### ISSUE TITLE
Blank screen after login

### ISSUE THREAD

**Issue by arudmin** [ajenti/ajenti#1020]
Absolutely clean OS, only Ajenti v1 installed and nginx 1.10. Log output below

02.02.2017 06:00 core.py:99                    INFO  Starting server on (u'0.0.0.0', 8000)
02.02.2017 06:00 __init__.py:207               DEBUG Root context instantiated [SessionMiddleware] <ajenti.middleware.SessionMiddleware object at 0x7f930b49c750>
02.02.2017 06:00 __init__.py:207               DEBUG Root context instantiated [AuthenticationMiddleware] <ajenti.middleware.AuthenticationMiddleware object at 0x7f930b49c450>
02.02.2017 06:00 __init__.py:207               DEBUG Root context instantiated [CentralDispatcher] <ajenti.routing.CentralDispatcher object at 0x7f930b49c2d0>
02.02.2017 06:00 core.py:135                   INFO  SSL enabled: /etc/ajenti/ajenti.pem
02.02.2017 06:00 __init__.py:207               DEBUG Root context instantiated [IPCServer] <ajenti.ipc.IPCServer object at 0x7f930b489e50>
02.02.2017 06:00 __init__.py:207               DEBUG Root context instantiated [Licensing] <ajenti.licensing.Licensing object at 0x7f930b489e10>
02.02.2017 06:00 feedback.py:30                DEBUG Feedback >> ping ({'edition': 'vanilla', 'version': '1.2.23.10', 'os': 'debian', 'id': 263938})
02.02.2017 06:00 connectionpool.py:188         INFO  Starting new HTTP connection (1): meta.ajenti.org
02.02.2017 06:00 connectionpool.py:362         DEBUG "POST /api/v2/ping HTTP/1.1" 200 36
02.02.2017 06:00 feedback.py:35                DEBUG Feedback << {"status": "ok"}
02.02.2017 06:00 __init__.py:207               DEBUG Root context instantiated [MainServer] <ajenti.plugins.main.main.MainServer object at 0x7f930b5522d0>
02.02.2017 06:00 __init__.py:207               DEBUG Root context instantiated [ContentServer] <ajenti.plugins.resources.server.ContentServer object at 0x7f930b59dbd0>
02.02.2017 06:00 __init__.py:207               DEBUG Root context instantiated [UploadReceiver] <ajenti.plugins.fm.fm.UploadReceiver object at 0x7f930b503c10>
02.02.2017 06:00 __init__.py:207               DEBUG Root context instantiated [TerminalHttp] <ajenti.plugins.terminal.main.TerminalHttp object at 0x7f930b569ed0>
02.02.2017 06:00 compat.py:20                  DEBUG Popen: ./compile_resources.py nocompress
02.02.2017 06:00 __init__.py:207               DEBUG Root context instantiated [ContentCompressor] <ajenti.plugins.resources.server.ContentCompressor object at 0x7f93097ae690>
02.02.2017 06:00 __init__.py:207               DEBUG Root context instantiated [UserManager] <ajenti.users.UserManager object at 0x7f93097aee50>
02.02.2017 06:00 __init__.py:207               DEBUG Root context instantiated [AjentiSyncProvider] <ajenti.usersync.local.AjentiSyncProvider object at 0x7f93097e2950>
02.02.2017 06:00 users.py:85                   INFO  user root logged in through AjentiSyncProvider from 217.148.209.50
02.02.2017 06:00 __init__.py:207               DEBUG [root] Context for root instantiated [MainServer] <ajenti.plugins.main.main.MainServer object at 0x7f93097aef10>
02.02.2017 06:00 __init__.py:207               DEBUG [root] Context for root instantiated [ContentServer] <ajenti.plugins.resources.server.ContentServer object at 0x7f93097e2350>
02.02.2017 06:00 __init__.py:207               DEBUG [root] Context for root instantiated [UploadReceiver] <ajenti.plugins.fm.fm.UploadReceiver object at 0x7f9310a4b8d0>
02.02.2017 06:00 __init__.py:207               DEBUG [root] Context for root instantiated [TerminalHttp] <ajenti.plugins.terminal.main.TerminalHttp object at 0x7f930b4952d0>
02.02.2017 06:00 compat.py:20                  DEBUG [root] Popen: ./compile_resources.py nocompress
02.02.2017 06:00 compat.py:20                  DEBUG [root] Popen: ./compile_resources.py nocompress
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 127, in wrap_socket_and_handle
    return self.handle(ssl_socket, address)
  File "/usr/lib/python2.7/dist-packages/socketio/server.py", line 124, in handle
    handler.handle()
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 443, in handle
    result = self.handle_one_request()
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 658, in handle_one_request
    self.handle_one_response()
  File "/usr/lib/pymodules/python2.7/ajenti/http.py", line 25, in handle_one_response
    return SocketIOHandler.handle_one_response(self)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 122, in handle_one_response
    return self._do_handshake(handshake_tokens.groupdict())
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 64, in _do_handshake
    self.write_smart(data)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 88, in write_smart
    self.write_plain_result(data)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 78, in write_plain_result
    ("Content-Type", "text/plain"),
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 778, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
<Greenlet at 0x7f930b8c3e10: _handle_and_close_when_done(<bound method SocketIOServer.wrap_socket_and_handl, <bound method SocketIOServer.do_close of <SocketIO, (<socket at 0x7f930b495110 fileno=[Errno 9] Bad fi)> failed with UnicodeError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 127, in wrap_socket_and_handle
    return self.handle(ssl_socket, address)
  File "/usr/lib/python2.7/dist-packages/socketio/server.py", line 124, in handle
    handler.handle()
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 443, in handle
    result = self.handle_one_request()
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 658, in handle_one_request
    self.handle_one_response()
  File "/usr/lib/pymodules/python2.7/ajenti/http.py", line 25, in handle_one_response
    return SocketIOHandler.handle_one_response(self)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 122, in handle_one_response
    return self._do_handshake(handshake_tokens.groupdict())
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 64, in _do_handshake
    self.write_smart(data)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 88, in write_smart
    self.write_plain_result(data)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 78, in write_plain_result
    ("Content-Type", "text/plain"),
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 778, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
<Greenlet at 0x7f930b8c3690: _handle_and_close_when_done(<bound method SocketIOServer.wrap_socket_and_handl, <bound method SocketIOServer.do_close of <SocketIO, (<socket at 0x7f930b436f10 fileno=[Errno 9] Bad fi)> failed with UnicodeError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 127, in wrap_socket_and_handle
    return self.handle(ssl_socket, address)
  File "/usr/lib/python2.7/dist-packages/socketio/server.py", line 124, in handle
    handler.handle()
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 443, in handle
    result = self.handle_one_request()
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 658, in handle_one_request
    self.handle_one_response()
  File "/usr/lib/pymodules/python2.7/ajenti/http.py", line 25, in handle_one_response
    return SocketIOHandler.handle_one_response(self)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 122, in handle_one_response
    return self._do_handshake(handshake_tokens.groupdict())
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 64, in _do_handshake
    self.write_smart(data)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 88, in write_smart
    self.write_plain_result(data)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 78, in write_plain_result
    ("Content-Type", "text/plain"),
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 778, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
<Greenlet at 0x7f930b8c3c30: _handle_and_close_when_done(<bound method SocketIOServer.wrap_socket_and_handl, <bound method SocketIOServer.do_close of <SocketIO, (<socket at 0x7f930b552290 fileno=[Errno 9] Bad fi)> failed with UnicodeError

**Comment by arudmin** [comment]
Admin panel after login
https://www.dropbox.com/s/dtsjq8kkxc2oy7b/Screenshot%202017-02-02%2009.07.54.jpg

**Comment by ghost** [comment]
I apt upgraded my Jessie and have the same screen after login.

**Comment by Gomah** [comment]
Same issue here with a clean install on Jessie, any update?

**Comment by Gomah** [comment]
Ok, same issue as #944.

This should do the trick:

```bash
# Install correct dependencies
sudo apt-get install python-dev libxml2-dev libxslt-dev python-setuptools

# Install gevent
sudo easy_install -U gevent==1.1b4

# Finally, restart ajenti
sudo service restart ajenti
```
