### ISSUE TITLE
Missing packages after script installations

### ISSUE THREAD

**Issue by LeonanCarvalho** [ajenti/ajenti#1021]
I used follow script to install (like in doc):
```
curl https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install.sh > install.sh && sudo bash 
install.sh
```

1st I got a version conflict, fixed with:
```
pip install psutil==2.2.1
```

2nd the module socketio wan't installed:
```
pip install python-socketio
``` 

And finally after fix 1st and 2nd problem, I got  it:
```
 ajenti-panel -v
08.02.2017 14:01  [...     3695]  DEBUG    Registering [aj.api.http.HttpMiddleware] (interface)
08.02.2017 14:01  [...     3695]  DEBUG    Registering [aj.api.http.HttpPlugin] (interface)
08.02.2017 14:01  [...     3695]  DEBUG    Registering [aj.api.http.SocketEndpoint] (interface)
08.02.2017 14:01  [...     3695]  DEBUG    Registering [aj.security.verifier.ClientCertificateVerificator] (service)
08.02.2017 14:01  [...     3695]  DEBUG    Registering [aj.auth.AuthenticationMiddleware] (service)
08.02.2017 14:01  [...     3695]  DEBUG    Registering [aj.auth.AuthenticationProvider] (interface)
08.02.2017 14:01  [...     3695]  DEBUG    Registering [aj.auth.OSAuthenticationProvider] (implementation of [aj.auth.AuthenticationProvider])
08.02.2017 14:01  [...     3695]  DEBUG    Registering [aj.auth.AuthenticationService] (service)
08.02.2017 14:01  [...     3695]  DEBUG    Registering [aj.auth.PermissionProvider] (interface)
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 123, in <module>
    plugin_providers=plugin_providers,
  File "/usr/lib/python2.7/site-packages/aj/entry.py", line 35, in start
    import aj.core
  File "/usr/lib/python2.7/site-packages/aj/core.py", line 18, in <module>
    from aj.gate.middleware import GateMiddleware
  File "/usr/lib/python2.7/site-packages/aj/gate/middleware.py", line 11, in <module>
    from socketio.namespace import BaseNamespace
ImportError: cannot import name BaseNamespace
```

Another informations:

- Python 2.7.5
- pip 9.0.1 from /usr/lib/python2.7/site-packages (python2.7)
- OS: Centos7 Linux localhost.localdomain 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by MatDepInfo** [comment]
Same... Have you find a solution ?
