### ISSUE TITLE
[2.0] Ajenti Service fails to start

### ISSUE THREAD

**Issue by MxtressMyxx** [ajenti/ajenti#1028]
```[root@localhost ~]# ajenti-panel -v
16.02.2017 04:18 ajenti-panel:105              INFO  Using config file /etc/ajenti/config.json
16.02.2017 04:18 ajenti-panel:130              INFO  Ajenti starting in foreground
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 137, in <module>
    from ajenti import core
  File "/usr/lib/python2.7/site-packages/ajenti/core.py", line 17, in <module>
    import ajenti.feedback
  File "/usr/lib/python2.7/site-packages/ajenti/feedback.py", line 8, in <module>
    import gevent
  File "/usr/lib64/python2.7/site-packages/gevent/__init__.py", line 51, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 31, in <module>
    from gevent._util import _NONE
ImportError: cannot import name _NONE
```

**Comment by MxtressMyxx** [comment]
```[root@localhost ~]# systemctl -l status ajenti.service
● ajenti.service - Ajenti panel
   Loaded: loaded (/usr/lib/systemd/system/ajenti.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2017-02-16 04:19:56 UTC; 7s ago
  Process: 11510 ExecStart=/bin/python /bin/ajenti-panel -d (code=exited, status=0/SUCCESS)
 Main PID: 11516 (code=exited, status=1/FAILURE)

Feb 16 04:19:56 localhost.localdomain systemd[1]: Starting Ajenti panel...
Feb 16 04:19:56 localhost.localdomain python[11510]: 2017-02-16 04:19:56,352 INFO     ajenti-panel.<module>(): Using config file /etc/ajenti/config.json
Feb 16 04:19:56 localhost.localdomain systemd[1]: PID file /var/run/ajenti.pid not readable (yet?) after start.
Feb 16 04:19:56 localhost.localdomain systemd[1]: Started Ajenti panel.
Feb 16 04:19:56 localhost.localdomain systemd[1]: ajenti.service: main process exited, code=exited, status=1/FAILURE
Feb 16 04:19:56 localhost.localdomain systemd[1]: Unit ajenti.service entered failed state.
Feb 16 04:19:56 localhost.localdomain systemd[1]: ajenti.service failed.```

**Comment by MxtressMyxx** [comment]
Fix one thing, make something new worse: don't know what I did: new logs.

```[root@localhost ~]# ajenti-panel -v
16.02.2017 04:28 ajenti-panel:105              INFO  Using config file /etc/ajenti/config.json
16.02.2017 04:28 ajenti-panel:130              INFO  Ajenti starting in foreground
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 137, in <module>
    from ajenti import core
  File "/usr/lib/python2.7/site-packages/ajenti/core.py", line 20, in <module>
    from ajenti.http import HttpRoot, RootHttpHandler
  File "/usr/lib/python2.7/site-packages/ajenti/http.py", line 9, in <module>
    from socketio.handler import SocketIOHandler
ImportError: No module named socketio.handler```

**Comment by muzzzdy** [comment]
So have you fixed "import _NONE" issue?

**Comment by MxtressMyxx** [comment]
Seems, so, but I don't know how. I updated/cleaned packages and tried a few threads with similar issues. Those logs are where I currently stand.

**Comment by zeroheure** [comment]
looks it try to run Ajenti 1.x because Ajenti 2 use config from /etc/ajenti/config.yml

**Comment by panpingusiowy** [comment]
I have same issue, it works fine until last server restart. It cannot start now and ajenti-panel -v says:

> File "/usr/bin/ajenti-panel", line 12, in <module>
    import aj.entry
  File "/usr/lib/python2.7/site-packages/aj/entry.py", line 7, in <module>
    from aj.util.pidfile import PidFile
  File "/usr/lib/python2.7/site-packages/aj/util/__init__.py", line 1, in <module>
    from aj.util.broadcast_queue import BroadcastQueue
  File "/usr/lib/python2.7/site-packages/aj/util/broadcast_queue.py", line 2, in <module>
    from gevent.queue import Queue
  File "/usr/lib64/python2.7/site-packages/gevent/__init__.py", line 51, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 31, in <module>
    from gevent._util import _NONE
ImportError: cannot import name _NONE
