### ISSUE TITLE
Saas Module configuration in odoo version 8.0

### ISSUE THREAD

**Issue by sathwiksunderreddy** [ajenti/ajenti#1047]
Hi 
Iam using Odoo 8 version I am trying to set Saas configuration on my odoo version i installed Saas module and able to create Server and Plan and Save it
After Creation of plan when I am trying to create Templatedb its giving below error I am unable to resolve it
When I try to Sync Server also it raises the below error can any one help me I am posting the Traceback of my issue below:

Traceback (most recent call last):
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\service\model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\web\controllers\main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\web\controllers\main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\saas_portal\models\saas_portal.py", line 344, in create_template_button
    res = self.create_template()
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\saas_portal\models\saas_portal.py", line 362, in create_template
    res = requests.Session().send(req, **req_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='sales', port=80): Max retries exceeded with url: /saas_server/new_database (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x092A1590>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',)

Thanks in Advance

**Comment by sathwiksunderreddy** [comment]
I tried to configure with both ^d% and ^%h for db-filter its rendering to database/manager page itself 
I am unable to login to odoo session nor the login page is coming

Please can you help me 
Thanks in Advance @jack-solution
