### ISSUE TITLE
Server error occured. This is likely a bug.

### ISSUE THREAD

**Issue by FOX61103** [ajenti/ajenti#1058]
Request
POST /api/core/auth

Type
TypeError

Message
expected string or buffer

Traceback
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ajenti_plugin_core/views/api.py", line 63, in handle_api_auth
    body_data = json.loads(http_context.body)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

How to fix it?

**Comment by Eugeny** [comment]
Fixed in 2.1.20

**Comment by okezieokpara** [comment]
What is the fix, because I am also getting this error and I don't know what to do.
