### ISSUE TITLE
Cannot Login: Authentication Faild

### ISSUE THREAD

**Issue by shahbaz-dev1** [ajenti/ajenti#1059]
I have installed Ajenti on Ubuntu and it was successful. I can access it at port :8000 . I am entering same credentials for root user which I use to access Linux via SSH. Usernname is root and password is system root password and each time it gives error "Authentication Failed" . Please guide me if I am doing wrong.

**Comment by Saliva520319** [comment]
Also meeeet the same problem, but I'm on Centos .
I wonder if anyone use this.

**Comment by timint** [comment]
+1 CentOS 7.4

**Comment by mihael147work** [comment]
+1 on Ubuntu 18.04

**Comment by lawrencebensaid** [comment]
+1 on Debian 10.4

**Comment by kiarn** [comment]
@lawrencebensaid :  do you have a visible error in `/var/log/ajenti/ajenti.log` ?

I've updated the documentation and the install script last month : I had no problem with Bionic, CentOS 8 or Debian 10.

**Comment by lawrencebensaid** [comment]
@kiarn Here is the `ajenti.log` for you.
```
2020-06-10 10:51:47,681 INFO    : Process 28338 exiting normally
2020-06-10 10:51:49,374 INFO    : Loading config from /etc/ajenti/config.yml
2020-06-10 10:51:49,378 INFO    : Ajenti Core 2.1.35
2020-06-10 10:51:49,378 INFO    : Master PID - 28969
2020-06-10 10:51:49,378 INFO    : Detected platform: debian gnu/linux / Debian GNU/Linux 10 (buster)
2020-06-10 10:51:49,378 INFO    : Python version: 3.7.3
2020-06-10 10:51:49,412 INFO    : Discovered 17 plugins
2020-06-10 10:51:49,552 ERROR   : [datetime]: plugin init failed: No implementation for [TZManager] is available
2020-06-10 10:51:49,552 ERROR   : Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aj/plugins.py", line 338, in load_all_from
    self.__init_plugin_module(name, self[name])
  File "/usr/local/lib/python3.7/dist-packages/aj/plugins.py", line 361, in __init_plugin_module
    mod.init(self)
  File "/usr/local/lib/python3.7/dist-packages/ajenti_plugin_datetime/__init__.py", line 9, in init
    api.TZManager.any(aj.context)
  File "/usr/local/lib/python3.7/dist-packages/jadi/jadi.py", line 129, in _any
    raise NoImplementationError(cls)
jadi.jadi.NoImplementationError: No implementation for [TZManager] is available

2020-06-10 10:51:49,554 ERROR   : [network]: plugin init failed: No implementation for [NetworkManager] is available
2020-06-10 10:51:49,554 ERROR   : Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aj/plugins.py", line 338, in load_all_from
    self.__init_plugin_module(name, self[name])
  File "/usr/local/lib/python3.7/dist-packages/aj/plugins.py", line 361, in __init_plugin_module
    mod.init(self)
  File "/usr/local/lib/python3.7/dist-packages/ajenti_plugin_network/__init__.py", line 10, in init
    api.NetworkManager.any(aj.context)
  File "/usr/local/lib/python3.7/dist-packages/jadi/jadi.py", line 129, in _any
    raise NoImplementationError(cls)
jadi.jadi.NoImplementationError: No implementation for [NetworkManager] is available

2020-06-10 10:51:49,554 INFO    : Loaded 15 plugins
2020-06-10 10:51:49,554 INFO    : Binding to [0.0.0.0]:8000
2020-06-10 10:51:49,562 INFO    : New worker "restricted session" PID 28978, EUID 0, EGID 0
2020-06-10 10:51:49,562 INFO    : Worker 28978 is demoting to UID 65534 / GID 65534...
2020-06-10 10:51:49,562 INFO    : ...done, new EUID 65534 EGID 65534
2020-06-10 10:52:03,091 WARNING : URL not found: /favicon.ico
```
