### ISSUE TITLE
Dockerized plugin development fails - 2.1.23

### ISSUE THREAD

**Issue by mickare** [ajenti/ajenti#1089]
Info | Value
----- | ------
Ajenti | 2.1.23 (via Install Script)
Platform | Docker (debian / ubuntu / Ubuntu 16.04 LTS)
Architecture | x86_64 x86_64
Python | 2.7.12
Installation | -
Debug | True
Catcher report |
Loaded plugins | Those from the Install-Script https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install.sh

## Description:

Hi,

I want to run Ajenti in a Docker container. Also I want to use a Docker container for development, so I have a consistent dev environment.

I can successful build the container, and run Ajenti inside. The plugin menu items are displayed correctly.

But when opening the view of the plugin the greenlet websocket fails. 
I followed the Installation procedure from the docs, if you want you can check the Dockerfile.

## Reproducibility

1. Clone my bootstrap plugin-dev project: https://github.com/mickare/ajenti-docker-plugin-dev
2. Run `./project.sh --setup` to create the docker image.
3. Run `./project.sh -n -b -r test_plugin` to create a new plugin, build it and run ajenti in dev mode.
4. Open in your local browser `localhost:8000` and click the test_plugin menu item.

## My first thoughts

Are there any undocumented ports used? If yes, which one?

## Log content:
```
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /view/test_plugin
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG    Building resources in /opt/ajenti/test_plugin
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG    Popen: ['ajenti-dev-multitool', '--rebuild']
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.752s      10.1 KB   200 GET /view/test_plugin
17.11.2017 20:44  [master    20]     websocket.py:368   DEBUG  Closed WebSocket
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /resources/all.vendor.css
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.007s       6.3 KB   200 GET /resources/all.vendor.css
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /resources/core/resources/vendor/pt-sans/styles/pt_sans.css
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /resources/core/resources/vendor/fontawesome/css/font-awesome.min.css
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /resources/all.css
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.007s  311.0 bytes   200 GET /resources/core/resources/vendor/pt-sans/styles/pt_sans.css
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.007s       5.9 KB   200 GET /resources/core/resources/vendor/fontawesome/css/font-awesome.min.css
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /resources/all.js
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.025s      26.0 KB   200 GET /resources/all.css
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.042s      25.3 KB   200 GET /resources/all.js
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /resources/all.init.js
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.047s  218.0 bytes   200 GET /resources/all.init.js
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /resources/all.vendor.js
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /resources/all.partials.js
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.133s     616.5 KB   200 GET /resources/all.vendor.js
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.130s      10.1 KB   200 GET /resources/all.partials.js
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /resources/core/resources/vendor/pt-sans/fonts/pt_sans/regular/PTS55F.woff
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.005s      26.4 KB   200 GET /resources/core/resources/vendor/pt-sans/fonts/pt_sans/regular/PTS55F.woff
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /api/core/identity
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.003s  178.0 bytes   200 GET /api/core/identity
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /api/core/sidebar
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.004s       1.8 KB   200 GET /api/core/sidebar
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /api/core/sidebar
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.004s       1.8 KB   200 GET /api/core/sidebar
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /resources/all.locale.js
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.004s   22.0 bytes   200 GET /resources/all.locale.js
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /resources/core/resources/vendor/fontawesome/fonts/fontawesome-webfont.woff2
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.009s      63.0 KB   200 GET /resources/core/resources/vendor/fontawesome/fonts/fontawesome-webfont.woff2
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /resources/core/resources/vendor/pt-sans/fonts/pt_sans/bold/PTS75F.woff
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.008s      26.8 KB   200 GET /resources/core/resources/vendor/pt-sans/fonts/pt_sans/bold/PTS75F.woff
17.11.2017 20:44  [master    20]    virtsocket.py:472   DEBUG  heartbeat timed out, killing socket
17.11.2017 20:44  [master    20]    virtsocket.py:230   DEBUG  Calling disconnect() on sessid='7218687215' client_queue[4] server_queue[1] hits=1
17.11.2017 20:44  [master    20]    middleware.py:64    DEBUG  Socket 139868938073168 disconnected
17.11.2017 20:44  [master    20]    virtsocket.py:243   DEBUG  Removing sessid='7218687215' client_queue[4] hits=1 from server sockets
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG    Socket namespace 139868938073168 is being destroyed
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG    Socket disconnected, destroying endpoints
17.11.2017 20:44  [master    20]       handler.py:68    DEBUG  Initializing WebSocket
17.11.2017 20:44  [master    20]       handler.py:100   DEBUG  Validating WebSocket request
17.11.2017 20:44  [master    20]       handler.py:151   DEBUG  Attempting to upgrade connection
17.11.2017 20:44  [master    20]       handler.py:230   DEBUG  WebSocket request accepted, switching protocols
17.11.2017 20:44  [master    20]    virtsocket.py:342   DEBUG  Spawning sub-Socket Greenlet: send_into_ws
17.11.2017 20:44  [master    20]    virtsocket.py:342   DEBUG  Spawning sub-Socket Greenlet: read_from_ws
17.11.2017 20:44  [master    20]    virtsocket.py:342   DEBUG  Spawning sub-Socket Greenlet: _heartbeat
17.11.2017 20:44  [master    20]    virtsocket.py:342   DEBUG  Spawning sub-Socket Greenlet: _heartbeat_timeout
17.11.2017 20:44  [master    20]    middleware.py:53    DEBUG  Socket 139868938167248 connected
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG    Socket namespace 139868938167248 created
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG    Spawning sub-Socket Greenlet (in a namespace): _reader
17.11.2017 20:44  [worker    32]          gate.py:110   DEBUG                        ... GET /api/core/tasks/request-update
17.11.2017 20:44  [master    20]    middleware.py:244   DEBUG  0.004s    4.0 bytes   200 GET /api/core/tasks/request-update
Socket is dead
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/socketio/transports.py", line 251, in send_into_ws
    websocket.send(message)
  File "/usr/local/lib/python2.7/dist-packages/geventwebsocket/websocket.py", line 347, in send
    raise WebSocketError(MSG_SOCKET_DEAD)
WebSocketError: Socket is dead
Fri Nov 17 20:44:23 2017 <Greenlet at 0x7f35c65e4230: send_into_ws> failed with WebSocketError



```

**Comment by mickare** [comment]
Example plugin generation is broken, see #1090
