### ISSUE TITLE
Isuue with CentOS -- :  ImportError: No module named 'requests.packages.urllib3' on ajenti-panel -v

### ISSUE THREAD

**Issue by njpsanghani** [ajenti/ajenti#1102]
[root@localhost Desktop]# ajenti-panel -v
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 11, in <module>
    import ajenti.log
  File "/usr/lib/python2.7/site-packages/ajenti/log.py", line 7, in <module>
    from ajenti.api import extract_context
  File "/usr/lib/python2.7/site-packages/ajenti/api/__init__.py", line 6, in <module>
    from ajenti.plugins import manager, PluginContext
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 9, in <module>
    from ajenti.util import *
  File "/usr/lib/python2.7/site-packages/ajenti/util.py", line 2, in <module>
    import catcher
  File "/usr/lib/python2.7/site-packages/catcher/__init__.py", line 2, in <module>
    from . import uploaders
  File "/usr/lib/python2.7/site-packages/catcher/uploaders/__init__.py", line 1, in <module>
    from .ajentiorg import AjentiOrgUploader
  File "/usr/lib/python2.7/site-packages/catcher/uploaders/ajentiorg.py", line 2, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from .packages.urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 95, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'requests.packages.urllib3'

**Comment by boymix81** [comment]
Solve running this:

`pip install requests urllib3 pyOpenSSL --force --upgrade`

Find solution here:
https://github.com/certbot/certbot/issues/5104
