### ISSUE TITLE
Ajenti 2 Ubuntu 16.04

### ISSUE THREAD

**Issue by ValkiryXDA** [ajenti/ajenti#1126]
Request
GET /api/plugins/pypi/list

Type
CalledProcessError

Message
Command '['pip', 'freeze']' returned non-zero exit status 1

Traceback
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ajenti_plugin_plugins/views.py", line 64, in handle_api_pypi_list
    for l in subprocess.check_output(['pip', 'freeze']).splitlines():
  File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 332, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
CalledProcessError: Command '['pip', 'freeze']' returned non-zero exit status 1

**Comment by wh0amll** [comment]
I've got the same issue! Have any ideas on how to fix it?
