### ISSUE TITLE
Can't start Ajenti [CentOS 7]

### ISSUE THREAD

**Issue by BitesizedLion** [ajenti/ajenti#1136]
[root@Ufo ~]# ajenti-panel
03.10.2018 18:30 INFO  Using config file /etc/ajenti/config.json
03.10.2018 18:30 INFO  Ajenti starting in foreground
Traceback (most recent call last):
  File "/bin/ajenti-panel", line 137, in <module>
    from ajenti import core
  File "/usr/lib/python2.7/site-packages/ajenti/core.py", line 18, in <module>
    import ajenti.licensing
  File "/usr/lib/python2.7/site-packages/ajenti/licensing.py", line 8, in <module>
    from ajenti.ipc import IPCHandler
  File "/usr/lib/python2.7/site-packages/ajenti/ipc.py", line 2, in <module>
    from gevent.pywsgi import WSGIServer, WSGIHandler
  File "/usr/lib64/python2.7/site-packages/gevent/pywsgi.py", line 6, in <module>
    import time
  File "/usr/lib64/python2.7/site-packages/gevent/time.py", line 19, in <module>
    from gevent._util import copy_globals
ImportError: cannot import name copy_globals
[root@Ufo ~]# sudo ajenti-panel
03.10.2018 18:30 INFO  Using config file /etc/ajenti/config.json
03.10.2018 18:30 INFO  Ajenti starting in foreground
Traceback (most recent call last):
  File "/bin/ajenti-panel", line 137, in <module>
    from ajenti import core
  File "/usr/lib/python2.7/site-packages/ajenti/core.py", line 18, in <module>
    import ajenti.licensing
  File "/usr/lib/python2.7/site-packages/ajenti/licensing.py", line 8, in <module>
    from ajenti.ipc import IPCHandler
  File "/usr/lib/python2.7/site-packages/ajenti/ipc.py", line 2, in <module>
    from gevent.pywsgi import WSGIServer, WSGIHandler
  File "/usr/lib64/python2.7/site-packages/gevent/pywsgi.py", line 6, in <module>
    import time
  File "/usr/lib64/python2.7/site-packages/gevent/time.py", line 19, in <module>
    from gevent._util import copy_globals
ImportError: cannot import name copy_globals
[root@Ufo ~]#

**Comment by MaximKiselev** [comment]
I think your problem in wrong version of gevent. Please, check that you use gevent 1.1b4

**Comment by BitesizedLion** [comment]
Already gave up and wiped my system so.
