### ISSUE TITLE
Ajenti 2.1.26 on Ubuntu 18.04, python 3: TypeError: Object of type 'bytes' is not JSON serializable

### ISSUE THREAD

**Issue by fransvanberckel** [ajenti/ajenti#1155]
I just setup a Ubuntu 18.04 with install.sh - 2.1.26, python3.6 and pip3 only. The install went fine. But starting ajenti-panel by systemd fails now with a clear error: Failed to start Ajenti panel.

Starting the panel from the prompt, as like systemd does ...

$ /usr/local/bin/ajenti-panel -d

Traceback (most recent call last):
  File "/usr/local/bin/ajenti-panel", line 123, in <module>
    plugin_providers=plugin_providers,
  File "/usr/local/lib/python3.6/dist-packages/aj/entry.py", line 25, in start
    with context:
  File "/usr/local/lib/python3.6/dist-packages/daemon/daemon.py", line 370, in __enter__
    self.open()
  File "/usr/local/lib/python3.6/dist-packages/daemon/daemon.py", line 354, in open
    exclude_fds = self._get_exclude_file_descriptors()
  File "/usr/local/lib/python3.6/dist-packages/daemon/daemon.py", line 438, in _get_exclude_file_descriptors
    files_preserve.extend(
AttributeError: 'range' object has no attribute 'extend'

**Comment by fransvanberckel** [comment]
Some feedback, I modified the install.sh, so it does python3 only ...

if [ "$OS" == "debian" ] ; then
    echo ":: Installing prerequisites"
    apt-get update
    DEBIAN_FRONTEND='noninteractive' apt-get install -y build-essential python3-pip python3-dev python3-setuptools python3-wheel python3-lxml libffi-dev libssl-dev libjpeg-dev libpng-dev uuid-dev python3-dbus python3-augeas python3-apt ntpdate || exit 1
fi

echo ":: Upgrading Python modules"
`which pip3` install -U psutil greenlet gevent
`which pip3` uninstall -y gevent-socketio

echo ":: Installing Ajenti"
`which pip3` install ajenti-panel ajenti.plugin.dashboard ajenti.plugin.settings ajenti.plugin.plugins ajenti.plugin.notepad ajenti.plugin.terminal ajenti.plugin.filemanager ajenti.plugin.packages ajenti.plugin.services ajenti.plugin.datetime || exit 1

**Comment by fransvanberckel** [comment]
Nice, the 'basestring' part (read the Ajenti aj plugin) is tweaked well by @kiarn thanks ...

| -  ({'path': x} if isinstance(x, basestring) else x)
| + ({'path': x} if isinstance(x, str) else x)

https://github.com/kiarn/ajenti/commit/7802e074d3c6afc4295f918305f4d4e60d623c16

**Comment by fransvanberckel** [comment]
Okay that's clear, there goes somewhere something wrong with the dependencies, so ...

$ pip3 install ajenti.plugin.core ajenti.plugin.ace ajenti.plugin.filesystem ajenti.plugin.passwd

Finding out the ajenti.plugin.datetime plugin needs pytz, so ...

$ pip3 install pytz

And the ajenti.plugin.terminal plugin needs PIL & pyte, but ...

$ pip3 install PIL

Collecting PIL
  Could not find a version that satisfies the requirement PIL (from versions: )
No matching distribution found for PIL

But that's solvable by ...

$ apt-get install python3-pil python3-pyte

**Comment by fransvanberckel** [comment]
This looks all fine now, without any error ...

$ /usr/local/bin/ajenti-panel -v

26.01.2019 20:18  [master  6346]          core.py:72    INFO   Loading config from /etc/ajenti/config.yml
26.01.2019 20:18  [master  6346]          core.py:90    INFO   Ajenti Core 2.1.26
26.01.2019 20:18  [master  6346]          core.py:91    INFO   Detected platform: debian / b'Ubuntu 18.04.1 LTS'
26.01.2019 20:18  [master  6346]       plugins.py:277   INFO   Discovered 13 plugins
26.01.2019 20:18  [master  6346]       plugins.py:345   INFO   Loaded 13 plugins
26.01.2019 20:18  [master  6346]          core.py:121   INFO   Binding to [0.0.0.0]:8000
26.01.2019 20:18  [rstrct  6357]          gate.py:110   INFO     New worker restricted session PID 6357, EUID 0, EGID 0
26.01.2019 20:18  [rstrct  6357]          gate.py:110   INFO     Worker 6357 is demoting to UID 65534 / GID 65534...
26.01.2019 20:18  [rstrct  6357]          gate.py:110   INFO     ...done, new EUID 65534 EGID 65534

But damm, again by Ajenti aj plugin, and it prints Internal Server Error in browser screen.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.6/dist-packages/gevent/pywsgi.py", line 923, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python3.6/dist-packages/aj/http.py", line 55, in dispatch
    content = self.handler.handle(http_context)
  File "/usr/local/lib/python3.6/dist-packages/aj/http.py", line 80, in handle
    output = middleware.handle(context)
  File "/usr/local/lib/python3.6/dist-packages/aj/gate/middleware.py", line 204, in handle
    rq = gate.stream.send(request_object)
  File "/usr/local/lib/python3.6/dist-packages/aj/gate/stream.py", line 75, in send
    for part in _seq_split(json.dumps(rq.serialize())):
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
2019-01-26T09:35:16Z {'REMOTE_ADDR': '192.168.1.45', 'REMOTE_PORT': '37642', 'HTTP_HOST': '192.168.1.253:8000', (hidden keys: 27)} failed with TypeError

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.6/dist-packages/gevent/pywsgi.py", line 923, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python3.6/dist-packages/aj/http.py", line 55, in dispatch
    content = self.handler.handle(http_context)
  File "/usr/local/lib/python3.6/dist-packages/aj/http.py", line 80, in handle
    output = middleware.handle(context)
  File "/usr/local/lib/python3.6/dist-packages/aj/gate/middleware.py", line 204, in handle
    rq = gate.stream.send(request_object)
  File "/usr/local/lib/python3.6/dist-packages/aj/gate/stream.py", line 75, in send
    for part in _seq_split(json.dumps(rq.serialize())):
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
2019-01-26T09:35:16Z {'REMOTE_ADDR': '192.168.1.45', 'REMOTE_PORT': '37644', 'HTTP_HOST': '192.168.1.253:8000', (hidden keys: 27)} failed with TypeError

**Comment by fransvanberckel** [comment]
To be clear, i parched aj/plugins.py, like @kiarn did ... so str could be cause.

 ({'path': x} if isinstance(x, basestring) else x)
 ({'path': x} if isinstance(x, str) else x)

**Comment by fransvanberckel** [comment]
@kiarn any idea, what i could try, for finding what goes wrong here? And are there dependencies that need to be a specific version?

**Comment by fransvanberckel** [comment]
$ pip3 check

gipc 1.0.0 has requirement gevent<1.4,>=1.2, but you have gevent 1.4.0.

That got to be gevent 1.3.7, the latest.

$ pip3 install --force-reinstall gevent==1.3.7

Collecting gevent==1.3.7
Requirement already satisfied: greenlet>=0.4.14 in /usr/local/lib/python3.6/dist-packages (from gevent==1.3.7)
Building wheels for collected packages: gevent
  Running setup.py bdist_wheel for gevent ... done
  Stored in directory: /root/.cache/pip/wheels/ef/67/a6/e6f2f9414dfdd943fb1aafdae3a2f82c8b3e16552d12500460
Successfully built gevent
Installing collected packages: gevent
  Found existing installation: gevent 1.4.0
    Uninstalling gevent-1.4.0:
      Successfully uninstalled gevent-1.4.0
Successfully installed gevent-1.3.7

$ pip3 check

No broken requirements found.

**Comment by kiarn** [comment]
Hello @fransvanberckel !

Thanks for your suggestion. Ajenti is a great project, and i'm trying to help, but my time is also limited.
I've created a new branch for a better support in Python3, and i'm working on it, but there's still some work for a complete support of Python 3.

In this case, it's necessary to decode the bytes as such as : 

    def serialize(self):
        self.object_tmp = {k.decode() : v for k, v in self.object.items() if isinstance(k, bytes)}
        return {
            'id': self.id.decode(),
            'object': self.object_tmp,
        }

instead of : 

    def serialize(self):
        return {
            'id': self.id,
            'object': self.object,
        }

in ajenti-core/aj/gate/stream.py on line 36.
Unfortunately, as I said, this will cause other errors because some response are empty.
And I have to test and check first if it fits for Python 2, and to be sure to completely solve this.

**Comment by fransvanberckel** [comment]
Great, and thanks. It's gonna be a work in progress, that's clear to me now.

Beware Python 2 goes and of life, within less then a year. For setup you are calling pip several times. So moving over to pip3, is the only way to go.

https://pythonclock.org/

And at least let me try to test the changesets on Python 3, so we know. ;-)

27.01.2019 08:36  [rstrct  1117]          gate.py:110   ERROR    Worker crashed!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aj/gate/worker.py", line 135, in run
    if rq.object['type'] == 'http':
KeyError: 'type'
27.01.2019 08:36  [...     1117]          gipc.py:607   DEBUG    Invalidating <_GIPCWriter_afd3e9 fd: 8> ...
27.01.2019 08:36  [...     1117]          gipc.py:607   DEBUG    Invalidating <_GIPCReader_4e83a2 fd: 9> ...
27.01.2019 08:36  [master  1106]          gipc.py:478   DEBUG  SIGCHLD watcher callback for 1117 invoked. Exitcode stored: 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.6/dist-packages/gevent/pywsgi.py", line 924, in run_application
    self.process_result()
  File "/usr/local/lib/python3.6/dist-packages/gevent/pywsgi.py", line 910, in process_result
    self.write(data)
  File "/usr/local/lib/python3.6/dist-packages/gevent/pywsgi.py", line 757, in write
    self._write_with_headers(data)
  File "/usr/local/lib/python3.6/dist-packages/gevent/pywsgi.py", line 778, in _write_with_headers
    self._write(data)
  File "/usr/local/lib/python3.6/dist-packages/gevent/pywsgi.py", line 742, in _write
    self._sendall(data)
  File "/usr/local/lib/python3.6/dist-packages/aj/wsgi.py", line 37, in _sendall
    data = six.binary_type(data) if data else data
TypeError: string argument without an encoding
2019-01-27T07:46:17Z {'REMOTE_ADDR': '192.168.1.45', 'REMOTE_PORT': '40846', 'HTTP_HOST': '192.168.1.253:8000', (hidden keys: 26)} failed with TypeError

**Comment by kiarn** [comment]
Hello @fransvanberckel ,
I think this is solved in the last commit https://github.com/ajenti/ajenti/commit/2d4cbab81f59c278f56f06315baf2f3f1dc1930c

The panel shows up, but all plugins are unfortunately not done ( dashboard seems to work ), I will do it later.

Can you please try and confirm this ?
