### ISSUE TITLE
Crash after fresh update

### ISSUE THREAD

**Issue by ghost** [ajenti/ajenti#1156]
Hey - I have fresh install of ajenti and I clicked to update anything.
I've checked [#891](https://github.com/ajenti/ajenti/issues/891) but it doesn't seems to be that thing.

I can't now restart ajenti.
Here is my system.
```bash
CentOS Linux release 7.6.1810 (Core)
```

Here are logs.
```bash
2019-01-25 20:34:45,824 INFO    : Subprocess PID 14077
2019-01-25 20:37:15,424 INFO    : Starting task 084aadcf3ccdf556df86417d369c810660d132690a5b75c6af34fa1ae3418852 (UpgradeAll)
2019-01-25 20:37:19,588 INFO    : Task 084aadcf3ccdf556df86417d369c810660d132690a5b75c6af34fa1ae3418852 finished
2019-01-25 20:37:22,350 WARNING : Restarting by request
2019-01-25 20:37:22,351 INFO    : Process 12975 exiting normally
2019-01-25 20:39:40,646 WARNING : stdout: Traceback (most recent call last):
2019-01-25 20:39:40,646 WARNING : stdout:   File "/bin/ajenti-panel", line 123, in <module>
2019-01-25 20:39:40,646 WARNING : stdout:
2019-01-25 20:39:40,646 WARNING : stdout: plugin_providers=plugin_providers,
2019-01-25 20:39:40,646 WARNING : stdout:   File "/usr/lib/python2.7/site-packages/aj/entry.py", line 28, in start
2019-01-25 20:39:40,646 WARNING : stdout:
2019-01-25 20:39:40,646 WARNING : stdout: import aj.core
2019-01-25 20:39:40,647 WARNING : stdout:   File "/usr/lib/python2.7/site-packages/aj/core.py", line 21, in <module>
2019-01-25 20:39:40,647 WARNING : stdout:
2019-01-25 20:39:40,647 WARNING : stdout: from aj.wsgi import RequestHandler
2019-01-25 20:39:40,647 WARNING : stdout:   File "/usr/lib/python2.7/site-packages/aj/wsgi.py", line 1, in <module>
2019-01-25 20:39:40,647 WARNING : stdout:
2019-01-25 20:39:40,647 WARNING : stdout: from socketio.handler import SocketIOHandler
2019-01-25 20:39:40,647 WARNING : stdout:   File "/usr/lib/python2.7/site-packages/socketio/handler.py", line 6, in <module>
2019-01-25 20:39:40,647 WARNING : stdout:
2019-01-25 20:39:40,647 WARNING : stdout: from gevent.pywsgi import WSGIHandler
2019-01-25 20:39:40,647 WARNING : stdout:   File "/usr/lib64/python2.7/site-packages/gevent/pywsgi.py", line 6, in <module>
2019-01-25 20:39:40,647 WARNING : stdout:
2019-01-25 20:39:40,647 WARNING : stdout: import time
2019-01-25 20:39:40,647 WARNING : stdout:   File "/usr/lib64/python2.7/site-packages/gevent/time.py", line 19, in <module>
2019-01-25 20:39:40,647 WARNING : stdout:
2019-01-25 20:39:40,647 WARNING : stdout: from gevent._util import copy_globals
2019-01-25 20:39:40,647 WARNING : stdout: ImportError
2019-01-25 20:39:40,648 WARNING : stdout: :
2019-01-25 20:39:40,648 WARNING : stdout: cannot import name copy_globals
2019-01-25 20:43:34,596 WARNING : stdout: Traceback (most recent call last):
2019-01-25 20:43:34,596 WARNING : stdout:   File "/bin/ajenti-panel", line 123, in <module>
2019-01-25 20:43:34,596 WARNING : stdout:
2019-01-25 20:43:34,596 WARNING : stdout: plugin_providers=plugin_providers,
2019-01-25 20:43:34,596 WARNING : stdout:   File "/usr/lib/python2.7/site-packages/aj/entry.py", line 28, in start
2019-01-25 20:43:34,596 WARNING : stdout:
2019-01-25 20:43:34,596 WARNING : stdout: import aj.core
2019-01-25 20:43:34,596 WARNING : stdout:   File "/usr/lib/python2.7/site-packages/aj/core.py", line 21, in <module>
2019-01-25 20:43:34,596 WARNING : stdout:
2019-01-25 20:43:34,597 WARNING : stdout: from aj.wsgi import RequestHandler
2019-01-25 20:43:34,597 WARNING : stdout:   File "/usr/lib/python2.7/site-packages/aj/wsgi.py", line 1, in <module>
2019-01-25 20:43:34,597 WARNING : stdout:
2019-01-25 20:43:34,597 WARNING : stdout: from socketio.handler import SocketIOHandler
2019-01-25 20:43:34,597 WARNING : stdout:   File "/usr/lib/python2.7/site-packages/socketio/handler.py", line 6, in <module>
2019-01-25 20:43:34,597 WARNING : stdout:
2019-01-25 20:43:34,597 WARNING : stdout: from gevent.pywsgi import WSGIHandler
```

**Comment by ghost** [comment]
I've reinstalled whole ajenti from scratch and works fine, but still I'm thinking what could cause this exactly.
