### ISSUE TITLE
Cannot bind <reconfigure.items.ajenti.SSLData object at 0x7fb2692e6390>

### ISSUE THREAD

**Issue by davodm** [ajenti/ajenti#1190]
Hi,
When I want to active my wildcard ssl certification, Ajenti returned this error, and configuration section disappeared:
```

Cannot bind <reconfigure.items.ajenti.SSLData object at 0x7fb2692e6390>.enable (<type 'int'>, = -1) to <checkbox # 9656>
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/main.py", line 161, in handle_message
    self.ui.dispatch_event(update['uid'], update['event'], update['params'])
  File "/usr/lib/pymodules/python2.7/ajenti/ui/__init__.py", line 72, in dispatch_event
    self.root.dispatch_event(uid, event, params)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 388, in dispatch_event
    getattr(self, k)(**(params or {}))
  File "/usr/lib/pymodules/python2.7/ajenti/users.py", line 18, in wrapper
    return fx(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/configurator/configurator.py", line 195, in save
    self.refresh()
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/configurator/configurator.py", line 180, in refresh
    self.binder.setup().populate()
  File "/usr/lib/pymodules/python2.7/ajenti/ui/binder.py", line 506, in setup
    self.__autodiscover()
  File "/usr/lib/pymodules/python2.7/ajenti/ui/binder.py", line 571, in __autodiscover
    self.__autodiscover(Binding.extract(object, k), bindable)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/binder.py", line 577, in __autodiscover
    self.add(PropertyBinding(object, k, bindable, propname))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/binder.py", line 135, in __init__
    raise Exception('Cannot bind %s.%s (%s, = %s) to %s' % (repr(obj), attribute, repr(type(v)), repr(v), ui))
Exception: Cannot bind <reconfigure.items.ajenti.SSLData object at 0x7fb2692e6390>.enable (<type 'int'>, = -1) to <checkbox # 9656>
```

**Comment by splaquet** [comment]
There's a few threads on this in the main forum 

In my case (Ubuntu 10.4), I had to edit config file and set SSL to false. I also removed tsl1.3 from one of the system files

**Comment by davodm** [comment]
I re-install ajenti again and again, test configuration via SSL tick, no SSL with TLS 1.3 or ...
nothing changed :/
