### ISSUE TITLE
'module' object is not callable.

### ISSUE THREAD

**Issue by fede1132** [ajenti/ajenti#1236]
Hardware: Raspberry Pi 3 B+
OS: Ubuntu 19.10 (Server Non-Desktop)
Crash report:
```
Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/aj/entry.py", line 37, in start
        aj.core.run(**kwargs)
      File "/usr/local/lib/python2.7/dist-packages/aj/core.py", line 208, in run
        gevent.signal(signal.SIGINT, signal_handler)
    TypeError: 'module' object is not callable
```

**Comment by kiarn** [comment]
Please see : https://github.com/ajenti/ajenti/issues/1232
