### ISSUE TITLE
write() argument must be str, not bytes 

### ISSUE THREAD

**Issue by Pingtado** [ajenti/ajenti#1270]
I've been getting python errors on a fresh install on Ubuntu 20.04

I have been able to reproduce this both in 

**system > network > network > update hostname:**

> ![image](https://user-images.githubusercontent.com/8573983/87243747-c0cb8f00-c438-11ea-9042-df6192a6250d.png)
> 
> Trace:
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/aj/api/endpoint.py", line 71, in wrapper
>     result = fx(self, context, *args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/ajenti_plugin_network/views.py", line 60, in handle_api_hostname_set
>     self.manager.set_hostname(http_context.body)
>   File "/usr/local/lib/python3.8/dist-packages/ajenti_plugin_network/managers/debian_manager.py", line 108, in set_hostname
>     f.write(value)
> TypeError: write() argument must be str, not bytes
> ```

**general > settings > generate self-signed certificate:**

> ![image](https://user-images.githubusercontent.com/8573983/87243731-aa253800-c438-11ea-8a12-429adecb99d8.png)
> 
> Trace: 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/aj/api/endpoint.py", line 71, in wrapper
>     result = fx(self, context, *args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/ajenti_plugin_settings/views.py", line 71, in handle_api_generate_server_certificate
>     f.write(dump_privatekey(FILETYPE_PEM, key))
> TypeError: write() argument must be str, not bytes
> 
> ```

**Comment by kiarn** [comment]
Hello @Pingtado 

Thanks for the report, I've just corrected the first one : https://github.com/kiarn/ajenti/commit/cc87ce6c391560ea4740afb6faefef53985ffab5

The second one was already corrected one week ago : https://github.com/kiarn/ajenti/commit/e16f229415f7471ede15a1dfb7a74776536223f7

Arnaud
