### ISSUE TITLE
Error opening network-page

### ISSUE THREAD

**Issue by delasource** [ajenti/ajenti#1289]
![image](https://user-images.githubusercontent.com/17216038/98599682-addca480-22dc-11eb-85bd-c94d72a51eac.png)
(i get 3 such messages at once)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aj/api/endpoint.py", line 71, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ajenti_plugin_network/views.py", line 30, in handle_api_state
    return self.manager.get_state(iface)
  File "/usr/local/lib/python3.7/dist-packages/ajenti_plugin_network/managers/debian_manager.py", line 94, in get_state
    'up': ifconfig_get_up(iface),
  File "/usr/local/lib/python3.7/dist-packages/ajenti_plugin_network/managers/ifconfig.py", line 18, in ifconfig_get_up
    return 'UP' in subprocess.check_output(['ifconfig', iface])
TypeError: a bytes-like object is required, not 'str'
```

ajenti.log
```
2020-11-09 22:40:03,711 ERROR   : Unhandled endpoint error at /api/network/state/lo
2020-11-09 22:40:03,713 ERROR   : Unhandled endpoint error at /api/network/state/enp3s0
2020-11-09 22:40:03,964 ERROR   : Unhandled endpoint error at /api/network/state/enp3s0
```

**Comment by kiarn** [comment]
Hello @genyx ,

Thanks for the report.
I made a fix for this : https://github.com/kiarn/ajenti/commit/202102a6eba4ea4f44d4ac9d625c789b6ed07e8b

**Comment by nlubello** [comment]
Tested the fix, works ok!
