### ISSUE TITLE
Cannot Login Ajenti on Ubuntu 18.04

### ISSUE THREAD

**Issue by HSBearBig** [ajenti/ajenti#1290]
I have already install completely and enter the login page
But whether I use root as username and root as password or my own user password, it's always show Authentication failed.
Pls help me about it. Thanks!><

**Comment by kiarn** [comment]
The best way to understand the problem is currently to run it in dev mode : 

```
systemctl stop ajenti
/usr/local/bin/ajenti-panel --dev
```
If there's some errors in the terminal, please post it here, I will have a look at it.

You can quit with Ctrl + C and then restart ajenti with `systemctl start ajenti`.

**Comment by HSBearBig** [comment]
```
13.11.2020 16:37  [...     1931]  DEBUG    Registering [aj.api.http.HttpMiddleware] (interface)
13.11.2020 16:37  [...     1931]  DEBUG    Registering [aj.api.http.HttpPlugin] (interface)
13.11.2020 16:37  [...     1931]  DEBUG    Registering [aj.api.http.SocketEndpoint] (interface)
13.11.2020 16:37  [...     1931]  DEBUG    Registering [aj.security.verifier.ClientCertificateVerificator] (service)
13.11.2020 16:37  [...     1931]  DEBUG    Registering [aj.auth.AuthenticationMiddleware] (service)
13.11.2020 16:37  [...     1931]  DEBUG    Registering [aj.auth.AuthenticationProvider] (interface)
13.11.2020 16:37  [...     1931]  DEBUG    Registering [aj.auth.OSAuthenticationProvider] (implementation of [aj.auth.AuthenticationProvider])
13.11.2020 16:37  [...     1931]  DEBUG    Registering [aj.auth.AuthenticationService] (service)
13.11.2020 16:37  [...     1931]  DEBUG    Registering [aj.auth.PermissionProvider] (interface)
13.11.2020 16:37  [...     1931]  DEBUG    Registering [aj.routing.CentralDispatcher] (service)
13.11.2020 16:37  [...     1931]  DEBUG    Registering [aj.gate.middleware.SocketIORouteHandler] (service)
13.11.2020 16:37  [...     1931]  DEBUG    Registering [aj.gate.middleware.GateMiddleware] (service)
13.11.2020 16:37  [...     1931]        compat.py:19    DEBUG    Popen: ('lsb_release', '-a')
13.11.2020 16:37  [...     1931]        compat.py:19    DEBUG    Popen: ('uname', '-rs')
13.11.2020 16:37  [...     1931]        compat.py:19    DEBUG    Popen: ['lsb_release', '-sd']
13.11.2020 16:37  [master  1931]          core.py:71    INFO   Loading config from /etc/ajenti/config.yml
13.11.2020 16:37  [master  1931]         entry.py:50    ERROR  Fatal crash occured
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aj/entry.py", line 40, in start
    aj.core.run(dev_mode=dev_mode, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/aj/core.py", line 72, in run
    aj.config.load()
  File "/usr/local/bin/ajenti-panel", line 30, in load
    self.data = yaml.load(open(self.path), Loader=yaml.Loader)
PermissionError: [Errno 13] Permission denied: '/etc/ajenti/config.yml'
13.11.2020 16:37  [master  1931]        compat.py:19    DEBUG  Popen: ['uname', '-mp']
13.11.2020 16:37  [master  1931]         entry.py:63    ERROR  Crash report written to ./ajenti-crash.txt
```

**Comment by kiarn** [comment]
Ok, then I need more informations : 

What's your OS ?
What is the output of `ls -al /etc/ajenti/` ?
What is the content of `/etc/ajenti/config.yml` ?

**Comment by HSBearBig** [comment]
OS: Ubuntu 18.04.5

```ls -al /etc/ajenti/``` show ```config.yml```

```/etc/ajenti/config.yml``` show
```
auth:
  allow_sudo: true
  emails: {}
  provider: os
  user_config: os
bind:
  host: 0.0.0.0
  mode: tcp
  port: 8000
color: default
max_sessions: 9
session_max_time: 3600
name: user-VirtualBox
ssl:
  certificate:
  fqdn_certificate:
  client_auth:
    certificates: []
    enable: false
    force: false
  enable: false
```

**Comment by kiarn** [comment]
And how did you start ajenti ?
If you are using Ubuntu, the right command should be `sudo /usr/local/bin/ajenti-panel --dev` (or launch as root)

> `ls -al /etc/ajenti/` show `config.yml`

The goal of this command was to see the permissions, e.g. something like : 

`-rw------- 1 root root 320 nov.  13 16:27 /etc/ajenti/config.yml`

**Comment by HSBearBig** [comment]
started by using ```service ajenti start```
```ls -al /etc/ajenti/``` show
```
總計 20
drwxr-xr-x   2 root root  4096 11月 13 16:54 .
drwxr-xr-x 125 root root 12288 11月 13 16:03 ..
-rw-------   1 root root   322 11月 13 16:03 config.yml
```

**Comment by kiarn** [comment]
Ok, the permissions are right.

> started by using `service ajenti start`

If you are logged as user, you should run it with sudo, or run it as root, because as a user ajenti will not be able to read the content of `/etc/ajenti/config.yml`

So, to find the problem, please try : 

```
sudo systemctl stop ajenti
sudo /usr/local/bin/ajenti-panel --dev
```

**Comment by HSBearBig** [comment]
I had find the problem. It's because I use Chinese as my language and lead to the unicode error.
Thanks about answering my question. Have a good day.
But another problem is when installing on "Ubuntu 20.04" it will ran error because of "greenlet". That's all.

**Comment by kiarn** [comment]
Thanks for the feedback, good to know where the error come from.
