### ISSUE TITLE
Debian 10: start ajenti service crash

### ISSUE THREAD

**Issue by alex-relov** [ajenti/ajenti#1300]
/var/log/ajenti/ajenti.log
```2020-12-05 23:43:50,255 INFO    : Loading config from /etc/ajenti/config.yml
2020-12-05 23:43:50,258 INFO    : Ajenti Core 2.1.37
2020-12-05 23:43:50,258 INFO    : Master PID - 8081
2020-12-05 23:43:50,258 INFO    : Detected platform: debian / Debian GNU/Linux 10 (buster)
2020-12-05 23:43:50,258 INFO    : Python version: 3.7.3
2020-12-05 23:43:50,284 INFO    : Discovered 12 plugins
2020-12-05 23:43:50,380 INFO    : Loaded 12 plugins
2020-12-05 23:43:50,381 INFO    : Binding to [0.0.0.0]:8005
2020-12-05 23:43:50,385 ERROR   : Fatal crash occured
2020-12-05 23:43:50,389 INFO    : New worker "restricted session" PID 8088, EUID 0, EGID 0
2020-12-05 23:43:50,389 INFO    : Worker 8088 is demoting to UID 65534 / GID 65534...
2020-12-05 23:43:50,389 INFO    : ...done, new EUID 65534 EGID 65534
2020-12-05 23:43:50,391 ERROR   : Crash report written to /var/log/ajenti/crash-2020-12-05-23h43.txt
2020-12-05 23:43:50,391 ERROR   : Please submit it to https://github.com/ajenti/ajenti/issues/new
```
/var/log/ajenti/crash-2020-12-05-23h43.txt
```
Ajenti bug report
--------------------


Info | Value
----- | -----
Ajenti | 2.1.37
Platform | debian / debian / Debian GNU/Linux 10 (buster)
Architecture | x86_64
Python | 3.7.3
Debug | False
Loaded plugins | ace, core, dashboard, filemanager, filesystem, notepad, packages, passwd, plugins, services, settings, terminal

Library | Version
------- | -------
gevent | 20.9.0
greenlet | 0.4.17
psutil | 5.7.3


    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/aj/entry.py", line 31, in start
        aj.core.run(dev_mode=dev_mode, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/aj/core.py", line 209, in run
        gevent.signal(signal.SIGINT, signal_handler)
    TypeError: 'module' object is not callable
```
systemctl status ajenti.service
```
● ajenti.service - Ajenti panel
   Loaded: loaded (/lib/systemd/system/ajenti.service; enabled; vendor preset: enabled)
   Active: activating (start-post) since Sat 2020-12-05 23:52:35 AKST; 28s ago
  Process: 8184 ExecStart=/usr/bin/python3 /usr/local/bin/ajenti-panel -d (code=exited, status=0/SUCCESS)
  Process: 8187 ExecStartPost=/bin/sleep 5 (code=exited, status=0/SUCCESS)
    Tasks: 2 (limit: 2330)
   Memory: 42.3M
   CGroup: /system.slice/ajenti.service
           ├─8186 /usr/bin/python3 /usr/local/bin/ajenti-panel -d
           └─8194 /usr/local/bin/ajenti-panel worker [restricted session]

Dec 05 23:52:35 BuildServer systemd[1]: Starting Ajenti panel...
Dec 05 23:52:40 BuildServer systemd[1]: ajenti.service: Can't open PID file /run/ajenti.pid (yet?) after start-post: No such file or directory
```

**Comment by kiarn** [comment]
Hello @alex-relov ,

You should use a lower version of `gevent` and `greenlet`, so as root : 

`python3 -m pip install gevent==1.3.7 greenlet==0.4.16`

**Comment by zs-gabor** [comment]
Hi,
With the specified versions of gevent==1.3.7 and greenlet==0.4.16  works for me on Debian 10.
