### ISSUE TITLE
Cannot install Network plugin

### ISSUE THREAD

**Issue by PrzemekSkw** [ajenti/ajenti#1313]
Hello, I install Ajenti today for first time on my Debian 10 VPS server. I have installed openvpn server there. I setbind IP in Ajenti Panel to my vpn IP 10.8.0.1 to login only when I'm connected as vpn client. 
1. I have problem installing network plugin. In panel there's everything OK but when I restart I see network plugin not installed. When I install in ssh console:
```
~$ sudo pip3 install ajenti.plugin.network
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Requirement already satisfied: ajenti.plugin.network in /usr/local/lib/python3.7/dist-packages (0.25)
Requirement already satisfied: ajenti.plugin.augeas in /usr/local/lib/python3.7/dist-packages (from ajenti.plugin.network) (0.17)
Requirement already satisfied: aj in /usr/local/lib/python3.7/dist-packages (from ajenti.plugin.network) (2.1.37)
Requirement already satisfied: ajenti.plugin.core in /usr/local/lib/python3.7/dist-packages (from ajenti.plugin.network) (0.97)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (5.4.1)
Requirement already satisfied: pyOpenSSL==19.1.0 in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (19.1.0)
Requirement already satisfied: pexpect in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (4.8.0)
Requirement already satisfied: greenlet==0.4.16 in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (0.4.16)
Requirement already satisfied: requests>=2 in /usr/lib/python3/dist-packages (from aj->ajenti.plugin.network) (2.21.0)
Requirement already satisfied: gevent-socketio-hartwork>=0.3.6 in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (0.3.6.post201803091952)
Requirement already satisfied: lxml>=2.2.4 in /usr/lib/python3/dist-packages (from aj->ajenti.plugin.network) (4.3.2)
Requirement already satisfied: gevent>=1 in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (1.3.7)
Requirement already satisfied: python-daemon-3k in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (1.5.8)
Requirement already satisfied: termcolor in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (1.1.0)
Requirement already satisfied: setproctitle in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (1.2.2)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from aj->ajenti.plugin.network) (1.12.0)
Requirement already satisfied: passlib in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (1.7.4)
Requirement already satisfied: setuptools>=41 in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (53.0.0)
Requirement already satisfied: distro in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (1.5.0)
Requirement already satisfied: psutil>=2.2.1 in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (5.8.0)
Requirement already satisfied: cookies in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (2.2.1)
Requirement already satisfied: pip>=20 in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (21.0.1)
Requirement already satisfied: simplejson in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (3.17.2)
Requirement already satisfied: gipc in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (1.1.0)
Requirement already satisfied: gevent-websocket in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (0.10.1)
Requirement already satisfied: jadi>=1.0.3 in /usr/local/lib/python3.7/dist-packages (from aj->ajenti.plugin.network) (1.0.3)
Requirement already satisfied: cryptography>=2.8 in /usr/local/lib/python3.7/dist-packages (from pyOpenSSL==19.1.0->aj->ajenti.plugin.network) (3.4.5)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography>=2.8->pyOpenSSL==19.1.0->aj->ajenti.plugin.network) (1.14.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography>=2.8->pyOpenSSL==19.1.0->aj->ajenti.plugin.network) (2.20)
Requirement already satisfied: python-augeas in /usr/lib/python3/dist-packages (from ajenti.plugin.augeas->ajenti.plugin.network) (0.5.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect->aj->ajenti.plugin.network) (0.7.0)
Requirement already satisfied: lockfile>=0.7 in /usr/local/lib/python3.7/dist-packages (from python-daemon-3k->aj->ajenti.plugin.network) (0.12.2)
```
regards,
Przemek

**Comment by kiarn** [comment]
Hello @PrzemekSkw, 

Wenn ajenti is running, do you see an entry `Network` in the sidebar ?

Regards,

Arnaud

**Comment by PrzemekSkw** [comment]
Hi @kiarn there's no network entry in sidebar. I have hosts, session list but no network. After i install from plugins menu and restart dashboard I still see it like not installed.
Regards, 
Przemek

**Comment by kiarn** [comment]
Ok, my bad, I can confirm the problem, I've overseen a line in the code.

In `/usr/local/lib/python3.7/dist-packages/ajenti_plugin_network/managers/debian_manager.py` line 26, replacing : 

```
return aj.platform in ['debian'] and check_prior_ubuntu
```

through

```
return aj.platform in ['debian'] or check_prior_ubuntu
```

and then restarting `Ajenti` should do the trick : 

```
systemctl restart ajenti.service
```

If you are using another version of Python, just change it in the above path.

Regards

Arnaud

**Comment by PrzemekSkw** [comment]
Thanks, that help.
But I noticed another issue with `404 - Page not found` when open Session List in tools section. It works when I delete one `/`at the end of url.
![image](https://user-images.githubusercontent.com/25219988/108256533-f0284400-715d-11eb-8c10-7924deb56f04.png)

**Comment by kiarn** [comment]
Yep thanks, it is already fixed sinde december : https://github.com/ajenti/ajenti/commit/0a382b35d06af99b1ab8ea1f3c4697831d842937

Will come in next release.

**Comment by PrzemekSkw** [comment]
Thanks, I see there's another error when installed docker plugin. When I open docker tab I see multiple windows with error:
![Zrzut ekranu z 2021-02-18 08-33-09](https://user-images.githubusercontent.com/25219988/108321179-184a8e00-71c4-11eb-978d-6ff43f08a576.png)
and new windows keep opening.
Full Traceback entry:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aj/api/endpoint.py", line 71, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ajenti_plugin_docker/views.py", line 26, in handle_api_resources_docker
    command = self.docker + ['stats', '--format', '\'{{json .}}\'', '--no-stream', '-a']
TypeError: can only concatenate str (not "list") to str
```
Regards,
Przemek

**Comment by kiarn** [comment]
Thanks for your tests !

It's fixed : https://github.com/kiarn/ajenti/commit/4ca873da6606517b0864b215484a15b0dd820944

**Comment by PrzemekSkw** [comment]
Thanks, for great project. Can You tell me it's possible to see clients connected to my openvpn server in Ajenti?

Regards,
Przemek

**Comment by kiarn** [comment]
I think this should be possible, but I don't have the time to do this.

Maybe you can try to adapt the [plugin template](https://github.com/ajenti/plugin-template) and make our own ?
There's some explanations here : https://docs.ajenti.org/en/latest/dev/intro.html

Regards

Arnaud

**Comment by PrzemekSkw** [comment]
OK, I understand. Maybe someone will make this because I'm not programmer and don't know how to do this.
Regards,
Przemek.
