### ISSUE TITLE
Request POST /api/core/auth =  a bytes-like object is required, not 'str' 

### ISSUE THREAD

**Issue by dropitlikecross** [ajenti/ajenti#1323]
Request
`POST /api/core/auth`
Type
`TypeError`
Message
`a bytes-like object is required, not 'str'`
Traceback

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aj/api/endpoint.py", line 75, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ajenti_plugin_core/views/api.py", line 116, in handle_api_auth
    if auth.check_sudo_password(username, password):
  File "/usr/local/lib/python3.8/dist-packages/aj/auth.py", line 158, in check_sudo_password
    o, e = sudo.communicate(password + '\n')
  File "/usr/local/lib/python3.8/dist-packages/gevent/subprocess.py", line 850, in communicate
    greenlet.get()
  File "src/gevent/greenlet.py", line 769, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception
  File "/usr/local/lib/python3.8/dist-packages/gevent/_compat.py", line 62, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/subprocess.py", line 506, in _write_and_close
    fobj.write(data)
TypeError: a bytes-like object is required, not 'str'

```
During elevation after clicking on Authenticate. Ubuntu 20.04.

**Comment by kiarn** [comment]
Please see : https://github.com/ajenti/ajenti/issues/1302#issuecomment-808045293

**Comment by dropitlikecross** [comment]
Cheers @kiarn i'll try it out. Any idea why this happens? It seems to only effect a few users.

**Comment by kiarn** [comment]
It happens because I forgot to correct it when I migrate `ajenti` to `python3`. It will come in the next version.

**Comment by jccore** [comment]
Failed when trying to elevate privileges

System: Ubuntu server 20.04 LTS

Server error
Server error occured. This is likely a bug.
Request
POST /api/core/auth
Type
TypeError
Message
a bytes-like object is required, not 'str'
Traceback
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/aj/api/endpoint.py", line 75, in wrapper
result = fx(self, context, *args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/ajenti_plugin_core/views/api.py", line 116, in handle_api_auth
if auth.check_sudo_password(username, password):
File "/usr/local/lib/python3.8/dist-packages/aj/auth.py", line 158, in check_sudo_password
o, e = sudo.communicate(password + '\n')
File "/usr/local/lib/python3.8/dist-packages/gevent/subprocess.py", line 850, in communicate
greenlet.get()
File "src/gevent/greenlet.py", line 769, in gevent._greenlet.Greenlet.get
File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception
File "/usr/local/lib/python3.8/dist-packages/gevent/_compat.py", line 62, in reraise
raise value.with_traceback(tb)
File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
File "/usr/local/lib/python3.8/dist-packages/gevent/subprocess.py", line 506, in _write_and_close
fobj.write(data)
TypeError: a bytes-like object is required, not 'str'

I make the suggested changes

File "/usr/local/lib/python3.8/dist-packages/aj/auth.py", line 158
o, e = sudo.communicate(input=(password + '\n').encode('utf-8'))
...
raise SudoError((o + e).decode('utf-8').splitlines()[-1].strip())

I add the suggested lines in the file etc/sudoers

Defaults:nobody targetpw
nobody  ALL=(ALL) /bin/ls

And it keeps giving error

**Comment by jccore** [comment]
Solved, I did not put Defaults **":"**, in the file /etc/sudoers
