### ISSUE TITLE
Raspbian 10 "buster", network plugin is not working

### ISSUE THREAD

**Issue by tonjo** [ajenti/ajenti#1325]
Relevant error is

```
2021-04-12 22:23:40,737 ERROR   : [network]: plugin init failed: No implementation for [NetworkManager] is available
2021-04-12 22:23:40,738 ERROR   : Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aj/plugins.py", line 346, in load_all_from
    self.__init_plugin_module(name, self[name])
  File "/usr/local/lib/python3.7/dist-packages/aj/plugins.py", line 369, in __init_plugin_module
    mod.init(self)
  File "/usr/local/lib/python3.7/dist-packages/ajenti_plugin_network/__init__.py", line 10, in init
    api.NetworkManager.any(aj.context)
  File "/usr/local/lib/python3.7/dist-packages/jadi/jadi.py", line 129, in _any
    raise NoImplementationError(cls)
jadi.jadi.NoImplementationError: No implementation for [NetworkManager] is available
```

NOTE: I had to manually install some packages, such as libtiff5, libxslt1, etc., not documented

**Comment by kiarn** [comment]
Hello @tonjo,

Raspbian is not officially supported for installing `Ajenti`, because of the compilation of `gevent`. But it would be a good option to install `Ajenti` on it, so I will have a look at it next week, and see if it's possible to adapt the install script.

Do you remember which packages you have to install in order to start `Ajenti` ? 
This would spare me some time.

**Comment by kiarn** [comment]
I have installed `Ajenti 2` on a `Raspbian 10`. Indeed, it's necessary to install some additional packages and to prevent `pip` to build `cryptography` with `rust` ( see : https://github.com/docker/compose/issues/8105 ).

After that, `Ajenti` starts and I can't reproduce your error : the network does not throw an error, even if the network informations are incomplete.

So I think I will need more details in order to help you.
