### ISSUE TITLE
Can't open PID file /run/ajenti.pid (yet?) after start-post: Operation not permitted

### ISSUE THREAD

**Issue by AliKhadivi** [ajenti/ajenti#1328]
Hello
I installed this control panel yesterday and it was installed correctly and it was safe and it worked.
Then I installed some community plugins and got the following error.

```
root@jalbo:~# systemctl status ajenti.service
● ajenti.service - Ajenti panel
     Loaded: loaded (/lib/systemd/system/ajenti.service; enabled; vendor preset: enabled)
     Active: failed (Result: protocol) since Tue 2021-05-11 07:17:51 EDT; 4h 22min ago

May 11 07:17:46 jalbo.ir-meet systemd[1]: Starting Ajenti panel...
May 11 07:17:51 jalbo.ir-meet systemd[1]: ajenti.service: Can't open PID file /run/ajenti.pid (yet?) after start-post: Operation not permitted
May 11 07:17:51 jalbo.ir-meet systemd[1]: ajenti.service: Failed with result 'protocol'.
May 11 07:17:51 jalbo.ir-meet systemd[1]: Failed to start Ajenti panel.
```
And when I run `/usr/local/bin/ajenti-panel --dev` Command, it gives the following error ↓
```
root@jalbo:~# /usr/local/bin/ajenti-panel --dev
11.05.2021 11:47  [...    681659]  DEBUG    Registering [aj.api.http.HttpMiddleware] (interface)
11.05.2021 11:47  [...    681659]  DEBUG    Registering [aj.api.http.HttpPlugin] (interface)
11.05.2021 11:47  [...    681659]  DEBUG    Registering [aj.api.http.SocketEndpoint] (interface)
11.05.2021 11:47  [...    681659]  DEBUG    Registering [aj.security.verifier.ClientCertificateVerificator] (service)
11.05.2021 11:47  [...    681659]  DEBUG    Registering [aj.auth.AuthenticationMiddleware] (service)
11.05.2021 11:47  [...    681659]  DEBUG    Registering [aj.auth.AuthenticationProvider] (interface)
11.05.2021 11:47  [...    681659]  DEBUG    Registering [aj.auth.OSAuthenticationProvider] (implementation of [aj.auth.AuthenticationProvider])
11.05.2021 11:47  [...    681659]  DEBUG    Registering [aj.auth.AuthenticationService] (service)
11.05.2021 11:47  [...    681659]  DEBUG    Registering [aj.auth.PermissionProvider] (interface)
11.05.2021 11:47  [...    681659]  DEBUG    Registering [aj.routing.CentralDispatcher] (service)
11.05.2021 11:47  [...    681659]  DEBUG    Registering [aj.gate.middleware.SocketIORouteHandler] (service)
11.05.2021 11:47  [...    681659]  DEBUG    Registering [aj.gate.middleware.GateMiddleware] (service)
11.05.2021 11:47  [...    681659]        compat.py:19    DEBUG    Popen: ('lsb_release', '-a')
11.05.2021 11:47  [...    681659]        compat.py:19    DEBUG    Popen: ('uname', '-rs')
11.05.2021 11:47  [...    681659]        compat.py:19    DEBUG    Popen: ['lsb_release', '-sd']
11.05.2021 11:47  [master 681659]          core.py:72    INFO   Loading config from /etc/ajenti/config.yml
11.05.2021 11:47  [master 681659]          core.py:76    INFO   Loading users from /etc/ajenti/users.yml
11.05.2021 11:47  [master 681659]          core.py:81    WARN   Debug mode
11.05.2021 11:47  [master 681659]          core.py:83    WARN   Dev mode
11.05.2021 11:47  [master 681659]          core.py:94    INFO   Ajenti Core 2.1.40
11.05.2021 11:47  [master 681659]          core.py:95    INFO   Master PID - 681659
11.05.2021 11:47  [master 681659]          core.py:96    INFO   Detected platform: debian / Ubuntu 20.04.2 LTS
11.05.2021 11:47  [master 681659]          core.py:97    INFO   Python version: 3.8.5
11.05.2021 11:47  [master 681659]       plugins.py:67    DEBUG  Looking for plugins in /usr/local/bin
11.05.2021 11:47  [master 681659]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python3.8
11.05.2021 11:47  [master 681659]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python3.8/lib-dynload
11.05.2021 11:47  [master 681659]       plugins.py:67    DEBUG  Looking for plugins in /usr/local/lib/python3.8/dist-packages
11.05.2021 11:47  [master 681659]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python3/dist-packages
11.05.2021 11:47  [master 681659]         entry.py:50    ERROR  Fatal crash occured
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aj/entry.py", line 39, in start
    aj.core.run(dev_mode=dev_mode, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/aj/core.py", line 100, in run
    PluginManager.get(aj.context).load_all_from(aj.plugin_providers)
  File "/usr/local/lib/python3.8/dist-packages/aj/plugins.py", line 274, in load_all_from
    yml_info = yaml.load(open(os.path.join(path, 'plugin.yml')), Loader=yaml.SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 408, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:aj.plugins.PluginDependency'
  in "/usr/local/lib/python3.8/dist-packages/ajenti_plugin_cpu_temp/plugin.yml", line 9, column 7
11.05.2021 11:47  [master 681659]        compat.py:19    DEBUG  Popen: ['uname', '-m']
11.05.2021 11:47  [master 681659]         entry.py:63    ERROR  Crash report written to /var/log/ajenti/crash-2021-05-11-11h47.txt
11.05.2021 11:47  [master 681659]         entry.py:64    ERROR  Please submit it to https://github.com/ajenti/ajenti/issues/new
```
OS : Ubuntu 20.04 focal

**Comment by kiarn** [comment]
Hello @AliKhadivi 

The syntax to solve the dependencies was simplified in the last version, and maybe the community plugin was not aware of this.
If you change the string `!!python/object:aj.plugins.PluginDependency` into `!PluginDependency` in `/usr/local/lib/python3.8/dist-packages/ajenti_plugin_cpu_temp/plugin.yml` it should solve your problem.

Arnaud

**Comment by AliKhadivi** [comment]
Thank for your good and fast replay. 
Its works very good.
