### ISSUE TITLE
 Check Certificates plugin error

### ISSUE THREAD

**Issue by AliKhadivi** [ajenti/ajenti#1329]
Hello
I get the following error when I enter the "Check Certificates" page ↓
https://dl.fcms.ir/media/image/ajenti.png

And when I add a site, I get the following error ↓
https://dl.fcms.ir/media/image/ajenti2.png
```
Server error occured. This is likely a bug.
Request
POST /api/check_cert/test
Type
Error
Message
unsupported locale setting
Traceback

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aj/api/endpoint.py", line 75, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ajenti_plugin_check_certificates/views.py", line 35, in handle_api_check_cert
    return json.loads(json.dumps(checkOnDom(*url.split(':'))))
  File "/usr/local/lib/python3.8/dist-packages/ajenti_plugin_check_certificates/api.py", line 78, in checkOnDom
    locale.setlocale(locale.LC_ALL, 'en_GB.UTF-8')
  File "/usr/lib/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
And when I enable "Developer mode" with the command `/usr/local/bin/ajenti-panel --dev`, I get the following error
``` 
12.05.2021 02:54  [...    703839]  DEBUG    Registering [aj.api.http.HttpMiddleware] (interface)
12.05.2021 02:54  [...    703839]  DEBUG    Registering [aj.api.http.HttpPlugin] (interface)
12.05.2021 02:54  [...    703839]  DEBUG    Registering [aj.api.http.SocketEndpoint] (interface)
12.05.2021 02:54  [...    703839]  DEBUG    Registering [aj.security.verifier.ClientCertificateVerificator] (service)
12.05.2021 02:54  [...    703839]  DEBUG    Registering [aj.auth.AuthenticationMiddleware] (service)
12.05.2021 02:54  [...    703839]  DEBUG    Registering [aj.auth.AuthenticationProvider] (interface)
12.05.2021 02:54  [...    703839]  DEBUG    Registering [aj.auth.OSAuthenticationProvider] (implementation of [aj.auth.AuthenticationProvider])
12.05.2021 02:54  [...    703839]  DEBUG    Registering [aj.auth.AuthenticationService] (service)
12.05.2021 02:54  [...    703839]  DEBUG    Registering [aj.auth.PermissionProvider] (interface)
12.05.2021 02:54  [...    703839]  DEBUG    Registering [aj.routing.CentralDispatcher] (service)
12.05.2021 02:54  [...    703839]  DEBUG    Registering [aj.gate.middleware.SocketIORouteHandler] (service)
12.05.2021 02:54  [...    703839]  DEBUG    Registering [aj.gate.middleware.GateMiddleware] (service)
12.05.2021 02:54  [...    703839]        compat.py:19    DEBUG    Popen: ('lsb_release', '-a')
12.05.2021 02:54  [...    703839]        compat.py:19    DEBUG    Popen: ('uname', '-rs')
12.05.2021 02:54  [...    703839]        compat.py:19    DEBUG    Popen: ['lsb_release', '-sd']
12.05.2021 02:54  [master 703839]          core.py:72    INFO   Loading config from /etc/ajenti/config.yml
12.05.2021 02:54  [master 703839]          core.py:76    INFO   Loading users from /etc/ajenti/users.yml
12.05.2021 02:54  [master 703839]          core.py:81    WARN   Debug mode
12.05.2021 02:54  [master 703839]          core.py:83    WARN   Dev mode
12.05.2021 02:54  [master 703839]          core.py:94    INFO   Ajenti Core 2.1.40
12.05.2021 02:54  [master 703839]          core.py:95    INFO   Master PID - 703839
12.05.2021 02:54  [master 703839]          core.py:96    INFO   Detected platform: debian / Ubuntu 20.04.2 LTS
12.05.2021 02:54  [master 703839]          core.py:97    INFO   Python version: 3.8.5
12.05.2021 02:54  [master 703839]       plugins.py:67    DEBUG  Looking for plugins in /usr/local/bin
12.05.2021 02:54  [master 703839]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python3.8
12.05.2021 02:54  [master 703839]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python3.8/lib-dynload
12.05.2021 02:54  [master 703839]       plugins.py:67    DEBUG  Looking for plugins in /usr/local/lib/python3.8/dist-packages
12.05.2021 02:54  [master 703839]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python3/dist-packages
12.05.2021 02:54  [master 703839]       plugins.py:285   INFO   Discovered 21 plugins
12.05.2021 02:54  [master 703839]       plugins.py:333   DEBUG  Resolved load order for 21 plugins: ['core', 'cron', 'plugins', 'passwd', 'dashboard', 'filesystem', 'ace', 'session_list', 'auth_users', 'augeas', 'filemanager', 'network', 'terminal', 'cpu_temp', 'services', 'traffic', 'settings', 'check_certificates', 'packages', 'datetime', 'notepad']
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "core"
12.05.2021 02:54  [master 703839]          jadi.py:136   DEBUG  Registering [aj.plugins.core.api.sidebar.SidebarItemProvider] (interface)
12.05.2021 02:54  [master 703839]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.sidebar.Sidebar] (service)
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.core.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.core.main.Permissions] (implementation of [aj.auth.PermissionProvider])
12.05.2021 02:54  [master 703839]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.navbox.Navbox] (service)
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.core.views.api.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.core.views.config.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.core.views.main.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.core.views.resource_server.ResourcesHandler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.push.Push] (service)
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.core.views.push.PushSocket] (implementation of [aj.api.http.SocketEndpoint])
12.05.2021 02:54  [master 703839]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.tasks.TasksService] (service)
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.core.views.tasks.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "cron"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.cron.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
12.05.2021 02:54  [master 703839]          jadi.py:70    DEBUG  Registering [aj.plugins.cron.manager.CronManager] (service)
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.cron.views.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]      __init__.py:5     INFO   extra_crontab.__init__.py: extra_crontab loaded
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "plugins"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.plugins.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.plugins.views.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "passwd"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.passwd.views.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "dashboard"
12.05.2021 02:54  [master 703839]          jadi.py:136   DEBUG  Registering [aj.plugins.dashboard.api.Widget] (interface)
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.dashboard.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.dashboard.views.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.dashboard.widgets.cpu.CPUWidget] (implementation of [aj.plugins.dashboard.api.Widget])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.dashboard.widgets.hostname.HostnameWidget] (implementation of [aj.plugins.dashboard.api.Widget])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.dashboard.widgets.loadavg.LoadAverageWidget] (implementation of [aj.plugins.dashboard.api.Widget])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.dashboard.widgets.memory.MemoryWidget] (implementation of [aj.plugins.dashboard.api.Widget])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.dashboard.widgets.uptime.UptimeWidget] (implementation of [aj.plugins.dashboard.api.Widget])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "filesystem"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.filesystem.main.Permissions] (implementation of [aj.auth.PermissionProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.filesystem.views.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "ace"
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "session_list"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.session_list.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.session_list.views.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "auth_users"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.auth_users.api.UsersAuthenticationProvider] (implementation of [aj.auth.AuthenticationProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.auth_users.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.auth_users.views.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "augeas"
12.05.2021 02:54  [master 703839]        compat.py:19    DEBUG  Popen: ['/sbin/ldconfig', '-p']
12.05.2021 02:54  [master 703839]          jadi.py:136   DEBUG  Registering [aj.plugins.augeas.api.AugeasEndpoint] (interface)
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.augeas.views.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "filemanager"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.filemanager.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "network"
12.05.2021 02:54  [master 703839]          jadi.py:136   DEBUG  Registering [aj.plugins.network.api.NetworkManager] (interface)
12.05.2021 02:54  [master 703839]        compat.py:19    DEBUG  Popen: ['which', 'ifconfig']
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.network.managers.debian_manager.DebianNetworkManager] (implementation of [aj.plugins.network.api.NetworkManager])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.network.managers.ubuntu_manager.UbuntuNetworkManager] (implementation of [aj.plugins.network.api.NetworkManager])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "terminal"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.terminal.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.terminal.main.Permissions] (implementation of [aj.auth.PermissionProvider])
12.05.2021 02:54  [master 703839]          jadi.py:70    DEBUG  Registering [aj.plugins.terminal.manager.TerminalManager] (service)
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.terminal.views.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.terminal.views.Socket] (implementation of [aj.api.http.SocketEndpoint])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "cpu_temp"
12.05.2021 02:54  [master 703839]       plugins.py:340   ERROR  [cpu_temp]: plugin import failed: No module named 'main'
12.05.2021 02:54  [master 703839]       plugins.py:341   ERROR  Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aj/plugins.py", line 337, in load_all_from
    self.__import_plugin_module(name, self[name])
  File "/usr/local/lib/python3.8/dist-packages/aj/plugins.py", line 359, in __import_plugin_module
    info['module'] = imp.load_module(
  File "/usr/lib/python3.8/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.8/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/ajenti_plugin_cpu_temp/__init__.py", line 1, in <module>
    import main
ModuleNotFoundError: No module named 'main'

12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "services"
12.05.2021 02:54  [master 703839]          jadi.py:136   DEBUG  Registering [aj.plugins.services.api.ServiceManager] (interface)
12.05.2021 02:54  [master 703839]        compat.py:19    DEBUG  Popen: ['which', 'systemctl']
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.services.managers.systemd_manager.SystemdServiceManager] (implementation of [aj.plugins.services.api.ServiceManager])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.services.managers.sysv_manager.SysVServiceManager] (implementation of [aj.plugins.services.api.ServiceManager])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.services.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.services.main.Permissions] (implementation of [aj.auth.PermissionProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.services.views.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "traffic"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.traffic.views.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.traffic.widget.TrafficWidget] (implementation of [aj.plugins.dashboard.api.Widget])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "settings"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.settings.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.settings.views.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "check_certificates"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.check_certificates.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.check_certificates.views.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "packages"
12.05.2021 02:54  [master 703839]          jadi.py:136   DEBUG  Registering [aj.plugins.packages.api.PackageManager] (interface)
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.packages.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.packages.main.Permissions] (implementation of [aj.auth.PermissionProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.packages.views.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.packages.managers.apt_manager.APTPackageManager] (implementation of [aj.plugins.packages.api.PackageManager])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.packages.managers.pip_manager.PIPPackageManager] (implementation of [aj.plugins.packages.api.PackageManager])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "datetime"
12.05.2021 02:54  [master 703839]          jadi.py:136   DEBUG  Registering [aj.plugins.datetime.api.TZManager] (interface)
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.datetime.managers.debian_manager.DebianTZManager] (implementation of [aj.plugins.datetime.api.TZManager])
12.05.2021 02:54  [master 703839]       plugins.py:356   DEBUG  Importing plugin "notepad"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.notepad.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "core"
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "cron"
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "plugins"
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "passwd"
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "dashboard"
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "filesystem"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.filesystem.widget.DiskWidget] (implementation of [aj.plugins.dashboard.api.Widget])
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "ace"
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "session_list"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.session_list.widget.SessionWidget] (implementation of [aj.plugins.dashboard.api.Widget])
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "auth_users"
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "augeas"
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "filemanager"
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "network"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.network.aug.ResolvConfEndpoint] (implementation of [aj.plugins.augeas.api.AugeasEndpoint])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.network.aug.HostsEndpoint] (implementation of [aj.plugins.augeas.api.AugeasEndpoint])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.network.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.network.main.Permissions] (implementation of [aj.auth.PermissionProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.network.views.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "terminal"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.terminal.widget.ScriptWidget] (implementation of [aj.plugins.dashboard.api.Widget])
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "services"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.services.widget.ServiceWidget] (implementation of [aj.plugins.dashboard.api.Widget])
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "traffic"
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "settings"
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "check_certificates"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.check_certificates.widget.CertWidget] (implementation of [aj.plugins.dashboard.api.Widget])
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "packages"
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "datetime"
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.datetime.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.datetime.main.Permissions] (implementation of [aj.auth.PermissionProvider])
12.05.2021 02:54  [master 703839]          jadi.py:161   DEBUG  Registering [aj.plugins.datetime.views.Handler] (implementation of [aj.api.http.HttpPlugin])
12.05.2021 02:54  [master 703839]       plugins.py:366   DEBUG  Initializing plugin "notepad"
12.05.2021 02:54  [master 703839]       plugins.py:353   INFO   Loaded 20 plugins
12.05.2021 02:54  [master 703839]          core.py:127   INFO   Binding to [0.0.0.0]:8000
12.05.2021 02:54  [master 703839]          core.py:131   ERROR  Could not bind: [Errno 98] Address already in use
```
OS : Ubuntu 20.04 focal

**Comment by kiarn** [comment]
Hello @AliKhadivi ,

Using `en_GB.UTF-8` was a bad idea from me, as I was the only user of this plugin.
Is it better if you replace `en_GB.UTF-8` with `C.UTF-8` ?

**Comment by AliKhadivi** [comment]
Thanks for your help
