### ISSUE TITLE
Workaround for package search not working? ("PyPI XMLRPC Search Disabled" - https://status.python.org/)

### ISSUE THREAD

**Issue by ReessKennedy** [ajenti/ajenti#1333]
I really wanted to play around with Ajenti. Design is so much simpler than other panels and I love the cohesive design of the built in file manager and terminal app. That said, I don't seem to able to install any packages or plugins. Packages returns the error below which is because Python has shut down an API that was being abused. Any workaround for this? Keep up the good work here with Ajenti. 

PyPI XMLRPC Search Disabled: https://status.python.org/

<img width="1205" alt="Screen Shot 2021-06-26 at 10 01 15 PM" src="https://user-images.githubusercontent.com/3970267/123530624-923ad880-d6ca-11eb-854c-a3c49d96f152.png">

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aj/api/endpoint.py", line 75, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ajenti_plugin_packages/views.py", line 80, in handle_api_list
    for package in self.managers[manager_id].list(query=query)
  File "/usr/local/lib/python3.6/site-packages/ajenti_plugin_packages/views.py", line 79, in <listcomp>
    self.__package_to_json(package)
  File "/usr/local/lib/python3.6/site-packages/ajenti_plugin_packages/managers/pip_manager.py", line 78, in list
    for dist in self.client.search({'name': query}):
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -32500: "RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.">

**Comment by kiarn** [comment]
Hello @ReessKennedy 

I'm already aware of this problem. the reason behind is that the [search has been disabled due of flood on the servers. Even the command `pip search` has been disabled.](https://github.com/pypa/pip/issues/5216)

One solution for this would be to retrieve and parse the content of https://pypi.org/simple/. But with nearly 300 000 packages, it's painfully slow to get the right information.
