### ISSUE TITLE
Error upon running Ajenti

### ISSUE THREAD

**Issue by Edward-Deakin** [ajenti/ajenti#1354]
```root@vmi712034:/lib# ajenti-panel --dev
20.11.2021 12:06  [...    451899]  DEBUG    Registering [aj.api.http.HttpMiddleware] (interface)
20.11.2021 12:06  [...    451899]  DEBUG    Registering [aj.api.http.HttpPlugin] (interface)
20.11.2021 12:06  [...    451899]  DEBUG    Registering [aj.api.http.SocketEndpoint] (interface)
20.11.2021 12:06  [...    451899]  DEBUG    Registering [aj.security.verifier.ClientCertificateVerificator] (service)
20.11.2021 12:06  [...    451899]  DEBUG    Registering [aj.auth.AuthenticationMiddleware] (service)
20.11.2021 12:06  [...    451899]  DEBUG    Registering [aj.auth.AuthenticationProvider] (interface)
20.11.2021 12:06  [...    451899]  DEBUG    Registering [aj.auth.OSAuthenticationProvider] (implementation of [aj.auth.AuthenticationProvider])
20.11.2021 12:06  [...    451899]  DEBUG    Registering [aj.auth.AuthenticationService] (service)
20.11.2021 12:06  [...    451899]  DEBUG    Registering [aj.auth.PermissionProvider] (interface)
20.11.2021 12:06  [...    451899]  DEBUG    Registering [aj.routing.CentralDispatcher] (service)
20.11.2021 12:06  [...    451899]  DEBUG    Registering [aj.gate.middleware.SocketIORouteHandler] (service)
20.11.2021 12:06  [...    451899]  DEBUG    Registering [aj.gate.middleware.GateMiddleware] (service)
20.11.2021 12:06  [...    451899]        compat.py:19    DEBUG    Popen: ('lsb_release', '-a')
20.11.2021 12:06  [...    451899]        compat.py:19    DEBUG    Popen: ('uname', '-rs')
20.11.2021 12:06  [...    451899]        compat.py:19    DEBUG    Popen: ['lsb_release', '-sd']
20.11.2021 12:06  [master 451899]          core.py:72    INFO   Loading config from /etc/ajenti/config.yml
20.11.2021 12:06  [master 451899]          core.py:76    INFO   Loading users from /etc/ajenti/users.yml
20.11.2021 12:06  [master 451899]          core.py:81    WARN   Debug mode
20.11.2021 12:06  [master 451899]          core.py:83    WARN   Dev mode
20.11.2021 12:06  [master 451899]          core.py:94    INFO   Ajenti Core 2.1.43
20.11.2021 12:06  [master 451899]          core.py:95    INFO   Master PID - 451899
20.11.2021 12:06  [master 451899]          core.py:96    INFO   Detected platform: debian / Ubuntu 21.04
20.11.2021 12:06  [master 451899]          core.py:97    INFO   Python version: 3.9.5
20.11.2021 12:06  [master 451899]       plugins.py:67    DEBUG  Looking for plugins in /usr/local/bin
20.11.2021 12:06  [master 451899]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python3.9
20.11.2021 12:06  [master 451899]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python3.9/lib-dynload
20.11.2021 12:06  [master 451899]       plugins.py:67    DEBUG  Looking for plugins in /usr/local/lib/python3.9/dist-packages
20.11.2021 12:06  [master 451899]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python3/dist-packages
20.11.2021 12:06  [master 451899]         entry.py:50    ERROR  Fatal crash occured
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aj/entry.py", line 39, in start
    aj.core.run(dev_mode=dev_mode, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/aj/core.py", line 100, in run
    PluginManager.get(aj.context).load_all_from(aj.plugin_providers)
  File "/usr/local/lib/python3.9/dist-packages/aj/plugins.py", line 274, in load_all_from
    yml_info = yaml.load(open(os.path.join(path, 'plugin.yml')), Loader=yaml.SafeLoader)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 408, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:aj.plugins.PluginDependency'
  in "/usr/local/lib/python3.9/dist-packages/ajenti_plugin_cpu_temp/plugin.yml", line 9, column 7
20.11.2021 12:06  [master 451899]        compat.py:19    DEBUG  Popen: ['uname', '-m']
20.11.2021 12:06  [master 451899]         entry.py:63    ERROR  Crash report written to /var/log/ajenti/crash-2021-11-20-12h06.txt
20.11.2021 12:06  [master 451899]         entry.py:64    ERROR  Please submit it to https://github.com/ajenti/ajenti/issues/new```

**Comment by Edward-Deakin** [comment]
Wait I figured this out - CPU Temperature is blocked on my VPS. Can you find a way to remove that plugin?

**Comment by kiarn** [comment]
Hello,

There's many issues relating the problem you have. Please see https://github.com/ajenti/ajenti/issues/1344

Arnaud

**Comment by Edward-Deakin** [comment]
Thanks It worked!

**Comment by kiarn** [comment]
So, I can close it :)
