### ISSUE TITLE
Issue with connecting to panel

### ISSUE THREAD

**Issue by Edward-Deakin** [ajenti/ajenti#1355]
```Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.9/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.9/dist-packages/gevent/server.py", line 233, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.9/dist-packages/aj/core.py", line 180, in <lambda>
    aj.server.wrap_socket = lambda socket, **args:context.wrap_socket(sock=socket, server_side=True)
  File "/usr/local/lib/python3.9/dist-packages/gevent/_ssl3.py", line 114, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.9/dist-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/usr/local/lib/python3.9/dist-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.9/dist-packages/gevent/_ssl3.py", line 667, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:1129)
2021-11-20T12:14:57Z <Greenlet at 0x7fa51ec159d0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <SocketIOSe, (<gevent._socket3.socket [closed] at 0x7fa51ebe3ac)> failed with SSLError ```

**Comment by Edward-Deakin** [comment]
This is when running ajenti-panel -v

**Comment by Edward-Deakin** [comment]
@kiarn

**Comment by cloudwindy** [comment]
You are using HTTP protocol. You should use https:// to use HTTPS protocol.

**Comment by Edward-Deakin** [comment]
Yeah, I realised that literally a minute before you sent this. Thanks anyway, Ill close this now!
