### ISSUE TITLE
Bug Report: Environment LANG and LANGUAGE Causes UnicodeError

### ISSUE THREAD

**Issue by cloudwindy** [ajenti/ajenti#1359]
UnicodeError occurs if ajenti isn't started with environment ```LANG=en_US LANGUAGE=en```
Error log as follows:
```
21.11.2021 22:14  [master 624080]    middleware.py:244   DEBUG  0.032s       4.3 KB   200 GET /resources/core/resources/vendor/fontawesome/css/v4-shims.css
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gevent/pywsgi.py", line 860, in start_response
    value if not PY3 else value.encode("latin-1")))
UnicodeEncodeError: 'latin-1' codec can't encode character '\u516d' in position 0: ordinal not in range(256)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gevent/pywsgi.py", line 999, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.9/dist-packages/gevent/pywsgi.py", line 945, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python3.9/dist-packages/aj/http.py", line 62, in dispatch
    http_context.run_response()
  File "/usr/local/lib/python3.9/dist-packages/aj/http.py", line 237, in run_response
    self.start_response(
  File "/usr/local/lib/python3.9/dist-packages/gevent/pywsgi.py", line 863, in start_response
    raise UnicodeError("Non-latin1 header", repr(header), repr(value))
UnicodeError: ('Non-latin1 header', "'Last-Modified'", "'六, 11月 20 2021 20:45:15 GMT'")
2021-11-21T14:14:35Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '36092', 'HTTP_HOST': '[REDACTED]', (hidden keys: 43)} failed with UnicodeError
```

**Comment by cloudwindy** [comment]
The Chinese characters translate to "六(Six), 11 月(Month) 20 2021 20:45:15 GMT"

**Comment by cloudwindy** [comment]
Duplicate to #1348. Closing
