### ISSUE TITLE
Bug Report: Network Doesn't Work On Ubuntu 21.10 "impish"

### ISSUE THREAD

**Issue by cloudwindy** [ajenti/ajenti#1362]
Error as follows:
```
Request
GET /api/network/config/get

Type
KeyError

Message
'addresses'

Traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aj/api/endpoint.py", line 75, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/ajenti_plugin_network/views.py", line 32, in handle_api_config_get
    return self.manager.get_config()
  File "/usr/local/lib/python3.9/dist-packages/ajenti_plugin_network/managers/ubuntu_manager.py", line 55, in get_config
    'address': config[key]['addresses'][0],
KeyError: 'addresses'
```

**Comment by kiarn** [comment]
Hello @cloudwindy 

I will try it in a virtual machine and see what happen.

**Comment by kiarn** [comment]
Ok, confirmed, I need a netplan parser ...

**Comment by cloudwindy** [comment]
Always happy to hear from you. Please keep me informed.

**Comment by kiarn** [comment]
Hello,

I made a minimal fix to let it work, but I will have to do it properly later.
