### ISSUE TITLE
Bug Report: Add Password Check to auth_user Plugin

### ISSUE THREAD

**Issue by cloudwindy** [ajenti/ajenti#1371]
```
Request
POST /api/core/auth

Type
KeyError

Message
'password'

Traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aj/api/endpoint.py", line 75, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/ajenti_plugin_core/views/api.py", line 99, in handle_api_auth
    auth_info = auth.check_password(username, password)
  File "/usr/local/lib/python3.9/dist-packages/aj/auth.py", line 147, in check_password
    return self.get_provider().authenticate(username, password)
  File "/usr/local/lib/python3.9/dist-packages/ajenti_plugin_auth_users/api.py", line 39, in authenticate
    user_hash = aj.users.data['users'][username]['password']
KeyError: 'password'
```

**Comment by kiarn** [comment]
Hello,

Ok, I will add some checks, but if you want to create a new user, you will have to set a password for this user.

**Comment by cloudwindy** [comment]
Thank you for your help. Please close this when you have added checks.

**Comment by cloudwindy** [comment]
Oh man, Github down again, lol.

Kientz Arnaud ***@***.***> 于2021年11月28日周日 上午3:51写道：
