### ISSUE TITLE
venv install error - Debian Bullseye on  arm64 (aarch64)

### ISSUE THREAD

**Issue by dkebler** [ajenti/ajenti#1400]
ran the venv install script.
`https://github.com/ajenti/ajenti/blob/master/scripts/install-venv.sh`
`curl https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install-venv.sh | sudo bash -s -`

was all looking good until building psutil
debian bulleseye (dietpi) running on arm64 box (rockpro64)

What more info do you need?

Looks like core stuff might be finde so I'll try to fire up panel server

```
Building wheel for psutil (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for psutil (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [101 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-3.9
      creating build/lib.linux-aarch64-3.9/psutil
      copying psutil/_pswindows.py -> build/lib.linux-aarch64-3.9/psutil
      copying psutil/_pssunos.py -> build/lib.linux-aarch64-3.9/psutil
      copying psutil/_psposix.py -> build/lib.linux-aarch64-3.9/psutil
      copying psutil/_psosx.py -> build/lib.linux-aarch64-3.9/psutil
      copying psutil/_pslinux.py -> build/lib.linux-aarch64-3.9/psutil
      copying psutil/_psbsd.py -> build/lib.linux-aarch64-3.9/psutil
      copying psutil/_psaix.py -> build/lib.linux-aarch64-3.9/psutil
      copying psutil/_compat.py -> build/lib.linux-aarch64-3.9/psutil
      copying psutil/_common.py -> build/lib.linux-aarch64-3.9/psutil
      copying psutil/__init__.py -> build/lib.linux-aarch64-3.9/psutil
      creating build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/test_windows.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/test_unicode.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/test_testutils.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/test_system.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/test_sunos.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/test_process.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/test_posix.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/test_osx.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/test_misc.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/test_memleaks.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/test_linux.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/test_contracts.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/test_connections.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/test_bsd.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/test_aix.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/runner.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/foo.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/__main__.py -> build/lib.linux-aarch64-3.9/psutil/tests
      copying psutil/tests/__init__.py -> build/lib.linux-aarch64-3.9/psutil/tests
      running build_ext
      building 'psutil._psutil_linux' extension
      creating build/temp.linux-aarch64-3.9
      creating build/temp.linux-aarch64-3.9/psutil
      aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-PN012d/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=591 -DPSUTIL_LINUX=1 -I/opt/ajenti/include -I/usr/include/python3.9 -c psutil/_psutil_common.c -o build/temp.linux-aarch64-3.9/psutil/_psutil_common.o
      aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-PN012d/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=591 -DPSUTIL_LINUX=1 -I/opt/ajenti/include -I/usr/include/python3.9 -c psutil/_psutil_linux.c -o build/temp.linux-aarch64-3.9/psutil/_psutil_linux.o
      aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-PN012d/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=591 -DPSUTIL_LINUX=1 -I/opt/ajenti/include -I/usr/include/python3.9 -c psutil/_psutil_posix.c -o build/temp.linux-aarch64-3.9/psutil/_psutil_posix.o
      aarch64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 build/temp.linux-aarch64-3.9/psutil/_psutil_common.o build/temp.linux-aarch64-3.9/psutil/_psutil_linux.o build/temp.linux-aarch64-3.9/psutil/_psutil_posix.o -L/usr/lib -o build/lib.linux-aarch64-3.9/psutil/_psutil_linux.cpython-39-aarch64-linux-gnu.so
      building 'psutil._psutil_posix' extension
      aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-PN012d/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=591 -DPSUTIL_LINUX=1 -I/opt/ajenti/include -I/usr/include/python3.9 -c psutil/_psutil_common.c -o build/temp.linux-aarch64-3.9/psutil/_psutil_common.o
      aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-PN012d/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=591 -DPSUTIL_LINUX=1 -I/opt/ajenti/include -I/usr/include/python3.9 -c psutil/_psutil_posix.c -o build/temp.linux-aarch64-3.9/psutil/_psutil_posix.o
      aarch64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 build/temp.linux-aarch64-3.9/psutil/_psutil_common.o build/temp.linux-aarch64-3.9/psutil/_psutil_posix.o -L/usr/lib -o build/lib.linux-aarch64-3.9/psutil/_psutil_posix.cpython-39-aarch64-linux-gnu.so
      installing to build/bdist.linux-aarch64/wheel
      running install
      running install_lib
      Traceback (most recent call last):
        File "/opt/ajenti/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/opt/ajenti/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/ajenti/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 216, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 253, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 145, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 449, in <module>
          main()
        File "setup.py", line 421, in main
          setup(**kwargs)
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 259, in run
          self.run_command('install')
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/install.py", line 578, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 985, in run_command
          cmd_obj.ensure_finalized()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
          self.set_undefined_options('install',('install_layout','install_layout'))
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 290, in set_undefined_options
          setattr(self, dst_option, getattr(src_cmd_obj, src_option))
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: install_layout
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
  Building wheel for termcolor (setup.py) ... done
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4832 sha256=2e0d6c8aa5c5017b3fd6c560b1f85921a581db2e9a23f5d4db497bd29f738317
  Stored in directory: /root/.cache/pip/wheels/b6/0d/90/0d1bbd99855f99cb2f6c2e5ff96f8023fad8ec367695f7d72d
Successfully built ajenti-panel aj gipc ajenti.plugin.core ajenti.plugin.dashboard ajenti.plugin.settings ajenti.plugin.plugins ajenti.plugin.notepad ajenti.plugin.terminal ajenti.plugin.filemanager ajenti.plugin.packages ajenti.plugin.services jadi ajenti.plugin.ace ajenti.plugin.filesystem ajenti.plugin.passwd bs4 termcolor
Failed to build psutil
ERROR: Could not build wheels for psutil, which is required to install pyproject.toml-based projects
```

**Comment by dkebler** [comment]
I commented out the `|| exit` so the script would continue....but
the $PANEL variable is not being set in the script so the systemd service is failing
`PANEL=$(which ajenti-panel)`

**Comment by kiarn** [comment]
Hello @dkebler ,

Providing wheel packages for `psutil` for aarch64 is still under development : https://github.com/giampaolo/psutil/pull/2070
I'm afraid we will have to wait until this is done, because one of the main plugin of `Ajenti` ( dashboard ) can not work without `psutil`.

Maybe you can try the following to install it manually ( not tested ) : 

```
apt install python3-dev gcc
source /opt/ajenti/bin/activate
pip3 install psutil
```

Arnaud
