### ISSUE TITLE
Ajenti bug report 2.2.3

### ISSUE THREAD

**Issue by Mihaidev-cloud** [ajenti/ajenti#1422]
Ajenti bug report
--------------------

Info | Value
----- | -----
Ajenti | 2.2.3
Platform | linux / linux / Linux Mint 21.1
Architecture | x86_64
Python | 3.10.6
Debug | True
Loaded plugins | 

Library | Version
------- | -------
gevent | 21.12.0
greenlet | 21.12.0
psutil | 5.9.0

    Traceback (most recent call last):
      File "/home/mihaidev-cloud/Desktop/ajenti/ajenti-panel/aj/entry.py", line 39, in start
        aj.core.run(dev_mode=dev_mode, **kwargs)
      File "/home/mihaidev-cloud/Desktop/ajenti/ajenti-panel/aj/core.py", line 109, in run
        aj.config.ensure_structure()
      File "/home/mihaidev-cloud/Desktop/ajenti/ajenti-panel/aj/config.py", line 79, in ensure_structure
        self.migrate_users_to_own_configfile()
      File "/home/mihaidev-cloud/Desktop/ajenti/ajenti-panel/aj/config.py", line 89, in migrate_users_to_own_configfile
        with open(users_path, 'w') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/etc/ajenti/users.yml'

**Comment by kiarn** [comment]
Hello @Mihaidev-cloud 

It seems you are trying to use `Ajenti` without install. In this case, it's necessary to create the config files manually (as root):

```
mkdir /etc/ajenti
touch /etc/ajenti/users.yml
touch /etc/ajenti/smtp.yml
touch /etc/ajenti/tfa.yml
chmod 600  /etc/ajenti/users.yml /etc/ajenti/smtp.yml /etc/ajenti/tfa.yml
```

Should solve the issue.

Arnaud

**Comment by Mihaidev-cloud** [comment]
Yea it fixed , but now I get this error

Ajenti bug report
--------------------


Info | Value
----- | -----
Ajenti | 2.2.3
Platform | linux / linux / Linux Mint 21.1
Architecture | x86_64
Python | 3.10.6
Debug | True
Loaded plugins | 

Library | Version
------- | -------
gevent | 21.12.0
greenlet | 21.12.0
psutil | 5.9.0


    Traceback (most recent call last):
      File "/home/mihaidev-cloud/Desktop/ajenti/ajenti-panel/aj/entry.py", line 39, in start
        aj.core.run(dev_mode=dev_mode, **kwargs)
      File "/home/mihaidev-cloud/Desktop/ajenti/ajenti-panel/aj/core.py", line 117, in run
        aj.smtp_config.load()
      File "/home/mihaidev-cloud/Desktop/ajenti/ajenti-panel/aj/config.py", line 148, in load
        self.data['smtp']['password'] = ''
    TypeError: 'NoneType' object is not subscriptable

**Comment by kiarn** [comment]
Oh, it seems I was testing the config file too early, it's now corrected.
Just remove `/etc/ajenti/smtp.yml` and it will work.
