### ISSUE TITLE
Network plugin issue - KeyError: 'ethernets'

### ISSUE THREAD

**Issue by leni8ec** [ajenti/ajenti#1423]
I get this error when try to open `System -> Network` tab

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aj/api/endpoint.py", line 75, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ajenti_plugin_network/views.py", line 32, in handle_api_config_get
    return self.manager.get_config()
  File "/usr/local/lib/python3.10/dist-packages/ajenti_plugin_network/managers/ubuntu_manager.py", line 49, in get_config
    config = yaml.load(open(path), Loader=yaml.SafeLoader)['network']['ethernets']
KeyError: 'ethernets'
```

![image](https://user-images.githubusercontent.com/2379473/213353024-45511095-1d14-4c64-808f-68f665afe72c.png)

My `/etc/netplan/00-installer-config.yaml`
![image](https://user-images.githubusercontent.com/2379473/213354082-e5f71fd2-3273-4e90-9d25-8a61fea0e5f0.png)

---
Ubuntu 22.04.1 LTS
Ajenti install via [Automatic Installation](https://docs.ajenti.org/en/latest/man/install.html#automatic-installation)

**Comment by kiarn** [comment]
Hello @leni8ec 

Thanks for the usefull report !
I don't see a problem here. Do you have any other YAML file in /etc/netplan ?
I will make some further tests.

Arnaud
