### ISSUE TITLE
'Service' object has no attribute 'enabled' for System V

### ISSUE THREAD

**Issue by acsvln** [ajenti/ajenti#1426]
I have installed Ajenti 2 on clean CentOS-7 system. 
I have both `systemd` and `System V` menus in Serivces.
When i try to select `System V` i got

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aj/api/endpoint.py", line 75, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ajenti_plugin_services/views.py", line 71, in handle_api_list
    return [self.__service_to_json(svc) for svc in self.managers[manager_id].list()]
  File "/usr/local/lib/python3.6/site-packages/ajenti_plugin_services/views.py", line 71, in <listcomp>
    return [self.__service_to_json(svc) for svc in self.managers[manager_id].list()]
  File "/usr/local/lib/python3.6/site-packages/ajenti_plugin_services/views.py", line 34, in __service_to_json
    'enabled': svc.enabled,
AttributeError: 'Service' object has no attribute 'enabled'
```
Looks strange, my core is "Ajenti Core version 2.2.1".

**Comment by kiarn** [comment]
Hello @acsvln ,

Thanks for the report. I'm only testing in Rocky Linux 8, but I can confirm, and I will fix it.

Regards,

Arnaud
