### ISSUE TITLE
Ajenti 2 on Debian 11 fresh install

### ISSUE THREAD

**Issue by digimbyte** [ajenti/ajenti#1441]
Fresh install of Debian 11
installation order: 
setup admin super-user
Nginx
Certbot
Ajenti 2

CRASH:
```
Ajenti bug report
--------------------


Info | Value
----- | -----
Ajenti | 2.2.6
Platform | debian / debian / Debian GNU/Linux 11 (bullseye)
Architecture | x86_64
Python | 3.9.2
Debug | True
Loaded plugins |

Library | Version
------- | -------
gevent | 22.10.2
greenlet | 22.10.2
psutil | 5.9.5


    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/dist-packages/aj/entry.py", line 39, in start
        aj.core.run(dev_mode=dev_mode, **kwargs)
      File "/usr/local/lib/python3.9/dist-packages/aj/core.py", line 108, in run
        aj.config.load()
      File "/usr/local/bin/ajenti-panel", line 37, in load
        self.data = yaml.load(open(self.path), Loader=yaml.Loader)
    PermissionError: [Errno 13] Permission denied: '/etc/ajenti/config.yml'
```

When I run the website on direct port access, I can log in but the side bar seems to crash, 

Output from debug mode:
```
$ /usr/local/bin/ajenti-panel --dev
24.06.2023 17:01:33  [...    54886]  DEBUG    Registering [aj.api.http.HttpMiddleware] (interface)
24.06.2023 17:01:33  [...    54886]  DEBUG    Registering [aj.api.http.HttpMasterMiddleware] (interface)
24.06.2023 17:01:33  [...    54886]  DEBUG    Registering [aj.api.http.HttpPlugin] (interface)
24.06.2023 17:01:33  [...    54886]  DEBUG    Registering [aj.api.http.SocketEndpoint] (interface)
24.06.2023 17:01:33  [...    54886]  DEBUG    Registering [aj.security.verifier.ClientCertificateVerificator] (service)
24.06.2023 17:01:33  [...    54886]  DEBUG    Registering [aj.auth.AuthenticationMiddleware] (service)
24.06.2023 17:01:33  [...    54886]  DEBUG    Registering [aj.auth.AuthenticationProvider] (interface)
24.06.2023 17:01:33  [...    54886]  DEBUG    Registering [aj.auth.OSAuthenticationProvider] (implementation of [aj.auth.AuthenticationProvider])
24.06.2023 17:01:33  [...    54886]  DEBUG    Registering [aj.auth.AuthenticationService] (service)
24.06.2023 17:01:33  [...    54886]  DEBUG    Registering [aj.auth.PermissionProvider] (interface)
24.06.2023 17:01:33  [...    54886]  DEBUG    Registering [aj.security.pwreset.PasswordResetMiddleware] (implementation of [aj.api.http.HttpMasterMiddleware])
24.06.2023 17:01:34  [...    54886]  DEBUG    Registering [aj.routing.CentralDispatcher] (service)
24.06.2023 17:01:34  [...    54886]  DEBUG    Registering [aj.gate.middleware.GateMiddleware] (service)
24.06.2023 17:01:34  [...    54886]        compat.py:20    DEBUG    Popen: ('lsb_release', '-a')
24.06.2023 17:01:34  [...    54886]        compat.py:20    DEBUG    Popen: ('uname', '-rs')
24.06.2023 17:01:34  [...    54886]        compat.py:20    DEBUG    Popen: ['lsb_release', '-sd']
24.06.2023 17:01:34  [master 54886]          core.py:107   INFO   Loading config from /etc/ajenti/config.yml
24.06.2023 17:01:34  [master 54886]         entry.py:50    ERROR  Fatal crash occured
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aj/entry.py", line 39, in start
    aj.core.run(dev_mode=dev_mode, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/aj/core.py", line 108, in run
    aj.config.load()
  File "/usr/local/bin/ajenti-panel", line 37, in load
    self.data = yaml.load(open(self.path), Loader=yaml.Loader)
PermissionError: [Errno 13] Permission denied: '/etc/ajenti/config.yml'
24.06.2023 17:01:34  [master 54886]        compat.py:20    DEBUG  Popen: ['uname', '-m']
24.06.2023 17:01:34  [master 54886]         entry.py:63    ERROR  Crash report written to ./crash-2023-06-24-17h01.txt
24.06.2023 17:01:34  [master 54886]         entry.py:64    ERROR  Please submit it to https://github.com/ajenti/ajenti/issues/new
```
from the front end, these are seen in the log which is most likely related to the above:
![image](https://github.com/ajenti/ajenti/assets/6645396/6744daa7-32a7-4ad5-9c7c-13e7a6b0ab0b)

python3 -m pip list | grep aj
```
aj                        2.2.6
ajenti-panel              2.2.6
ajenti.plugin.ace         0.32
ajenti.plugin.core        0.106
ajenti.plugin.dashboard   0.42
ajenti.plugin.filemanager 0.31
ajenti.plugin.filesystem  0.50
ajenti.plugin.notepad     0.30
ajenti.plugin.packages    0.36
ajenti.plugin.passwd      0.26
ajenti.plugin.plugins     0.50
ajenti.plugin.services    0.35
ajenti.plugin.settings    0.34
ajenti.plugin.terminal    0.42
```
$ ls /usr/local/lib/python3.9/dist-packages/ajenti_plugin_core/resources/build -al
```
total 2268
drwxr-xr-x 2 root root      78 Jun 24 16:08 .
drwxr-xr-x 9 root root     103 Jun 24 16:08 ..
-rwxr-xr-x 1 root root  196822 Jun 24 16:08 all.css
-rwxr-xr-x 1 root root   66539 Jun 24 16:08 all.js
-rwxr-xr-x 1 root root   14580 Jun 24 16:08 all.vendor.css
-rwxr-xr-x 1 root root 2033455 Jun 24 16:08 all.vendor.js
```

**Comment by kiarn** [comment]
Hello @digimbyte 

Ajenti main process is intended to run as root, and if I understand you correctly, you are trying to run it as admin. The crash you are pointing is caused because admin may don't have the permission to read `/etc/ajenti/*`

Arnaud

**Comment by digimbyte** [comment]
from what I understand, the script is run and installed as root regardless.
`sudo bash -s -`
if running the curl command as root should be defined in the documentation.

Regardless, I followed the uninstall instructions and ran the install script again as root. 
and now the services fail to start:
```
 sudo systemctl start ajenti.service
Job for ajenti.service failed because the control process exited with error code.
See "systemctl status ajenti.service" and "journalctl -xe" for details.
root@6wu7kjoq:~# systemctl status ajenti.service
● ajenti.service - Ajenti panel
     Loaded: loaded (/lib/systemd/system/ajenti.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-06-27 05:58:30 CST; 38s ago
    Process: 1812 ExecStart=/usr/bin/python3 /usr/local/bin/ajenti-panel -d (code=exited, status=1/FAILURE)
        CPU: 98ms
```

**Comment by digimbyte** [comment]
found the issue maybe browser related, latest chrome and opera it did not work. Edge however, worked fine
