### ISSUE TITLE
elevate does not work on ubuntu 22.04

### ISSUE THREAD

**Issue by mohataj** [ajenti/ajenti#1445]
it shows a password field where i cannot enter anything and switches fast back to the dashboard

#ajenti.log

2023-08-05 03:40:56,005 INFO    : 192.168.178.71 - - [2023-08-05 03:40:56] "POST /api/dashboard/widgets-values HTTP/1.1" 200 390 0.005129
2023-08-05 03:40:57,005 INFO    : 192.168.178.71 - - [2023-08-05 03:40:57] "POST /api/dashboard/widgets-values HTTP/1.1" 200 390 0.005089
2023-08-05 03:40:58,004 INFO    : 192.168.178.71 - - [2023-08-05 03:40:58] "POST /api/dashboard/widgets-values HTTP/1.1" 200 388 0.005561
2023-08-05 03:40:59,001 INFO    : 192.168.178.71 - - [2023-08-05 03:40:59] "POST /api/dashboard/widgets-values HTTP/1.1" 200 389 0.005145
2023-08-05 03:40:59,637 INFO    : 192.168.178.71 - - [2023-08-05 03:40:59] "GET /view/login/sudo:mo//view/dashboard HTTP/1.1" 200 11191 0.005178
2023-08-05 03:40:59,889 INFO    : 192.168.178.71 - - [2023-08-05 03:40:59] "GET /resources/all.vendor.css HTTP/1.1" 200 6657 0.012216
2023-08-05 03:40:59,899 INFO    : 192.168.178.71 - - [2023-08-05 03:40:59] "GET /resources/all.css HTTP/1.1" 200 27456 0.019564
2023-08-05 03:41:00,224 INFO    : 192.168.178.71 - - [2023-08-05 03:41:00] "GET /resources/all.vendor.js HTTP/1.1" 200 652849 0.342710
2023-08-05 03:41:00,226 INFO    : 192.168.178.71 - - [2023-08-05 03:41:00] "GET /resources/core/resources/vendor/pt-sans/styles/pt_sans.css HTTP/1.1" 304 137 0.342716
2023-08-05 03:41:00,228 INFO    : 192.168.178.71 - - [2023-08-05 03:41:00] "GET /resources/core/resources/vendor/fontawesome/css/v4-shims.css HTTP/1.1" 304 137 0.342183
2023-08-05 03:41:00,229 INFO    : 192.168.178.71 - - [2023-08-05 03:41:00] "GET /resources/core/resources/vendor/fontawesome/css/all.min.css HTTP/1.1" 304 137 0.342634
2023-08-05 03:41:00,231 INFO    : 192.168.178.71 - - [2023-08-05 03:41:00] "GET /resources/all.init.js HTTP/1.1" 200 412 0.126387
2023-08-05 03:41:00,237 INFO    : 192.168.178.71 - - [2023-08-05 03:41:00] "GET /resources/all.js HTTP/1.1" 200 30251 0.092046
2023-08-05 03:41:00,456 INFO    : 192.168.178.71 - - [2023-08-05 03:41:00] "GET /resources/all.partials.js HTTP/1.1" 200 14292 0.012206
2023-08-05 03:41:00,806 INFO    : 192.168.178.71 - - [2023-08-05 03:41:00] "GET /api/core/identity HTTP/1.1" 200 329 0.016790
2023-08-05 03:41:00,812 INFO    : 192.168.178.71 - - [2023-08-05 03:41:00] "GET /socket.io/?EIO=4&transport=polling&t=Od3oB_s HTTP/1.1" 200 214 0.002427
2023-08-05 03:41:00,818 INFO    : 192.168.178.71 - - [2023-08-05 03:41:00] "GET /api/core/sidebar HTTP/1.1" 200 2116 0.025362
2023-08-05 03:41:00,819 INFO    : 192.168.178.71 - - [2023-08-05 03:41:00] "GET /api/core/session-time HTTP/1.1" 200 156 0.024634
2023-08-05 03:41:00,820 INFO    : 192.168.178.71 - - [2023-08-05 03:41:00] "GET /resources/all.locale.js?lang=en HTTP/1.1" 200 222 0.023059
2023-08-05 03:41:00,836 INFO    : 192.168.178.71 - - [2023-08-05 03:41:00] "GET /api/core/sidebar HTTP/1.1" 200 2116 0.008367
2023-08-05 03:41:01,032 INFO    : 192.168.178.71 - - [2023-08-05 03:41:01] "GET /api/core/identity HTTP/1.1" 200 329 0.004180
2023-08-05 03:41:01,053 INFO    : 192.168.178.71 - - [2023-08-05 03:41:01] "GET /api/core/session-time HTTP/1.1" 200 156 0.015746
2023-08-05 03:41:01,061 INFO    : 192.168.178.71 - - [2023-08-05 03:41:01] "GET / HTTP/1.1" 302 143 0.003212
2023-08-05 03:41:01,289 INFO    : 192.168.178.71 - - [2023-08-05 03:41:01] "GET /view/ HTTP/1.1" 200 11191 0.005124
2023-08-05 03:41:01,538 INFO    : 192.168.178.71 - - [2023-08-05 03:41:01] "GET /resources/all.vendor.css HTTP/1.1" 200 6657 0.013272
2023-08-05 03:41:01,547 INFO    : 192.168.178.71 - - [2023-08-05 03:41:01] "GET /resources/all.css HTTP/1.1" 200 27456 0.020012
2023-08-05 03:41:01,554 INFO    : 192.168.178.71 - - [2023-08-05 03:41:01] "GET /resources/all.partials.js HTTP/1.1" 200 14292 0.024638
2023-08-05 03:41:01,569 INFO    : 192.168.178.71 - - [2023-08-05 03:41:01] "GET /resources/all.js HTTP/1.1" 200 30251 0.037616
2023-08-05 03:41:01,572 INFO    : 192.168.178.71 - - [2023-08-05 03:41:01] "GET /resources/all.init.js HTTP/1.1" 200 412 0.039288
2023-08-05 03:41:01,859 INFO    : 192.168.178.71 - - [2023-08-05 03:41:01] "GET /resources/all.vendor.js HTTP/1.1" 200 652849 0.324842
2023-08-05 03:41:02,250 INFO    : 192.168.178.71 - - [2023-08-05 03:41:02] "GET /api/core/identity HTTP/1.1" 200 329 0.003868
2023-08-05 03:41:02,256 INFO    : 192.168.178.71 - - [2023-08-05 03:41:02] "GET /socket.io/?EIO=4&transport=polling&t=Od3oCMa HTTP/1.1" 200 214 0.000890
2023-08-05 03:41:02,262 INFO    : 192.168.178.71 - - [2023-08-05 03:41:02] "GET /api/core/sidebar HTTP/1.1" 200 2116 0.010776
2023-08-05 03:41:02,265 INFO    : 192.168.178.71 - - [2023-08-05 03:41:02] "GET /resources/all.locale.js?lang=en HTTP/1.1" 200 222 0.007103
2023-08-05 03:41:02,270 INFO    : 192.168.178.71 - - [2023-08-05 03:41:02] "GET /api/core/session-time HTTP/1.1" 200 156 0.017014
2023-08-05 03:41:02,275 INFO    : 192.168.178.71 - - [2023-08-05 03:41:02] "GET /api/core/sidebar HTTP/1.1" 200 2116 0.007752
2023-08-05 03:41:02,474 INFO    : 192.168.178.71 - - [2023-08-05 03:41:02] "GET /api/dashboard/widgets HTTP/1.1" 200 1402 0.004231
2023-08-05 03:41:02,479 INFO    : 192.168.178.71 - - [2023-08-05 03:41:02] "GET /api/core/user-config HTTP/1.1" 200 154 0.003276
2023-08-05 03:41:02,503 INFO    : 192.168.178.71 - - [2023-08-05 03:41:02] "GET /api/core/session-time HTTP/1.1" 200 156 0.014384
2023-08-05 03:41:02,595 INFO    : 192.168.178.71 - - [2023-08-05 03:41:02] "POST /socket.io/?EIO=4&transport=polling&t=Od3oCRt&sid=bgw7MLaBLQ2_ELfrAAAW HTTP/1.1" 200 103 0.002152
2023-08-05 03:41:02,598 INFO    : 192.168.178.71 - - [2023-08-05 03:41:02] "GET /socket.io/?EIO=4&transport=polling&t=Od3oCRv&sid=bgw7MLaBLQ2_ELfrAAAW HTTP/1.1" 200 157 0.005847
2023-08-05 03:41:02,730 INFO    : 192.168.178.71 - - [2023-08-05 03:41:02] "GET /api/core/session-time HTTP/1.1" 200 156 0.014336
2023-08-05 03:41:02,873 INFO    : 192.168.178.71 - - [2023-08-05 03:41:02] "GET /api/core/tasks/request-update HTTP/1.1" 200 156 0.006002
2023-08-05 03:41:02,874 INFO    : 192.168.178.71 - - [2023-08-05 03:41:02] "GET /socket.io/?EIO=4&transport=polling&t=Od3oCVg&sid=bgw7MLaBLQ2_ELfrAAAW HTTP/1.1" 200 222 0.004772
2023-08-05 03:41:03,108 INFO    : 192.168.178.71 - - [2023-08-05 03:41:03] "GET /socket.io/?EIO=4&transport=polling&t=Od3oCZ-&sid=bgw7MLaBLQ2_ELfrAAAW HTTP/1.1" 200 117 0.000532
2023-08-05 03:41:03,341 INFO    : 192.168.178.71 - - [2023-08-05 03:41:03] "GET /socket.io/?EIO=4&transport=polling&t=Od3oCdc&sid=bgw7MLaBLQ2_ELfrAAAW HTTP/1.1" 200 117 0.000442
2023-08-05 03:41:03,744 INFO    : 192.168.178.71 - - [2023-08-05 03:41:03] "POST /api/dashboard/widgets-values HTTP/1.1" 200 405 0.005144
2023-08-05 03:41:04,752 INFO    : 192.168.178.71 - - [2023-08-05 03:41:04] "POST /api/dashboard/widgets-values HTTP/1.1" 200 389 0.005811
2023-08-05 03:41:05,744 INFO    : 192.168.178.71 - - [2023-08-05 03:41:05] "POST /api/dashboard/widgets-values HTTP/1.1" 200 389 0.005289
2023-08-05 03:41:06,750 INFO    : 192.168.178.71 - - [2023-08-05 03:41:06] "POST /api/dashboard/widgets-values HTTP/1.1" 200 389 0.005512
2023-08-05 03:41:07,747 INFO    : 192.168.178.71 - - [2023-08-05 03:41:07] "POST /api/dashboard/widgets-values HTTP/1.1" 200 389 0.005085
2023-08-05 03:41:08,748 INFO    : 192.168.178.71 - - [2023-08-05 03:41:08] "POST /api/dashboard/widgets-values HTTP/1.1" 200 388 0.005107
2023-08-05 03:41:09,750 INFO    : 192.168.178.71 - - [2023-08-05 03:41:09] "POST /api/dashboard/widgets-values HTTP/1.1" 200 389 0.005032
2023-08-05 03:41:10,751 INFO    : 192.168.178.71 - - [2023-08-05 03:41:10] "POST /api/dashboard/widgets-values HTTP/1.1" 200 389 0.004874
2023-08-05 03:41:11,748 INFO    : 192.168.178.71 - - [2023-08-05 03:41:11] "POST /api/dashboard/widgets-values HTTP/1.1" 200 386 0.005111
2023-08-05 03:41:12,748 INFO    : 192.168.178.71 - - [2023-08-05 03:41:12] "POST /api/dashboard/widgets-values HTTP/1.1" 200 390 0.005091

**Comment by mohataj** [comment]
and plugins do not get installed from root login - success and reboot message is showing up but after login the new plugin stays uninstalled

#ajenti.log


2023-08-05 03:47:00,154 INFO    : 192.168.178.71 - - [2023-08-05 03:47:00] "POST /api/core/tasks/start HTTP/1.1" 200 221 0.020594
2023-08-05 03:47:00,158 INFO    : Starting task a7f9644bb9e8620a0a862e64cb3a068089a6a009cada3df2570f4deb10be2d2a (InstallPlugin)
2023-08-05 03:47:03,962 INFO    : Task a7f9644bb9e8620a0a862e64cb3a068089a6a009cada3df2570f4deb10be2d2a finished
2023-08-05 03:47:04,252 INFO    : 192.168.178.71 - - [2023-08-05 03:47:04] "GET /api/plugins/installed HTTP/1.1" 200 4554 0.028384
2023-08-05 03:47:06,230 INFO    : 192.168.178.71 - - [2023-08-05 03:47:06] "POST /api/plugins/core/check-upgrade HTTP/1.1" 200 161 2.009619
2023-08-05 03:47:06,528 INFO    : 192.168.178.71 - - [2023-08-05 03:47:06] "GET /api/plugins/pypi/installed HTTP/1.1" 200 692 2.306557

**Comment by mohataj** [comment]
plugins are present but not listed in installed

#ajenti.log2023-08-05 03:50:13,951 INFO    : Master PID - 3507
2023-08-05 03:50:13,951 INFO    : Detected platform: debian / Ubuntu 22.04.3 LTS
2023-08-05 03:50:13,951 INFO    : Python version: 3.10.12
2023-08-05 03:50:14,096 INFO    : Discovered 17 plugins
2023-08-05 03:50:14,227 ERROR   : [cron]: plugin import failed: No module named 'reconfigure.configs.ajenti'
2023-08-05 03:50:14,228 ERROR   : Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aj/plugins.py", line 341, in load_all_from
    self.__import_plugin_module(name, self[name])
  File "/usr/local/lib/python3.10/dist-packages/aj/plugins.py", line 367, in __import_plugin_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/ajenti_plugin_cron/__init__.py", line 3, in <module>
    from .views import Handler
  File "/usr/local/lib/python3.10/dist-packages/ajenti_plugin_cron/views.py", line 11, in <module>
    from .manager import CronManager
  File "/usr/local/lib/python3.10/dist-packages/ajenti_plugin_cron/manager.py", line 4, in <module>
    from reconfigure.configs import CrontabConfig
  File "/usr/local/lib/python3.10/dist-packages/reconfigure/configs/__init__.py", line 6, in <module>
    from reconfigure.configs.ajenti import AjentiConfig
ModuleNotFoundError: No module named 'reconfigure.configs.ajenti'

2023-08-05 03:50:14,272 ERROR   : [fstab]: plugin import failed: No module named 'reconfigure.configs.ajenti'
2023-08-05 03:50:14,273 ERROR   : Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aj/plugins.py", line 341, in load_all_from
    self.__import_plugin_module(name, self[name])
  File "/usr/local/lib/python3.10/dist-packages/aj/plugins.py", line 367, in __import_plugin_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/ajenti_plugin_fstab/__init__.py", line 3, in <module>
    from .views import Handler
  File "/usr/local/lib/python3.10/dist-packages/ajenti_plugin_fstab/views.py", line 11, in <module>
    from reconfigure.configs import FSTabConfig
  File "/usr/local/lib/python3.10/dist-packages/reconfigure/configs/__init__.py", line 6, in <module>
    from reconfigure.configs.ajenti import AjentiConfig
ModuleNotFoundError: No module named 'reconfigure.configs.ajenti'

2023-08-05 03:50:14,345 INFO    : Loaded 15 plugins
2023-08-05 03:50:14,345 INFO    : Binding to [0.0.0.0]:8000

**Comment by mohataj** [comment]
The URL https://192.168.178.101:8000/view/cron/ was not found on this server.

not working

**Comment by kiarn** [comment]
Hello @mohataj 

Thanks for the report, I can confirm the problem with elevate, I made a mistake by implementing the TFA verification. I will have a look at it.

Concerning the problem with the cron plugin, I think it's installed, but not showing up because a dependency is missing. I don't understand why, because the dependency is clearly written here : 

https://github.com/ajenti/ajenti/blob/master/plugins/cron/requirements.txt

So, in your case, running a:

```
pip3 install reconfigure
```

and then restarting `Ajenti` should help. But I will have a look at it too.

Regards,

Arnaud

**Comment by kiarn** [comment]
The first point with elevation is now solved on the git repository.

I simulated many installations under 22.04 today ( with and without virtualenv ), and was not able to reproduce the problem with the installation of the cron plugin. So I think I need more details about the way you installed `Ajenti`.

Arnaud

**Comment by CollectorKirk** [comment]
For those looking for a workaround to the Elevation issue, follow the steps below:

The following instructions assume the IP address of your server is "192.168.1.200", you are running Ajenti on the default port 8000, and the username with sudo privileges is "someuser"

  1. Navigate to https://192.168.1.200:8000/view/login/sudo:someuser (replace "someuser" with the username specific to your system) DO NOT CLICK AUTHENTICATE YET
  
  2. Open a new tab/window in the same browser and navigate to the main login page (i.e https://192.168.1.200:8000/view/login/normal)
  
  3. Enter your username and password, then click "Login"
  
  4. Go back to the other tab/window from Step 1, then click Authenticate
  
  5. Close the tab/window from Step 2 and continue working from the tab/window from Step 1.
