### ISSUE TITLE
ajenti error

### ISSUE THREAD

**Issue by CobbleCZC** [ajenti/ajenti#1446]
2023-08-16 23:17:42,232 INFO    : Process 3368 exiting normally
2023-08-16 23:17:42,876 INFO    : Loading config from /etc/ajenti/config.yml
2023-08-16 23:17:42,878 INFO    : Loading users from /etc/ajenti/users.yml
2023-08-16 23:17:42,879 INFO    : Loading smtp config from /etc/ajenti/smtp.yml
2023-08-16 23:17:42,879 ERROR   : Smtp credentials file "/etc/ajenti/smtp.yml" not found
2023-08-16 23:17:42,879 INFO    : Loading tfa config from /etc/ajenti/tfa.yml
2023-08-16 23:17:42,879 INFO    : Ajenti Core 2.2.6
2023-08-16 23:17:42,879 INFO    : Master PID - 3424
2023-08-16 23:17:42,879 INFO    : Detected platform: debian / Ubuntu 22.04.2 LTS
2023-08-16 23:17:42,879 INFO    : Python version: 3.10.12
2023-08-16 23:17:42,905 INFO    : Discovered 12 plugins
2023-08-16 23:17:42,941 INFO    : Loaded 12 plugins
2023-08-16 23:17:42,941 INFO    : Binding to [192.168.0.197]:8000
2023-08-16 23:17:42,951 INFO    : New worker "restricted session" PID 3431, EUID 0, EGID 0
2023-08-16 23:17:42,952 INFO    : Worker 3431 is demoting to UID 65534 / GID 65534...
2023-08-16 23:17:42,952 INFO    : ...done, new EUID 65534 EGID 65534

**Comment by kiarn** [comment]
This error should in fact only be a warning and should not annoy you. Without a smtp config, the only thing which will not work is the password reset functionality. It will not affect other plugins.

If it annoys you, just make a `touch /etc/ajenti/smtp.yml` as root.

Arnaud

**Comment by CobbleCZC** [comment]
kiarn, it doesnt annoy me, i dont even care it is there, but it wont start so i need someone to contact me and help me diagnose
use here or discord: benderblendersexofferer

**Comment by CobbleCZC** [comment]
a little update

Aug 18 12:00:49 acer systemd[1]: Starting Ajenti panel...
Aug 18 12:00:49 acer python3[2458]: Traceback (most recent call last):
Aug 18 12:00:49 acer python3[2458]:   File "/usr/local/bin/ajenti-panel", line 123, in <module>
Aug 18 12:00:49 acer python3[2458]:     if not os.path.exists(config_path):
Aug 18 12:00:49 acer python3[2458]:   File "/usr/lib/python3.10/genericpath.py", line 19, in exists
Aug 18 12:00:49 acer python3[2458]:     os.stat(path)
Aug 18 12:00:49 acer python3[2458]: TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Aug 18 12:00:49 acer systemd[1]: ajenti.service: Control process exited, code=exited, status=1/FAILURE
Aug 18 12:00:49 acer systemd[1]: ajenti.service: Failed with result 'exit-code'.
Aug 18 12:00:49 acer systemd[1]: Failed to start Ajenti panel.

**Comment by kiarn** [comment]
I think your install proces was ot complete because it seems the main config files which should be located at `/etc/ajenti` are missing. How did you install it ? On which system ?

The simplier way is to run the automatic script : https://docs.ajenti.org/en/latest/man/install.html
If you did so, please try to rerun and if provided, copy/paste the errors here, I will try to help.

Arnaud
