### ISSUE TITLE
Can't open PID file /var/run/ajenti.pid (yet?) after start-post: No such file or directory

### ISSUE THREAD

**Issue by ZGLinus** [ajenti/ajenti#1451]
I try to use ajenti in my arm64 server, but it's not working.
```
Starting Ajenti panel...
ajenti.service: Can't open PID file /var/run/ajenti.pid (yet?) after start-post: No such file or directory
ajenti.service: Failed with result 'protocol'.
Failed to start Ajenti panel.
```
But when I try to run ajenti in verbose debug mode, it works as it should, except for the plugins view.

**Comment by kiarn** [comment]
Hello,

The `systemd` service is only an utility to run a single command as daemon. Did you try to run this command manually ?

```
/usr/bin/python3 /usr/local/bin/ajenti-panel -d --stock-plugins --plugins /usr/lib/linuxmuster-webui/plugins
```

(in not venv installation)

You can maybe find some usefull errors in `/var/log/ajenti`

Arnaud

**Comment by ZGLinus** [comment]
Here is the ajenti log
```
2023-10-10 09:46:59,260 INFO    : Loading config from /etc/ajenti/config.yml
2023-10-10 09:46:59,287 INFO    : Loading users from /etc/ajenti/users.yml
2023-10-10 09:46:59,290 INFO    : Loading smtp config from /etc/ajenti/smtp.yml
2023-10-10 09:46:59,291 ERROR   : Smtp credentials file "/etc/ajenti/smtp.yml" not found
2023-10-10 09:46:59,292 INFO    : Loading tfa config from /etc/ajenti/tfa.yml
2023-10-10 09:46:59,292 INFO    : Ajenti Core 2.2.7
2023-10-10 09:46:59,293 INFO    : Master PID - 553
2023-10-10 09:46:59,293 INFO    : Detected platform: debian / Ubuntu 18.04.5 LTS
2023-10-10 09:46:59,293 INFO    : Python version: 3.7.11
2023-10-10 09:46:59,374 ERROR   : Fatal crash occured
2023-10-10 09:46:59,402 ERROR   : Crash report written to /var/log/ajenti/crash-2023-10-10-09h46.txt
2023-10-10 09:46:59,403 ERROR   : Please submit it to https://github.com/ajenti/ajenti/issues/new
```
Here is the `crash-2023-10-10-09h46.txt`
```
Ajenti bug report
--------------------


Info | Value
----- | -----
Ajenti | 2.2.7
Platform | debian / ubuntu / Ubuntu 18.04.5 LTS
Architecture | aarch64
Python | 3.7.11
Debug | False
Loaded plugins |

Library | Version
------- | -------
gevent | 22.10.2
greenlet | 22.10.2
psutil | 5.9.5


    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/aj/entry.py", line 29, in start
        aj.core.run(dev_mode=dev_mode, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/aj/core.py", line 145, in run
        PluginManager.get(aj.context).load_all_from(aj.plugin_providers)
      File "/usr/local/lib/python3.7/dist-packages/aj/plugins.py", line 270, in load_all_from
        found += provider.provide()
      File "/usr/local/lib/python3.7/dist-packages/aj/plugins.py", line 45, in provide
        for _dir in os.listdir(self.path):
    FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/linuxmuster-webui/plugins'
```

**Comment by kiarn** [comment]
Oh sorry, my bad, I gave you a wrong command with extra plugins !

That's the good one:

```
/usr/bin/python3 /usr/local/bin/ajenti-panel -d --stock-plugins
```

**Comment by ZGLinus** [comment]
Here is the ajenti log
```
2023-10-10 14:47:57,363 INFO    : Loading config from /etc/ajenti/config.yml
2023-10-10 14:47:57,385 INFO    : Loading users from /etc/ajenti/users.yml
2023-10-10 14:47:57,388 INFO    : Loading smtp config from /etc/ajenti/smtp.yml
2023-10-10 14:47:57,389 ERROR   : Smtp credentials file "/etc/ajenti/smtp.yml" not found
2023-10-10 14:47:57,390 INFO    : Loading tfa config from /etc/ajenti/tfa.yml
2023-10-10 14:47:57,390 INFO    : Ajenti Core 2.2.7
2023-10-10 14:47:57,391 INFO    : Master PID - 7723
2023-10-10 14:47:57,391 INFO    : Detected platform: debian / Ubuntu 18.04.5 LTS
2023-10-10 14:47:57,391 INFO    : Python version: 3.7.11
```
But after that, I found something interesting in systemctl
```
ajenti.service: Refusing to accept PID outside of service control group, acquired through unsafe symlink chain: /var/run/ajenti.pid
```
Maybe there are something wrong in the ajenti.service.

**Comment by ZGLinus** [comment]
I found something interesting again.
When I run the command with "sudo" in normal user, it did work. But when I run it in root, the command didn't work and there were nothing new in the ajenti log.

**Comment by kiarn** [comment]
Thanks for your description!
I think I will need to dive a little more in the systemd configuration in order to understand why the pidfile is a problem for some architectures.
