### ISSUE TITLE
[BUG] Error when Closing Handle in gipc.gipc: GIPCLocked Exception

### ISSUE THREAD

**Issue by Zxce3** [ajenti/ajenti#1452]
Ajenti bug report
--------------------

Info | Value
----- | -----
Ajenti | 2.2.3
Platform | debian / ubuntu / Ubuntu 22.04.3 LTS
Architecture | x86_64
Python | 3.10.12
Debug | False
Loaded plugins | ace, check_certificates, core, dashboard, filemanager, filesystem, notepad, packages, passwd, plugins, services, settings, terminal

Library | Version
------- | -------
gevent | 21.12.0
greenlet | 21.12.0
psutil | 5.9.4

    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/aj/entry.py", line 29, in start
        aj.core.run(dev_mode=dev_mode, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/aj/core.py", line 271, in run
      File "/usr/local/lib/python3.10/dist-packages/gevent/baseserver.py", line 400, in serve_forever
        self._stop_event.wait()
      File "src/gevent/event.py", line 163, in gevent._gevent_cevent.Event.wait
      File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
      File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
      File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
      File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
      File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
      File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
      File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
      File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
      File "/usr/local/lib/python3.10/dist-packages/gevent/hub.py", line 300, in handle
        self.handler(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.10/dist-packages/aj/core.py", line 265, in signal_handler
        except OSError:
      File "/usr/local/lib/python3.10/dist-packages/aj/core.py", line 254, in cleanup
        logging.info(f'Process {os.getpid()} exiting normally')
      File "/usr/local/lib/python3.10/dist-packages/aj/gate/middleware.py", line 103, in destroy
        for session in self.sessions.values():
      File "/usr/local/lib/python3.10/dist-packages/aj/gate/middleware.py", line 96, in vacuum
        """
      File "/usr/local/lib/python3.10/dist-packages/aj/gate/session.py", line 42, in destroy
        self.gate.stop()
      File "/usr/local/lib/python3.10/dist-packages/aj/gate/gate.py", line 74, in stop
        self.stream.destroy()
      File "/usr/local/lib/python3.10/dist-packages/aj/gate/stream.py", line 124, in destroy
        self.pipe.close()
      File "/usr/local/lib/python3.10/dist-packages/gipc/gipc.py", line 1153, in close
        self._reader.close()
      File "/usr/local/lib/python3.10/dist-packages/gipc/gipc.py", line 676, in close
        raise GIPCLocked(
    gipc.gipc.GIPCLocked: Can't close handle <_GIPCReader_c27468 fd: 25>: locked for I/O operation

**Comment by kiarn** [comment]
I think it's solved in the version 2.2.8. Feel free to reopen the issue if it's not the case !

**Comment by Zxce3** [comment]
> I think it's solved in the version 2.2.8. Feel free to reopen the issue if it's not the case !

i think yes! thanks for your hard work!!
