### ISSUE TITLE
crash-2024-01-01-20h39.txt

### ISSUE THREAD

**Issue by lescieur** [ajenti/ajenti#1462]
>> Actions Taken:
Installed couple of plugins, then restarted the panel manually.

Ajenti Crashed.

I have to # systemctl restart ajenti

>> System:

# uname -a
Linux venom 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

>>> Log/Crash

root@venom:/var/log/ajenti# ls -la
total 284
drw-r-----  2 root root   4096 Jan  1 20:39 .
drwxr-xr-x 13 root root   4096 Jan  1 19:56 ..
-rw-r-----  1 root root 267833 Jan  1 20:39 ajenti.log
-rw-rw-rw-  1 root root   1733 Jan  1 20:15 crash-2024-01-01-20h15.txt
-rw-rw-rw-  1 root root   1739 Jan  1 20:39 crash-2024-01-01-20h39.txt

---

>>> CRASH FILE

Ajenti bug report
--------------------

Info | Value
----- | -----
Ajenti | 2.2.7
Platform | debian / debian / Debian GNU/Linux 12 (bookworm)
Architecture | x86_64
Python | 3.11.2
Debug | False
Loaded plugins | ace, core, cron, dashboard, filemanager, filesystem, notepad, packages, passwd, plugins, services, settings, terminal

Library | Version
------- | -------
gevent | 22.10.2
greenlet | 22.10.2
psutil | 5.9.7

    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/dist-packages/aj/entry.py", line 29, in start
        aj.core.run(dev_mode=dev_mode, **kwargs)
      File "/usr/local/lib/python3.11/dist-packages/aj/core.py", line 283, in run
        cleanup()
      File "/usr/local/lib/python3.11/dist-packages/aj/core.py", line 258, in cleanup
        gateway.destroy()
      File "/usr/local/lib/python3.11/dist-packages/aj/gate/middleware.py", line 105, in destroy
        self.vacuum()
      File "/usr/local/lib/python3.11/dist-packages/aj/gate/middleware.py", line 98, in vacuum
        session.destroy()
      File "/usr/local/lib/python3.11/dist-packages/aj/gate/session.py", line 42, in destroy
        self.gate.stop()
      File "/usr/local/lib/python3.11/dist-packages/aj/gate/gate.py", line 74, in stop
        self.stream.destroy()
      File "/usr/local/lib/python3.11/dist-packages/aj/gate/stream.py", line 124, in destroy
        self.pipe.close()
      File "/usr/local/lib/python3.11/dist-packages/gipc/gipc.py", line 1153, in close
        self._reader.close()
      File "/usr/local/lib/python3.11/dist-packages/gipc/gipc.py", line 676, in close
        raise GIPCLocked(
    gipc.gipc.GIPCLocked: Can't close handle <_GIPCReader_033b57 fd: 24>: locked for I/O operation.

---

>>> Logs:

2024-01-01 20:37:11,114 INFO    : 10.0.9.1 - - [2024-01-01 20:37:11] "GET /api/plugins/pypi/installed HTTP/1.1" 200 772 14.277756
2024-01-01 20:37:32,062 INFO    : 10.0.9.1 - - [2024-01-01 20:37:32] "GET /api/plugins/pypi/ajenti-plugins HTTP/1.1" 200 9168 34.685508
2024-01-01 20:37:50,710 INFO    : 10.0.9.1 - - [2024-01-01 20:37:50] "POST /api/core/tasks/start HTTP/1.1" 200 221 0.042977
2024-01-01 20:37:50,721 INFO    : Starting task 9ea2d6d6891b3c85564952a0e726b37468f2504d7f03d7e8df10e48c83dac895 (InstallPlugin)
2024-01-01 20:38:05,564 INFO    : Task 9ea2d6d6891b3c85564952a0e726b37468f2504d7f03d7e8df10e48c83dac895 finished
2024-01-01 20:38:05,894 INFO    : 10.0.9.1 - - [2024-01-01 20:38:05] "GET /api/plugins/installed HTTP/1.1" 200 4550 0.008931
2024-01-01 20:38:07,275 INFO    : 10.0.9.1 - - [2024-01-01 20:38:07] "POST /api/plugins/core/check-upgrade HTTP/1.1" 200 161 1.384262
2024-01-01 20:38:20,192 INFO    : 10.0.9.1 - - [2024-01-01 20:38:20] "GET /api/plugins/pypi/installed HTTP/1.1" 200 804 14.304548
2024-01-01 20:38:41,047 INFO    : 10.0.9.1 - - [2024-01-01 20:38:41] "GET /api/plugins/pypi/ajenti-plugins HTTP/1.1" 200 9168 34.832857
2024-01-01 20:39:09,584 INFO    : 10.0.9.1 - - [2024-01-01 20:39:09] "POST /api/core/restart-master HTTP/1.1" 200 158 0.006212
2024-01-01 20:39:09,585 WARNING : Restarting by request
2024-01-01 20:39:09,586 INFO    : Process 238120 exiting normally
2024-01-01 20:39:09,714 ERROR   : Child process 238230 did not stop after SIGKILL!
2024-01-01 20:39:09,716 ERROR   : Fatal crash occured
2024-01-01 20:39:09,784 ERROR   : Crash report written to /var/log/ajenti/crash-2024-01-01-20h39.txt
2024-01-01 20:39:09,785 ERROR   : Please submit it to https://github.com/ajenti/ajenti/issues/new
2024-01-01 20:39:14,890 ERROR   : disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/engineio/server.py", line 621, in _trigger_event
    return self.handlers[event](*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/socketio/server.py", line 809, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.11/dist-packages/socketio/server.py", line 711, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.11/dist-packages/socketio/server.py", line 767, in _trigger_event
    return self.namespace_handlers[namespace].trigger_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/socketio/namespace.py", line 18, in trigger_event
    return getattr(self, handler_name)(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aj/gate/middleware.py", line 60, in on_disconnect
    self._send_worker_event(sid, 'disconnect')
  File "/usr/local/lib/python3.11/dist-packages/aj/gate/middleware.py", line 43, in _send_worker_event
    gate.stream.send({
  File "/usr/local/lib/python3.11/dist-packages/aj/gate/stream.py", line 78, in send
    self.pipe.put(part)
  File "/usr/local/lib/python3.11/dist-packages/gipc/gipc.py", line 1058, in put
    self._validate()
  File "/usr/local/lib/python3.11/dist-packages/gipc/gipc.py", line 702, in _validate
    raise GIPCClosed(
gipc.gipc.GIPCClosed: GIPCHandle has been closed before.
2024-01-01 20:39:14,915 INFO    : 10.0.9.1 - - [2024-01-01 20:39:14] "GET /view/plugins HTTP/1.1" 200 11184 0.009999
2024-01-01 20:39:14,939 INFO    : 10.0.9.1 - - [2024-01-01 20:39:14] "GET /resources/all.vendor.css HTTP/1.1" 200 6664 0.008493
2024-01-01 20:39:14,966 INFO    : 10.0.9.1 - - [2024-01-01 20:39:14] "GET /resources/all.css HTTP/1.1" 200 27479 0.032418
2024-01-01 20:39:15,669 INFO    : 10.0.9.1 - - [2024-01-01 20:39:15] "GET /resources/all.init.js HTTP/1.1" 200 417 0.425063
2024-01-01 20:39:15,676 INFO    : 10.0.9.1 - - [2024-01-01 20:39:15] "GET /resources/all.js HTTP/1.1" 200 30243 0.380284
2024-01-01 20:39:16,012 INFO    : 10.0.9.1 - - [2024-01-01 20:39:16] "GET /resources/all.partials.js HTTP/1.1" 200 14456 0.017477
2024-01-01 20:39:16,895 INFO    : 10.0.9.1 - - [2024-01-01 20:39:16] "GET /resources/all.vendor.js HTTP/1.1" 200 652856 1.723947

**Comment by kiarn** [comment]
Hello @lescieur 

Thanks for the report, this should be already solved in `Ajenti` 2.2.8, it will soon be published.

Regards

Arnaud
