### ISSUE TITLE
Error upgrading from 2.2.7 to 2.2.9

### ISSUE THREAD

**Issue by anonhostpi** [ajenti/ajenti#1469]
![image](https://github.com/ajenti/ajenti/assets/130698314/6b25d024-79cb-4c83-9f87-3882c97efc78)

When running `/opt/ajenti/bin/ajenti-upgrade` from the venv (Ubuntu Server 23.10+Python3.11.6 with a venv install), you get this error message:

```log
INFO: pip is looking at multiple versions of gevent to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install aj and aj==2.2.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    aj 2.2.9 depends on greenlet==2.0.2
    gevent 23.9.1 depends on greenlet>=3.0rc3; platform_python_implementation == "CPython" and python_version >= "3.11"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
Traceback (most recent call last):
  File "/opt/ajenti/bin/ajenti-upgrade", line 41, in <module>
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', f'{package}=={version}'])
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/ajenti/bin/python3', '-m', 'pip', 'install', 'aj==2.2.9']' returned non-zero exit status 1.
```

Which I'm assuming is caused by this requirements.txt file excerpt:

https://github.com/ajenti/ajenti/blob/54c6712cf7e4b943d7353bd90ecc331844a48fb5/ajenti-core/requirements.txt#L7-L8

**Comment by kiarn** [comment]
Thanks for the report, I forgot the breaking changes in `greenlet` for Python above 3.11.
This is fixed in the last `requirements.txt`, and a new version is on the way.
