### ISSUE TITLE
ajenti crash report 

### ISSUE THREAD

**Issue by cweikl** [ajenti/ajenti#1476]
Please see description of the error: https://ask.linuxmuster.net/t/webui-7-2-7-2-27-testing-installation-der-pakete-kann-nicht-erfolgreich-abgeschlossen-werden/10642/46

Content of crash-2024-05-04-11h56.txt

Ajenti bug report
--------------------

Info | Value
----- | -----
Ajenti | 2.2.10
Platform | debian / ubuntu / Ubuntu 22.04.4 LTS
Architecture | x86_64
Python | 3.10.12
Debug | True
Loaded plugins | 

Library | Version
------- | -------
gevent | 23.9.1
greenlet | 23.9.1
psutil | 5.9.6

    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/aj/entry.py", line 39, in start
        aj.core.run(dev_mode=dev_mode, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/aj/core.py", line 145, in run
        PluginManager.get(aj.context).load_all_from(aj.plugin_providers)
      File "/usr/local/lib/python3.10/dist-packages/aj/plugins.py", line 270, in load_all_from
        found += provider.provide()
      File "/usr/local/lib/python3.10/dist-packages/aj/plugins.py", line 45, in provide
        for _dir in os.listdir(self.path):
    FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/linuxmuster/webui/plugins'

**Comment by kiarn** [comment]
Thanks, but it's not related to Ajenti and yet solved ;)
