### ISSUE TITLE
Authentication provider user is unavailable

### ISSUE THREAD

**Issue by alirezaalavi87** [ajenti/ajenti#1488]
Hi, 

## Setup
- Debian12
- installed ajenti via the venv installation script, then activated the venv and installed all plugins:
```
pip3 install ajenti-panel ajenti.plugin.ace ajenti.plugin.augeas ajenti.plugin.auth-users ajenti.plugin.core ajenti.plugin.dashboard ajenti.plugin.datetime ajenti.plugin.filemanager ajenti.plugin.filesystem ajenti.plugin.network ajenti.plugin.notepad ajenti.plugin.packages ajenti.plugin.passwd ajenti.plugin.plugins ajenti.plugin.power ajenti.plugin.services ajenti.plugin.settings ajenti.plugin.terminal
```

## config.yml
```yaml
auth:
  allow_sudo: true
  emails: {}
  provider: users
  users_file: /etc/ajenti/users.yml
bind:
  host: 0.0.0.0
  mode: tcp
  port: 8000
color: default
max_sessions: 3
trusted_domains: []
trusted_proxies: []
session_max_time: 3600
name: vps-ir
ssl:
  certificate:
  fqdn_certificate:
  force: false
  client_auth:
    certificates: []
    enable: false
    force: false
  enable: false
```

## Problem

when I run ajenti `sudo /opt/ajenti/bin/ajenti-panel -v` I get this error:

```
Traceback (most recent call last):
  File "/opt/ajenti/lib/python3.11/site-packages/aj/entry.py", line 39, in start
    aj.core.run(dev_mode=dev_mode, **kwargs)
  File "/opt/ajenti/lib/python3.11/site-packages/aj/core.py", line 182, in run
    middleware_stack = HttpMasterMiddleware.all(aj.context) + [gateway]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ajenti/lib/python3.11/site-packages/jadi/jadi.py", line 122, in _all
    return list(context.get_components(cls, ignore_exceptions=ignore_exceptions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ajenti/lib/python3.11/site-packages/jadi/jadi.py", line 38, in get_components
    instance = self.get_component(comp)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ajenti/lib/python3.11/site-packages/jadi/jadi.py", line 32, in get_component
    self.component_instances[fqdn] = cls(self)
                                     ^^^^^^^^^
  File "/opt/ajenti/lib/python3.11/site-packages/aj/security/pwreset.py", line 21, in __init__
    self.auth_provider = AuthenticationService.get(self.context).get_provider()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ajenti/lib/python3.11/site-packages/aj/auth.py", line 189, in get_provider
    raise AuthenticationError(f'Authentication provider {provider_id} is unavailable')
aj.auth.AuthenticationError: Authentication provider users is unavailable
```

and even though I don't like exposing my server's users to the internet, even with this config
```yaml
auth:
  allow_sudo: true
  emails: {}
  provider: os
  users_file: os
```

I get 403 error with my server users.

**Comment by kiarn** [comment]
Hello @alirezaalavi87 

Since you've installed `Ajenti` in a virtual env (good point !), you can only start `Ajenti` when the virtual env first activated is, or simply:

```
/opt/ajenti/bin/python3 /opt/ajenti/bin/ajenti-panel -v
```

Maybe you can get this a way a more specific which could help to understand the problem.
There's also the log file `/var/log/ajenti/ajenti.log` which could contain some useful informations.

**Comment by alirezaalavi87** [comment]
@kiarn 
the venv is activated by
`source /opt/ajenti/bin/activate`
and then I run it with `sudo /opt/ajenti/ajenti-panel -v`

the errors I posted is all it prints and the same thing in crash report.

this is also the last lines of `ajenti.log`:

```
2024-09-17 17:57:09,346 DEBUG   : Initializing plugin "filemanager"
2024-09-17 17:57:09,346 INFO    : Loaded 12 plugins
2024-09-17 17:57:09,347 INFO    : Binding to [0.0.0.0]:8000
2024-09-17 17:57:09,348 DEBUG   : Invoke target `<bound method WorkerGate._target of <aj.gate.gate.WorkerGate object at 0x7fd4f8b66b90>>` in child process.
2024-09-17 17:57:09,352 DEBUG   : SIGCHLD watcher for 990305 started.
2024-09-17 17:57:09,355 DEBUG   : _child start. target: `<bound method WorkerGate._target of <aj.gate.gate.WorkerGate object at 0x7fd4f8b66b90>>`
2024-09-17 17:57:09,354 DEBUG   : Invalidate <_GIPCWriter_76e9ec fd: 8> in parent.
2024-09-17 17:57:09,355 DEBUG   : Invalidating <_GIPCWriter_76e9ec fd: 8> ...
2024-09-17 17:57:09,356 DEBUG   : Delete current hub's threadpool.
2024-09-17 17:57:09,356 DEBUG   : Destroy hub and default loop.
2024-09-17 17:57:09,355 DEBUG   : Invalidate <_GIPCReader_5f8efe fd: 9> in parent.
2024-09-17 17:57:09,357 DEBUG   : Invalidating <_GIPCReader_5f8efe fd: 9> ...
2024-09-17 17:57:09,357 DEBUG   : Started child process 990305
2024-09-17 17:57:09,357 DEBUG   : Created new hub and event loop.
2024-09-17 17:57:09,358 DEBUG   : Invalidate <_GIPCReader_30dbe9 fd: 7> in child.
2024-09-17 17:57:09,359 DEBUG   : Legitimate <_GIPCReader_30dbe9 fd: 7> for current process.
2024-09-17 17:57:09,359 ERROR   : Fatal crash occured
2024-09-17 17:57:09,359 DEBUG   : Invalidating <_GIPCReader_30dbe9 fd: 7> ...                            2024-09-17 17:57:09,359 DEBUG   : Invalidate <_GIPCWriter_c52f1d fd: 10> in child.
2024-09-17 17:57:09,359 DEBUG   : Legitimate <_GIPCWriter_c52f1d fd: 10> for current process.
2024-09-17 17:57:09,359 DEBUG   : Invalidating <_GIPCWriter_c52f1d fd: 10> ...                           2024-09-17 17:57:09,360 DEBUG   : Legitimate <_GIPCWriter_76e9ec fd: 8> for current process.
2024-09-17 17:57:09,360 DEBUG   : Handle `<_GIPCWriter_76e9ec fd: 8>` is now valid in child.
2024-09-17 17:57:09,360 DEBUG   : Legitimate <_GIPCReader_5f8efe fd: 9> for current process.             2024-09-17 17:57:09,360 DEBUG   : Handle `<_GIPCReader_5f8efe fd: 9>` is now valid in child.
2024-09-17 17:57:09,367 DEBUG   : Popen: ['uname', '-m']                                                 2024-09-17 17:57:09,375 INFO    : New worker "restricted session" PID 990305, EUID 0, EGID 0
2024-09-17 17:57:09,376 INFO    : Worker 990305 is demoting to UID 65534 / GID 65534...
2024-09-17 17:57:09,377 INFO    : ...done, new EUID 65534 EGID 65534                                     2024-09-17 17:57:09,380 ERROR   : Crash report written to /var/log/ajenti/crash-2024-09-17-17h57.txt
```

**Comment by Manthan172005** [comment]
Km t nko.

**Comment by kiarn** [comment]
The problem here is, that you are activating the virtualenv as the current user. Using sudo will not use the same python path. You can easily check this:

```
source /opt/ajenti/bin/activate
which python3 # should give /opt/ajenti/bin/python3
sudo which python3 # should give /usr/bin/python3 --> not the Ajenti env.
```

The easiest way to start `Ajenti` is as root, with venv activated.

**Comment by alirezaalavi87** [comment]
Sorry for the late response,
well what do I have to do?
the automatic install script isn't working and it's doing the same thing. it creates a venv in /opt/ajenti
https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install-venv.sh

if I do this:
```
source /opt/ajenti/bin/activate
python /opt/ajenti/bin/ajenti-panel
```
I get this error:
```
  File "/opt/ajenti/./bin/ajenti-panel", line 127, in <module>
    aj.entry.start(
  File "/opt/ajenti/lib/python3.11/site-packages/aj/entry.py", line 35, in start
    aj.log.init_log_directory()
  File "/opt/ajenti/lib/python3.11/site-packages/aj/log.py", line 109, in init_log_directory
    os.chmod(LOG_DIR, 0o640)
PermissionError: [Errno 1] Operation not permitted: '/var/log/ajenti'
```

so now I have tried:
1. 
```
source /opt/ajenti/bin/activate
sudo python /opt/ajenti/bin/ajenti-panel
```
2. 
```
source /opt/ajenti/bin/activate
python /opt/ajenti/bin/ajenti-panel
```
and both face errors.

What steps should I take?

**Comment by kiarn** [comment]
Hi @alirezaalavi87 

It's not possible to start `Ajenti` as a normal user, you should start it as root user:

```
# To become root user
sudo -i
source /opt/ajenti/bin/activate
python /opt/ajenti/bin/ajenti-panel
```

**Comment by alirezaalavi87** [comment]
Thank you. But I still get the `Authentication provider users is unavailable` error.

**Comment by kiarn** [comment]
Ok, I don't get it. Maybe is there another error occuring before this one ? It could be an useful hint for me to understand what is going on.

**Comment by alirezaalavi87** [comment]
Here is the full error log:
https://pastefy.app/Dk3bXMkV

**Comment by kiarn** [comment]
Are you really sure that the users plugin is installed in the venv ? I don't find another explanation.

Can you please try the following:

```
sudo -i
source /opt/ajenti/bin/activate
pip3 list | grep ajenti
```

and see if the plugin `ajenti.plugin.auth-users`. In your first post, if you have installed it via sudo, it's possible that you have installed it outside the venv.

**Comment by alirezaalavi87** [comment]
Thank you with the steps you described I understood what the problem was. most of the plugins were installed by users was not installed. I think it ran into a network error or something during install.

Now ajenti starts.

**Comment by kiarn** [comment]
Great, thanks for your feedback !
