### ISSUE TITLE
No install method works...

### ISSUE THREAD

**Issue by rdnckreaper** [ajenti/ajenti#1489]
I have attempted this on an Ubuntu 24.04 VM and a Linux Mint 22.1 (Ubuntu 22.04). No matter what I do I can never get past initiating an 'automated' install or the manual install. I get the same error types on the very first package which is the ajenti-panel.

:: Setting up virtual env in /opt

:: Upgrading PIP

rm: cannot remove '/usr/lib//opt/ajenti/bin/python3/dist-packages/setuptools.egg-info': No such file or directory
Requirement already satisfied: pip in /opt/ajenti/lib/python3.10/site-packages (24.2)
Requirement already satisfied: wheel in /usr/local/lib/python3.10/dist-packages (0.44.0)
Requirement already satisfied: setuptools in /opt/ajenti/lib/python3.10/site-packages (75.1.0)
WARNING: Skipping gevent-socketio as it is not installed.
WARNING: Skipping gevent-socketio-hartwork as it is not installed.

:: Installing Ajenti

Collecting ajenti-panel
  Using cached ajenti-panel-2.2.10.tar.gz (61 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-pc0dt62o/ajenti_panel.egg-info
      writing /tmp/pip-pip-egg-info-pc0dt62o/ajenti_panel.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-pc0dt62o/ajenti_panel.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-pc0dt62o/ajenti_panel.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-pc0dt62o/ajenti_panel.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-pc0dt62o/ajenti_panel.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-pip-egg-info-pc0dt62o/ajenti_panel.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-dbgve861/ajenti-panel_dd8cb7bd87be4f79a270e3760f7cc0d1/setup.py", line 59, in <module>
          setup(
        File "/opt/ajenti/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/opt/ajenti/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/opt/ajenti/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/opt/ajenti/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/opt/ajenti/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/opt/ajenti/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/opt/ajenti/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 311, in run
          self.find_sources()
        File "/opt/ajenti/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 319, in find_sources
          mm.run()
        File "/opt/ajenti/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 545, in run
          self.prune_file_list()
        File "/opt/ajenti/lib/python3.10/site-packages/setuptools/command/sdist.py", line 161, in prune_file_list
          super().prune_file_list()
        File "/opt/ajenti/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 380, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "/opt/ajenti/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 267, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/opt/ajenti/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by kiarn** [comment]
Hi @rdnckreaper 

It's probably due to the missing `packaging` packet: https://github.com/ajenti/ajenti/pull/1484
I've merged this in order to update the install script.

Can you please try again ?

Thanks !

**Comment by rdnckreaper** [comment]
Hey @kiarn 
I decided to go with the automated and it appears to be moving right along now. I believe it has installed.

Thank you so much. I am in the UI now. Excited to test this out.
