### ISSUE TITLE
can't elevate user with auth-users plugin: (Permission denied: '/nonexistent' )

### ISSUE THREAD

**Issue by alirezaalavi87** [ajenti/ajenti#1492]
## Setup
os: debian 12
ajenti version: (couldn't find how to get the version)

## Problem

when using auth.provider: os , everything works fine. but with auth.provider: users, I can login with the user I have defined, but then when I try to elevate the user, I get this error:
```
Traceback (most recent call last):
  File "/opt/ajenti/lib/python3.11/site-packages/aj/api/endpoint.py", line 77, in wrapper
    result = fx(self, context, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ajenti/lib/python3.11/site-packages/ajenti_plugin_core/views/config.py", line 72, in handle_api_get_user_config
    return UserConfigService.get(self.context).get_provider().data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ajenti/lib/python3.11/site-packages/aj/config.py", line 331, in get_provider
    for provider in UserConfigProvider.all(self.context):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ajenti/lib/python3.11/site-packages/jadi/jadi.py", line 122, in _all
    return list(context.get_components(cls, ignore_exceptions=ignore_exceptions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ajenti/lib/python3.11/site-packages/jadi/jadi.py", line 38, in get_components
    instance = self.get_component(comp)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ajenti/lib/python3.11/site-packages/jadi/jadi.py", line 32, in get_component
    self.component_instances[fqdn] = cls(self)
                                     ^^^^^^^^^
  File "/opt/ajenti/lib/python3.11/site-packages/aj/config.py", line 346, in __init__
    os.makedirs(_dir)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/nonexistent'
```

## Config files

config.yml
```yml
auth:
  allow_sudo: true
  emails: {}
  provider: users
  users_file: /etc/ajenti/users.yml
bind:
  host: 0.0.0.0
  mode: tcp
  port: 8000
color: purple
email:
  enable: false
  templates: {}
language: en
logo: /opt/ajenti/lib/python3.11/site-packages/aj/static/images/Logo.png
max_sessions: 3
name: vps-ir
restricted_user: nobody
session_max_time: 3600
ssl:
  certificate: null
  client_auth:
    certificates: []
    enable: false
    force: false
  enable: false
  force: false
  fqdn_certificate: null
trusted_domains:
- https://test.com
trusted_proxies: []
view:
  filepath: content/pages/index.html
  plugin: core
```

users.yml
```yml
users:
  paneladmin:
    email: *******************
    fs_root: /home/paneladmin
    password: 123hash
    permissions:
      packages:install: true
      sidebar:view:/view/cron: true
    uid: 1000
```

**Comment by kiarn** [comment]
Hello @alirezaalavi87 ,

I will have a look at this. BTW, I've removed your email address for security reasons ;)

**Comment by alirezaalavi87** [comment]
Thank you

**Comment by kiarn** [comment]
I must test this because i'm not using the `auth_users` plugin.
The sudo elevation ist not supported yet in this authentication method, only in the OS authentication.

But you can create an user which is bound to the root account, giving this user all permissions.

**Comment by alirezaalavi87** [comment]
Isn't that too much of a security risk?

**Comment by kiarn** [comment]
Yes, it can be risky, it depends on your installation (in a DMZ, behind a firewall, etc ...) and the data stored on the server.
