### ISSUE TITLE
Centos 7 service will not start

### ISSUE THREAD

**Issue by gtabomber** [ajenti/ajenti#608]
## Ajenti bug report

| Info | Value |
| --- | --- |
| Ajenti | 1.2.22.13 |
| Platform | centos / centos / Linux 2.6.32-042stab093.4 x86_64 |
| Architecture | x86_64 x86_64 |
| Python | 2.7.5 |
| Installation | 76886101 |
| Debug | True |
| Catcher report | http://ajenti.org/catcher/view/43553 |
| Loaded plugins | dashboard, main |

| Library | Version |
| --- | --- |
| gevent | 1.0 |
| greenlet | 0.4.2 |
| reconfigure | 0.1.61 |
| requests | 1.1.0 |
| psutil | 0.6.1 |

```
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 133, in <module>
    core.run()
  File "/usr/lib/python2.7/site-packages/ajenti/core.py", line 88, in run
    ajenti.plugins.manager.load_all()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 266, in load_all
    self.load_recursive(item[0])
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 277, in load_recursive
    return self.load(name)
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 324, in load
    dependency.check()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 67, in check
    if not self.satisfied():
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 58, in satisfied
    self._was_satisfied = self.is_satisfied()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 131, in is_satisfied
    return subprocess.call(['which', self.binary_name]) == 0
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 115, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/site-packages/ajenti/compat.py", line 26, in Popen
    *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 238, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 755, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Log content:

```
2014-10-14 10:25:07,518 INFO     ajenti-panel.<module>(): Using config file /etc/ajenti/config.json
2014-10-14 10:25:07,558 INFO     ajenti-panel.<module>(): Ajenti starting in foreground
2014-10-14 10:25:07,692 INFO     registry.register_crypt_handler(): registered crypt handler 'sha512_crypt': <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
2014-10-14 10:25:07,782 DEBUG    compat.Popen(): Popen: git describe --tags 2> /dev/null
2014-10-14 10:25:07,811 DEBUG    compat.Popen(): Popen: ['lsb_release', '-sd']
2014-10-14 10:25:07,821 DEBUG    compat.Popen(): Popen: ['uname', '-mrs']
2014-10-14 10:25:07,828 INFO     core.run(): Ajenti 1.2.22.13 running on platform: centos
2014-10-14 10:25:07,831 DEBUG    __init__.load(): Loading plugin hdparm
2014-10-14 10:25:07,833 DEBUG    __init__.load_recursive(): Preloading plugin dependency: main
2014-10-14 10:25:07,835 DEBUG    __init__.load(): Loading plugin main
2014-10-14 10:25:07,847 DEBUG    __init__.load(): Loading plugin hdparm
2014-10-14 10:25:07,849 DEBUG    __init__.load_recursive(): Preloading plugin dependency: dashboard
2014-10-14 10:25:07,851 DEBUG    __init__.load(): Loading plugin dashboard
2014-10-14 10:25:07,857 DEBUG    __init__.load(): Loading plugin hdparm
2014-10-14 10:25:07,859 DEBUG    compat.Popen(): Popen: ['which', 'hdparm']
2014-10-14 10:25:07,867 ERROR    core.handle_crash(): Fatal crash occured
```

**Comment by batonac** [comment]
Judging by your kernel, I'm assuming that you're running a CentOS 7 container on OpenVZ.  I've experienced the same problem in the same scenario, but found that it's not a CentOS, OpenVZ, or Ajenti problem specifically, but simply a missing Ajenti package dependency in the default (minimal) CentOS 7 OpenVZ template.

I've done a diff between the packages installed on a working CentOS 7 machine and the packages installed in the container producing the error, and after installing all the missing packages in the container, Ajenti works!  I don't have time ATM to narrow down the search and find exactly which package was the missing dependency, but hopefully someone who knows more about Ajenti can peruse the following list and find the culprit(s):

`which virt-what usermode tuned trousers teamd t1lib sudo snappy slang setools-libs selinux-policy selinux-policy-targeted rsyslog rsync recode PyYAML python-slip python-slip-dbus python-rsa python-pyudev python-pygments python-prettytable python-markdown python-jsonpointer python-jsonpatch python-IPy python-decorator python-configobj python-cheetah python-boto pygobject3-base ppp postgresql-libs polkit polkit-pkla-compat policycoreutils policycoreutils-python plymouth plymouth-scripts plymouth-core-libs phpMyAdmin php-xml php-tidy php-tcpdf php-tcpdf-dejavu-sans-fonts php-recode php-process php-phpseclib-crypt-rijndael php-phpseclib-crypt-random php-phpseclib-crypt-base php-phpseclib-crypt-aes php-php-gettext php-pear php-mcrypt php-mbstring php-gd php-cli php-channel-phpseclib php-bcmath perl-WWW-RobotRules perl-URI perl-TimeDate perl-TermReadKey perl-Net-SSLeay perl-Net-LibIDN perl-Net-HTTP perl-LWP-MediaTypes perl-libwww-perl perl-IO-Socket-SSL perl-IO-Socket-IP perl-IO-HTML perl-HTTP-Negotiate perl-HTTP-Message perl-HTTP-Date perl-HTTP-Daemon perl-HTTP-Cookies perl-HTML-Tagset perl-HTML-Parser perl-Git perl-File-Listing perl-Error perl-Encode-Locale perl-Digest perl-Digest-MD5 perl-Business-ISBN perl-Business-ISBN-Data pciutils-libs parted os-prober numactl-libs ntpdate newt newt-python nettle mozjs17 ModemManager-glib microcode_ctl man-db mailcap lzo logrotate libzip libyaml libXpm libxcb libXau libX11 libX11-common libvpx libunistring libtool-ltdl libtidy libteam libsysfs libss libsoup libsemanage-python libselinux-utils libselinux-python libproxy libpng libpipeline libpciaccess libpcap libnl3 libnl3-cli libndp libmodman libmcrypt libgudev1 libgomp libgnome-keyring libestr libdrm libdaemon libcroco libcgroup kpartx kexec-tools kbd kbd-misc kbd-legacy json-c jansson irqbalance iprutils hwdata hardlink gsettings-desktop-schemas grubby grub2 grub2-tools gobject-introspection gnutls glib-networking gettext gettext-libs gd-last fxload fontpackages-filesystem fontconfig firewalld file ethtool elfutils-libs ebtables e2fsprogs dracut dracut-network dracut-config-rescue dnsmasq dmidecode dhcp-libs dhcp-common dhclient dejavu-sans-fonts dejavu-fonts-common cloud-init checkpolicy centos-logos btrfs-progs biosdevname bind-license bind-libs-lite avahi avahi-libs avahi-autoipd autogen-libopts authconfig audit audit-libs-python`

**Comment by batonac** [comment]
Okay I've found the missing dependency: which
`yum install which`
Installing this along with Ajenti in a freshly configured, vanilla CentOS 7 OpenVZ container (using template centos-7-x86_64-minimal.tar.gz) fixes the problem, at least in my experiments.
