### ISSUE TITLE
Ajenti doesn't work in Ubuntu 14.10

### ISSUE THREAD

**Issue by eloypr** [ajenti/ajenti#618]
```
8.10.2014 00:16 feedback.py:30                DEBUG Feedback >> ping ({'edition': 'vanilla', 'version': '1.2.22.16', 'os': 'debian', 'id': 83849})
28.10.2014 00:16 connectionpool.py:187         INFO  Starting new HTTP connection (1): meta.ajenti.org
28.10.2014 00:16 connectionpool.py:353         DEBUG "POST /api/v2/ping HTTP/1.1" 200 36
28.10.2014 00:16 feedback.py:35                DEBUG Feedback << {"status": "ok"}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 382, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 84, in __init__
    ctx = SSLContext(ssl_version)
NameError: global name 'SSLContext' is not defined
<Greenlet at 0x7f9c4d1a6910: <bound method SocketIOServer.wrap_socket_and_handle of <SocketIOServer at 0x7f9c4ccc4350 fileno=6 address=0.0.0.0:8000>>(<socket at 0x7f9c4cb73210 fileno=11 sock=127.0.0.1, ('127.0.0.1', 36338))> failed with NameError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 382, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 84, in __init__
    ctx = SSLContext(ssl_version)
NameError: global name 'SSLContext' is not defined
<Greenlet at 0x7f9c4d1a6910: <bound method SocketIOServer.wrap_socket_and_handle of <SocketIOServer at 0x7f9c4ccc4350 fileno=6 address=0.0.0.0:8000>>(<socket at 0x7f9c4cb73250 fileno=11 sock=127.0.0.1, ('127.0.0.1', 36340))> failed with NameError
```

NameError: global name 'SSLContext' is not defined

**Comment by Meai1** [comment]
this problem still exists and i also tried the steps here and now I get: 

```
          SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
           <Greenlet at 0x7f98b43a4910: <bound method SocketIOServer.wrap_socket_and_handle                  of <SocketIOServer at 0x7f98b3fbadd0 fileno=6 address=0.0.0.0:8000>>(<socket at 0x7f98b33e5a90 fileno=11 sock=5.9.78.24, ('193.154.230.67', 60884))> failed with SSLError
```

**Comment by CreativeWolf** [comment]
Thanks a lot eloypr - That did the trick!

**Comment by alessiodionisi** [comment]
I tried

```
sudo easy_install -U gevent
```

But did not solve the problem...

```
2015-05-27 15:09:34,244 INFO     users.check_password(): user root logged in through AjentiSyncProvider from 2.239.61.150
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/_sslgte279.py", line 636, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/_sslgte279.py", line 248, in __init__
    raise x
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)
<Greenlet at 0x7fa4ef860cd0: <bound method SocketIOServer.wrap_socket_and_handle of <SocketIOServer at 0x7fa4ef9e9590 fileno=8 address=0.0.0.0:8000>>(<socket at 0x7fa4ee41be10 fileno=17 sock=172.31.16, ('2.239.61.150', 38716))> failed with SSLEOFError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/_sslgte279.py", line 636, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/_sslgte279.py", line 248, in __init__
    raise x
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)
<Greenlet at 0x7fa4ef860d70: <bound method SocketIOServer.wrap_socket_and_handle of <SocketIOServer at 0x7fa4ef9e9590 fileno=8 address=0.0.0.0:8000>>(<socket at 0x7fa4ee41bd90 fileno=19 sock=172.31.16, ('2.239.61.150', 38717))> failed with SSLEOFError
```

**Comment by Whax** [comment]
Hi,

same problem here.

I tried also with the latest version available on github and the problems persists, same error as above. I'm on debian 8 Jessie

**Comment by jadethomas** [comment]
Updating gevent worked for me on ubantu 14.10. waahoo. thanks for your help

**Comment by diimpp** [comment]
Still broken.

Debian 7.8
python 2.7.3
gevent system and pip versions

**Comment by Schinti95** [comment]
Im also not able to use ajenti with SSL.
Debian 8.2
python 2.7.9

Result of: pip show gevent
```
---
Name: gevent
Version: 1.1b5
Location: /usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-x86_64.egg
Requires: greenlet
```

Result of: pip freeze
```
Mako==1.0.0
MarkupSafe==0.23
Pillow==2.6.1
Pygments==2.0.1
SOAPpy==0.12.22
ajenti==1.2.22.24
argparse==1.2.1
cffi==0.8.6
chardet==2.3.0
colorama==0.3.2
cryptography==0.6.1
defusedxml==0.4.1
docutils==0.12
gevent==1.1b5
gevent-socketio==0.3.6
gevent-websocket==0.9.3
greenlet==0.4.9
html5lib==0.999
lockfile==0.8
lxml==3.4.0
ndg-httpsclient==0.3.2
numpy==1.8.2
passlib==1.6.1
ply==3.4
psutil==2.1.1
pyOpenSSL==0.14
pyasn1==0.1.7
pycparser==2.10
pycrypto==2.6.1
pygobject==3.14.0
python-apt==0.9.3.12
python-catcher==0.1.7
python-daemon==1.5.5
python-debian==0.1.27
python-debianbts==1.11
python-exconsole==0.1.5
python-ldap==2.4.10
reconfigure==0.1.72
reportbug==6.6.3
requests==2.4.3
roman==2.0.0
six==1.8.0
urllib3==1.9.1
wheel==0.24.0
wsgiref==0.1.2
wstools==0.4.3
```

**Comment by tjbp** [comment]
Patch for ssl.py, working on Debian 8:

```
--- old.py      2016-02-03 23:55:08.769430293 +0000
+++ new.py      2016-02-03 23:56:00.134031892 +0000
@@ -81,14 +81,15 @@
             self._sslobj = None
         else:
             # yes, create the SSL object
-            ctx = SSLContext(ssl_version)
-            if keyfile or certfile:
-                ctx.load_cert_chain(certfile, keyfile)
-            if ca_certs:
-                ctx.load_verify_locations(ca_certs)
-            if ciphers:
-                ctx.set_ciphers(ciphers)
-            self._sslobj = ctx._wrap_socket(self._sock, server_side=server_side)
+            if ciphers is None:
+                self._sslobj = _ssl.sslwrap(self._sock, server_side,
+                                            keyfile, certfile,
+                                            cert_reqs, ssl_version, ca_certs)
+            else:
+                self._sslobj = _ssl.sslwrap(self._sock, server_side,
+                                            keyfile, certfile,
+                                            cert_reqs, ssl_version, ca_certs,
+                                            ciphers)
             if do_handshake_on_connect:
                 self.do_handshake()
         self.keyfile = keyfile
```
