### ISSUE TITLE
Can't launch on Debian

### ISSUE THREAD

**Issue by gdeligne** [ajenti/ajenti#687]
Hi,

I've just install the deb package on my debian and i'm unable to launch Ajenti.
Here is the report :
## Ajenti bug report

| Info | Value |
| --- | --- |
| Ajenti | 1.2.22.17 |
| Platform | debian / debian / Debian GNU/Linux 7.8 (wheezy) |
| Architecture | x86_64 unknown |
| Python | 2.7.3 |
| Installation | 6689295 |
| Debug | False |
| Catcher report | http://ajenti.org/catcher/view/76453 |
| Loaded plugins | ajenti_org, codemirror, configurator, cron, dashboard, db_common, fail2ban, fm, fstab, hosts, iptables, logs, main, mysql, network, notepad, packages, plugins, power, resolv, resources, scripts, sensors, services, taskmgr, tasks, terminal, uname, users, webserver_common |

| Library | Version |
| --- | --- |
| gevent | 0.13.6 |
| greenlet | 0.4.0 |
| reconfigure | 0.1.65 |
| requests | 0.12.1 |
| psutil | 0.6.1 |

```
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 126, in <module>
    core.run()
  File "/usr/lib/pymodules/python2.7/ajenti/core.py", line 89, in run
    Inflater.get().precache()
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 39, in precache
    self.inflate(temp_ui, layout)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 74, in inflate
    self.cache[layout] = self.inflate_rec(ui, xml)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 111, in inflate_rec
    element = self.create_element(ui, tag, children=children, **props)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 46, in create_element
    inst = cls.new(ui, context=(ui or self).context, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/api/__init__.py", line 91, in new
    return context.instantiate(cls, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/__init__.py", line 202, in instantiate
    init(instance)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/controls_inputs.py", line 117, in init
    self.dialog = self.ui.create('openfiledialog')
  File "/usr/lib/pymodules/python2.7/ajenti/ui/__init__.py", line 24, in create
    return self.inflater.create_element(self, typeid, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 46, in create_element
    inst = cls.new(ui, context=(ui or self).context, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/api/__init__.py", line 91, in new
    return context.instantiate(cls, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/__init__.py", line 202, in instantiate
    init(instance)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/controls_dialogs.py", line 98, in init
    self.refresh()
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/controls_dialogs.py", line 74, in refresh
    _dirs += sorted(os.listdir(unicode(self.path)))
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xda in position 1: invalid continuation byte
```

Log content:

```
2015-03-09 16:13:30,432 INFO     ajenti-panel.<module>(): Using config file /etc/ajenti/config.json
2015-03-09 16:13:30,725 INFO     registry.register_crypt_handler(): registered crypt handler 'sha512_crypt': <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
2015-03-09 16:13:30,921 DEBUG    compat.Popen(): Popen: git describe --tags 2> /dev/null
2015-03-09 16:13:30,974 DEBUG    compat.Popen(): Popen: ['lsb_release', '-sd']
2015-03-09 16:13:31,049 WARNING  core.run(): Couldn't set default locale
2015-03-09 16:13:31,051 INFO     core.run(): Ajenti 1.2.22.17 running on platform: debian
2015-03-09 16:13:31,056 DEBUG    __init__.load(): Loading plugin nsd
2015-03-09 16:13:31,057 DEBUG    __init__.load_recursive(): Preloading plugin dependency: main
2015-03-09 16:13:31,058 DEBUG    __init__.load(): Loading plugin main
2015-03-09 16:13:31,081 DEBUG    __init__.load(): Loading plugin nsd
2015-03-09 16:13:31,082 DEBUG    __init__.load_recursive(): Preloading plugin dependency: services
2015-03-09 16:13:31,082 DEBUG    __init__.load(): Loading plugin services
2015-03-09 16:13:31,085 DEBUG    __init__.load_recursive(): Preloading plugin dependency: dashboard
2015-03-09 16:13:31,085 DEBUG    __init__.load(): Loading plugin dashboard
2015-03-09 16:13:31,094 DEBUG    __init__.load(): Loading plugin services
2015-03-09 16:13:31,120 INFO     sm_upstart.verify(): Disabling Upstart service manager: org.freedesktop.DBus.Error.ServiceUnknown: The name com.ubuntu.Upstart was not provided by any .service files
2015-03-09 16:13:31,121 DEBUG    compat.Popen(): Popen: ['which', 'systemctl']
2015-03-09 16:13:31,139 DEBUG    __init__.load(): Loading plugin nsd
2015-03-09 16:13:31,140 DEBUG    compat.Popen(): Popen: ['which', 'nsd']
2015-03-09 16:13:31,149 DEBUG    __init__.load():  *** [nsd] skipping due to BinaryDependency (nsd)
2015-03-09 16:13:31,150 DEBUG    __init__.load(): Loading plugin supervisor
2015-03-09 16:13:31,151 DEBUG    compat.Popen(): Popen: ['which', 'supervisord']
2015-03-09 16:13:31,160 DEBUG    __init__.load():  *** [supervisor] skipping due to BinaryDependency (supervisord)
2015-03-09 16:13:31,162 DEBUG    __init__.load(): Loading plugin snmpd
2015-03-09 16:13:31,162 DEBUG    compat.Popen(): Popen: ['which', 'snmpd']
2015-03-09 16:13:31,171 DEBUG    __init__.load():  *** [snmpd] skipping due to BinaryDependency (snmpd)
2015-03-09 16:13:31,173 DEBUG    __init__.load(): Loading plugin rethink
2015-03-09 16:13:31,174 DEBUG    __init__.load_recursive(): Preloading plugin dependency: db_common
2015-03-09 16:13:31,174 DEBUG    __init__.load(): Loading plugin db_common
2015-03-09 16:13:31,176 DEBUG    __init__.load(): Loading plugin rethink
2015-03-09 16:13:31,177 DEBUG    compat.Popen(): Popen: ['which', 'rethinkdb']
2015-03-09 16:13:31,185 DEBUG    __init__.load():  *** [rethink] skipping due to BinaryDependency (rethinkdb)
2015-03-09 16:13:31,187 DEBUG    __init__.load(): Loading plugin psql
2015-03-09 16:13:31,188 DEBUG    compat.Popen(): Popen: ['which', 'psql']
2015-03-09 16:13:31,197 DEBUG    __init__.load():  *** [psql] skipping due to BinaryDependency (psql)
2015-03-09 16:13:31,198 DEBUG    __init__.load(): Loading plugin cron
2015-03-09 16:13:31,199 DEBUG    compat.Popen(): Popen: ['which', 'crontab']
2015-03-09 16:13:31,211 DEBUG    __init__.load(): Loading plugin iptables
2015-03-09 16:13:31,239 DEBUG    compat.Popen(): Popen: ['which', 'ip6tables']
2015-03-09 16:13:31,250 DEBUG    __init__.load(): Loading plugin dhcpd
2015-03-09 16:13:31,251 DEBUG    compat.Popen(): Popen: ['which', 'dhcpd']
2015-03-09 16:13:31,260 DEBUG    __init__.load():  *** [dhcpd] skipping due to BinaryDependency (dhcpd)
2015-03-09 16:13:31,261 DEBUG    __init__.load(): Loading plugin taskmgr
2015-03-09 16:13:31,264 DEBUG    __init__.load(): Loading plugin fail2ban
2015-03-09 16:13:31,265 DEBUG    compat.Popen(): Popen: ['which', 'fail2ban-client']
2015-03-09 16:13:31,274 DEBUG    compat.Popen(): Popen: ['which', 'fail2ban-regex']
2015-03-09 16:13:31,287 DEBUG    __init__.load(): Loading plugin ntpd
2015-03-09 16:13:31,288 DEBUG    compat.Popen(): Popen: ['which', 'ntpd']
2015-03-09 16:13:31,297 DEBUG    __init__.load():  *** [ntpd] skipping due to BinaryDependency (ntpd)
2015-03-09 16:13:31,298 DEBUG    __init__.load(): Loading plugin squid
2015-03-09 16:13:31,299 DEBUG    compat.Popen(): Popen: ['which', 'squid3']
2015-03-09 16:13:31,308 DEBUG    __init__.load():  *** [squid] skipping due to BinaryDependency (squid3)
2015-03-09 16:13:31,309 DEBUG    __init__.load(): Loading plugin network
2015-03-09 16:13:31,318 DEBUG    __init__.load(): Loading plugin packages
2015-03-09 16:13:31,319 DEBUG    __init__.load_recursive(): Preloading plugin dependency: terminal
2015-03-09 16:13:31,319 DEBUG    __init__.load(): Loading plugin terminal
2015-03-09 16:13:31,365 DEBUG    __init__.load(): Loading plugin packages
2015-03-09 16:13:31,372 DEBUG    __init__.load(): Loading plugin configurator
2015-03-09 16:13:31,377 DEBUG    __init__.load(): Loading plugin exports
2015-03-09 16:13:31,378 DEBUG    compat.Popen(): Popen: ['which', 'nfsstat']
2015-03-09 16:13:31,390 DEBUG    __init__.load():  *** [exports] skipping due to BinaryDependency (nfsstat)
2015-03-09 16:13:31,391 DEBUG    __init__.load(): Loading plugin munin
2015-03-09 16:13:31,392 DEBUG    compat.Popen(): Popen: ['which', 'munin-cron']
2015-03-09 16:13:31,402 DEBUG    __init__.load():  *** [munin] skipping due to BinaryDependency (munin-cron)
2015-03-09 16:13:31,403 DEBUG    __init__.load(): Loading plugin fm
2015-03-09 16:13:31,404 DEBUG    __init__.load_recursive(): Preloading plugin dependency: tasks
2015-03-09 16:13:31,404 DEBUG    __init__.load(): Loading plugin tasks
2015-03-09 16:13:31,435 DEBUG    __init__.load(): Loading plugin fm
2015-03-09 16:13:31,439 DEBUG    __init__.load(): Loading plugin ajenti_org
2015-03-09 16:13:31,441 DEBUG    __init__.load(): Loading plugin power
2015-03-09 16:13:31,443 DEBUG    compat.Popen(): Popen: ['which', 'systemctl']
2015-03-09 16:13:31,453 DEBUG    compat.Popen(): Popen: ['which', 'pm-hibernate']
2015-03-09 16:13:31,464 DEBUG    __init__.load(): Loading plugin fstab
2015-03-09 16:13:31,471 DEBUG    __init__.load(): Loading plugin openvpn
2015-03-09 16:13:31,471 DEBUG    compat.Popen(): Popen: ['which', 'openvpn']
2015-03-09 16:13:31,481 DEBUG    __init__.load():  *** [openvpn] skipping due to BinaryDependency (openvpn)
2015-03-09 16:13:31,482 DEBUG    __init__.load(): Loading plugin notepad
2015-03-09 16:13:31,483 DEBUG    __init__.load_recursive(): Preloading plugin dependency: codemirror
2015-03-09 16:13:31,483 DEBUG    __init__.load(): Loading plugin codemirror
2015-03-09 16:13:31,485 DEBUG    __init__.load(): Loading plugin notepad
2015-03-09 16:13:31,487 DEBUG    __init__.load(): Loading plugin elements
2015-03-09 16:13:31,487 WARNING  __init__.load():  *** [elements] Plugin error: format error
2015-03-09 16:13:31,489 DEBUG    __init__.load(): Loading plugin nginx
2015-03-09 16:13:31,489 DEBUG    __init__.load_recursive(): Preloading plugin dependency: webserver_common
2015-03-09 16:13:31,489 DEBUG    __init__.load(): Loading plugin webserver_common
2015-03-09 16:13:31,493 DEBUG    __init__.load(): Loading plugin nginx
2015-03-09 16:13:31,493 DEBUG    compat.Popen(): Popen: ['which', 'nginx']
2015-03-09 16:13:31,502 DEBUG    __init__.load():  *** [nginx] skipping due to BinaryDependency (nginx)
2015-03-09 16:13:31,504 DEBUG    __init__.load(): Loading plugin mongo
2015-03-09 16:13:31,505 DEBUG    compat.Popen(): Popen: ['which', 'mongod']
2015-03-09 16:13:31,514 DEBUG    __init__.load():  *** [mongo] skipping due to BinaryDependency (mongod)
2015-03-09 16:13:31,516 DEBUG    __init__.load(): Loading plugin scripts
2015-03-09 16:13:31,519 DEBUG    __init__.load(): Loading plugin ctdb
2015-03-09 16:13:31,519 DEBUG    compat.Popen(): Popen: ['which', 'ctdb']
2015-03-09 16:13:31,529 DEBUG    __init__.load():  *** [ctdb] skipping due to BinaryDependency (ctdb)
2015-03-09 16:13:31,530 DEBUG    __init__.load(): Loading plugin sensors
2015-03-09 16:13:31,535 DEBUG    __init__.load(): Loading plugin ipmi
2015-03-09 16:13:31,536 DEBUG    compat.Popen(): Popen: ['which', 'ipmitool']
2015-03-09 16:13:31,546 DEBUG    __init__.load():  *** [ipmi] skipping due to BinaryDependency (ipmitool)
2015-03-09 16:13:31,547 DEBUG    __init__.load(): Loading plugin resources
2015-03-09 16:13:31,552 DEBUG    __init__.load(): Loading plugin apcups
2015-03-09 16:13:31,553 DEBUG    compat.Popen(): Popen: ['which', 'apcaccess']
2015-03-09 16:13:31,575 DEBUG    __init__.load():  *** [apcups] skipping due to BinaryDependency (apcaccess)
2015-03-09 16:13:31,577 DEBUG    __init__.load(): Loading plugin megaraid
2015-03-09 16:13:31,579 DEBUG    __init__.load():  *** [megaraid] skipping due to FileDependency (/opt/MegaRAID/MegaCli/MegaCli)
2015-03-09 16:13:31,580 DEBUG    __init__.load(): Loading plugin users
2015-03-09 16:13:31,584 DEBUG    __init__.load(): Loading plugin resolv
2015-03-09 16:13:31,587 DEBUG    __init__.load(): Loading plugin samba
2015-03-09 16:13:31,588 DEBUG    compat.Popen(): Popen: ['which', 'smbd']
2015-03-09 16:13:31,609 DEBUG    __init__.load():  *** [samba] skipping due to BinaryDependency (smbd)
2015-03-09 16:13:31,611 DEBUG    __init__.load(): Loading plugin mysql
2015-03-09 16:13:31,613 DEBUG    compat.Popen(): Popen: ['which', 'mysql']
2015-03-09 16:13:31,634 DEBUG    compat.Popen(): Popen: ['which', 'mysqld_safe']
2015-03-09 16:13:31,660 DEBUG    __init__.load(): Loading plugin logs
2015-03-09 16:13:31,665 DEBUG    __init__.load(): Loading plugin plugins
2015-03-09 16:13:31,667 DEBUG    __init__.load(): Loading plugin uname
2015-03-09 16:13:31,671 DEBUG    __init__.load(): Loading plugin smartctl
2015-03-09 16:13:31,672 DEBUG    compat.Popen(): Popen: ['which', 'smartctl']
2015-03-09 16:13:31,694 DEBUG    __init__.load():  *** [smartctl] skipping due to BinaryDependency (smartctl)
2015-03-09 16:13:31,696 DEBUG    __init__.load(): Loading plugin hddtemp
2015-03-09 16:13:31,697 DEBUG    compat.Popen(): Popen: ['which', 'hddtemp']
2015-03-09 16:13:31,719 DEBUG    __init__.load():  *** [hddtemp] skipping due to BinaryDependency (hddtemp)
2015-03-09 16:13:31,721 DEBUG    __init__.load(): Loading plugin hdparm
2015-03-09 16:13:31,723 DEBUG    compat.Popen(): Popen: ['which', 'hdparm']
2015-03-09 16:13:31,747 DEBUG    __init__.load():  *** [hdparm] skipping due to BinaryDependency (hdparm)
2015-03-09 16:13:31,748 DEBUG    __init__.load(): Loading plugin raid
2015-03-09 16:13:31,750 DEBUG    compat.Popen(): Popen: ['which', 'mdadm']
2015-03-09 16:13:31,794 DEBUG    __init__.load():  *** [raid] skipping due to BinaryDependency (mdadm)
2015-03-09 16:13:31,796 DEBUG    __init__.load(): Loading plugin memcache
2015-03-09 16:13:31,797 DEBUG    compat.Popen(): Popen: ['which', 'memcached']
2015-03-09 16:13:31,814 DEBUG    __init__.load():  *** [memcache] skipping due to BinaryDependency (memcached)
2015-03-09 16:13:31,816 DEBUG    __init__.load(): Loading plugin bind9
2015-03-09 16:13:31,818 DEBUG    compat.Popen(): Popen: ['which', 'named']
2015-03-09 16:13:31,843 DEBUG    __init__.load():  *** [bind9] skipping due to BinaryDependency (named)
2015-03-09 16:13:31,844 DEBUG    __init__.load(): Loading plugin apache
2015-03-09 16:13:31,846 DEBUG    compat.Popen(): Popen: ['which', 'apache2']
2015-03-09 16:13:31,866 DEBUG    __init__.load():  *** [apache] skipping due to BinaryDependency (apache2)
2015-03-09 16:13:31,867 DEBUG    __init__.load(): Loading plugin hosts
2015-03-09 16:13:31,871 DEBUG    __init__.load(): Loading plugin lm_sensors
2015-03-09 16:13:31,872 DEBUG    compat.Popen(): Popen: ['which', 'sensors']
2015-03-09 16:13:31,893 DEBUG    __init__.load():  *** [lm_sensors] skipping due to BinaryDependency (sensors)
2015-03-09 16:13:31,895 DEBUG    __init__.load(): Loading plugin netatalk
2015-03-09 16:13:31,896 DEBUG    compat.Popen(): Popen: ['which', 'afpd']
2015-03-09 16:13:31,917 DEBUG    __init__.load():  *** [netatalk] skipping due to BinaryDependency (afpd)
2015-03-09 16:13:31,919 DEBUG    __init__.load(): Loading plugin csf
2015-03-09 16:13:31,921 DEBUG    compat.Popen(): Popen: ['which', 'csf']
2015-03-09 16:13:31,941 DEBUG    __init__.load():  *** [csf] skipping due to BinaryDependency (csf)
2015-03-09 16:13:32,020 DEBUG    __init__.instantiate(): Root context instantiated [Inflater] <ajenti.ui.inflater.Inflater object at 0x17d4990>
2015-03-09 16:13:32,022 DEBUG    __init__.instantiate(): Root context instantiated [UI] <ajenti.ui.UI object at 0x17f6ad0>
2015-03-09 16:13:32,023 DEBUG    inflater.precache(): Precaching layout main:input-dialog
2015-03-09 16:13:32,026 DEBUG    inflater.precache(): Precaching layout main:file-dialog-save
2015-03-09 16:13:32,028 DEBUG    inflater.precache(): Precaching layout main:file-dialog
2015-03-09 16:13:32,029 DEBUG    inflater.precache(): Precaching layout main:passwd-main
2015-03-09 16:13:32,031 DEBUG    inflater.precache(): Precaching layout dashboard:dash
2015-03-09 16:13:32,035 DEBUG    inflater.precache(): Precaching layout dashboard:welcome
2015-03-09 16:13:32,036 DEBUG    inflater.precache(): Precaching layout dashboard:text
2015-03-09 16:13:32,038 DEBUG    inflater.precache(): Precaching layout services:bar
2015-03-09 16:13:32,039 DEBUG    inflater.precache(): Precaching layout services:main
2015-03-09 16:13:32,041 DEBUG    inflater.precache(): Precaching layout services:widget
2015-03-09 16:13:32,043 DEBUG    inflater.precache(): Precaching layout db_common:main
2015-03-09 16:13:32,049 DEBUG    inflater.precache(): Precaching layout cron:main
2015-03-09 16:13:32,056 DEBUG    inflater.precache(): Precaching layout iptables:option-address
2015-03-09 16:13:32,058 DEBUG    inflater.precache(): Precaching layout iptables:option-custom
2015-03-09 16:13:32,059 DEBUG    inflater.precache(): Precaching layout iptables:option-match
2015-03-09 16:13:32,061 DEBUG    inflater.precache(): Precaching layout iptables:option-ports
2015-03-09 16:13:32,062 DEBUG    inflater.precache(): Precaching layout iptables:option-interface
2015-03-09 16:13:32,063 DEBUG    inflater.precache(): Precaching layout iptables:option-reject-with
2015-03-09 16:13:32,065 DEBUG    inflater.precache(): Precaching layout iptables:option-state
2015-03-09 16:13:32,067 DEBUG    inflater.precache(): Precaching layout iptables:main
2015-03-09 16:13:32,071 DEBUG    inflater.precache(): Precaching layout iptables:option
2015-03-09 16:13:32,072 DEBUG    inflater.precache(): Precaching layout iptables:option-port
2015-03-09 16:13:32,074 DEBUG    inflater.precache(): Precaching layout iptables:option-protocol
2015-03-09 16:13:32,076 DEBUG    inflater.precache(): Precaching layout taskmgr:main
2015-03-09 16:13:32,079 DEBUG    inflater.precache(): Precaching layout fail2ban:main
2015-03-09 16:13:32,083 DEBUG    __init__.instantiate(): Root context instantiated [SysVInitServiceManager] <ajenti.plugins.services.sm_sysvinit.SysVInitServiceManager object at 0x185d410>
2015-03-09 16:13:32,083 DEBUG    __init__.instantiate(): Root context instantiated [ServiceMultiplexor] <ajenti.plugins.services.api.ServiceMultiplexor object at 0x1857a50>
2015-03-09 16:13:32,084 DEBUG    compat.Popen(): Popen: [u'/etc/init.d/fail2ban', 'status']
2015-03-09 16:13:32,173 DEBUG    compat.Popen(): Popen: [u'/etc/init.d/fail2ban', 'status']
2015-03-09 16:13:32,381 DEBUG    inflater.precache(): Precaching layout network:bit-linux-basic
2015-03-09 16:13:32,385 DEBUG    inflater.precache(): Precaching layout network:bit-linux-dhcp
2015-03-09 16:13:32,389 DEBUG    inflater.precache(): Precaching layout network:bit-linux-ipv4
2015-03-09 16:13:32,392 DEBUG    inflater.precache(): Precaching layout network:main
2015-03-09 16:13:32,396 DEBUG    inflater.precache(): Precaching layout network:bit-linux-ifupdown
2015-03-09 16:13:32,398 DEBUG    inflater.precache(): Precaching layout network:widget
2015-03-09 16:13:32,400 DEBUG    inflater.precache(): Precaching layout terminal:main
2015-03-09 16:13:32,402 DEBUG    inflater.precache(): Precaching layout terminal:config
2015-03-09 16:13:32,404 DEBUG    inflater.precache(): Precaching layout packages:installer
2015-03-09 16:13:32,406 DEBUG    inflater.precache(): Precaching layout packages:row
2015-03-09 16:13:32,408 DEBUG    inflater.precache(): Precaching layout packages:headers
2015-03-09 16:13:32,409 DEBUG    inflater.precache(): Precaching layout packages:main
2015-03-09 16:13:32,417 DEBUG    inflater.precache(): Precaching layout configurator:ldap-sync-config
2015-03-09 16:13:32,420 DEBUG    inflater.precache(): Precaching layout configurator:main
2015-03-09 16:13:32,425 ERROR    core.handle_crash(): Fatal crash occured
```

Thanks for your help.
Regards,
Guillaume

**Comment by jjoc** [comment]
Hi you. 99% UP with Automatic or Manual Install from:
http://support.ajenti.org/topic/349864-installing-on-debian/

**Comment by gdeligne** [comment]
Anyone with the same issue or any idea on how to fix it ?
