### ISSUE TITLE
Install but nothing 

### ISSUE THREAD

**Issue by chadyred** [ajenti/ajenti#718]
I can't launch ajenti on port 8000. This is the log of the command ajenti panel and i have no port running under '8000'. I also change the '0.0.0.0' to 127.0.0.1.

I don't use any firewall (iptable or firewalld).

<pre>
Ajenti bug report
--------------------

Info | Value
----- | -----
Ajenti | 1.2.22.19
Platform | debian / ubuntu / Ubuntu 14.04.2 LTS
Architecture | x86_64 x86_64
Python | 2.7.6
Installation | 66914213
Debug | True
...
...
 2015-05-13 00:24:54,433 DEBUG    compat.Popen(): Popen: ['which', 'ipmitool']
    2015-05-13 00:24:54,440 DEBUG    __init__.load():  *** [ipmi] skipping due to BinaryDependency (ipmitool)
    2015-05-13 00:24:54,444 DEBUG    __init__.instantiate(): Root context instantiated [Inflater] <ajenti.ui.inflater.Inflater object at 0x7fe054f24550>
    2015-05-13 00:24:54,448 DEBUG    __init__.instantiate(): Root context instantiated [UI] <ajenti.ui.UI object at 0x7fe0563e8350>
    2015-05-13 00:24:54,450 DEBUG    inflater.precache(): Precaching layout main:passwd-main
    2015-05-13 00:24:54,451 DEBUG    inflater.precache(): Precaching layout main:file-dialog-save
    2015-05-13 00:24:54,452 DEBUG    inflater.precache(): Precaching layout main:file-dialog
    2015-05-13 00:24:54,453 DEBUG    inflater.precache(): Precaching layout main:input-dialog
    2015-05-13 00:24:54,454 DEBUG    inflater.precache(): Precaching layout dashboard:text
    2015-05-13 00:24:54,455 DEBUG    inflater.precache(): Precaching layout dashboard:welcome
    2015-05-13 00:24:54,456 DEBUG    inflater.precache(): Precaching layout dashboard:dash
    2015-05-13 00:24:54,458 DEBUG    inflater.precache(): Precaching layout services:widget
    2015-05-13 00:24:54,460 DEBUG    inflater.precache(): Precaching layout services:bar
    2015-05-13 00:24:54,461 DEBUG    inflater.precache(): Precaching layout services:main
    2015-05-13 00:24:54,463 DEBUG    inflater.precache(): Precaching layout git:main
    2015-05-13 00:24:54,466 DEBUG    inflater.precache(): Precaching layout git:main-userlist
    2015-05-13 00:24:54,468 DEBUG    inflater.precache(): Precaching layout git:main-repolist
    2015-05-13 00:24:54,470 DEBUG    inflater.precache(): Precaching layout terminal:config
    2015-05-13 00:24:54,470 DEBUG    inflater.precache(): Precaching layout terminal:main
    2015-05-13 00:24:54,472 DEBUG    inflater.precache(): Precaching layout hosts:main
    2015-05-13 00:24:54,474 DEBUG    inflater.precache(): Precaching layout cron:main
    2015-05-13 00:24:54,479 DEBUG    inflater.precache(): Precaching layout webserver_common:main
    2015-05-13 00:24:54,482 DEBUG    inflater.precache(): Precaching layout db_common:main
    2015-05-13 00:24:54,486 DEBUG    inflater.precache(): Precaching layout notepad:config
    2015-05-13 00:24:54,487 DEBUG    inflater.precache(): Precaching layout notepad:main
    2015-05-13 00:24:54,489 ERROR    core.handle_crash(): Fatal crash occured
</pre>

And directly after the command, this prompt to me : 

<pre>
13.05.2015 00:29 core.py:191                   ERROR Fatal crash occured
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 133, in <module>
    core.run()
  File "/usr/lib/pymodules/python2.7/ajenti/core.py", line 89, in run
    Inflater.get().precache()
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 39, in precache
    self.inflate(temp_ui, layout)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 74, in inflate
    self.cache[layout] = self.inflate_rec(ui, xml)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 111, in inflate_rec
    element = self.create_element(ui, tag, children=children, **props)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 46, in create_element
    inst = cls.new(ui, context=(ui or self).context, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/api/__init__.py", line 91, in new
    return context.instantiate(cls, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/__init__.py", line 202, in instantiate
    init(instance)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/controls_dialogs.py", line 98, in init
    self.refresh()
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/controls_dialogs.py", line 74, in refresh
    _dirs += sorted(os.listdir(unicode(self.path)))
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8e in position 1: invalid start byte
</pre>

**Comment by bassybeats** [comment]
I had this issue on a local server. But rebooting the VPS seemed to fix the issue.
