### ISSUE TITLE
Ajenti don`t working

### ISSUE THREAD

**Issue by Mel0ne** [ajenti/ajenti#722]
Сервис подымается, работает, а в веб-морду зайти не могу. Следующий лог выдает: 

2015-05-22 06:33:19,267 INFO     core.run(): Ajenti 1.2.22.19 running on platform: debian
2015-05-22 06:33:19,326 INFO     sm_upstart.verify(): Disabling Upstart service manager: org.freedesktop.DBus.Error.ServiceUnknown: The name com.ubuntu.Upstart was not provided by any .service files
2015-05-22 06:33:19,381 INFO     sm_systemd.verify(): Disabling systemd service manager: global name 'SystemdService' is not defined
2015-05-22 06:33:19,440 WARNING  **init**.load():  **\* [elements] Plugin error: format error
2015-05-22 06:33:20,065 INFO     core.run(): Starting server on (u'0.0.0.0', 8182)
2015-05-22 06:33:20,069 INFO     core.run(): SSL enabled: /etc/ajenti/ajenti.pem
2015-05-22 06:33:20,079 INFO     connectionpool._new_conn(): Starting new HTTP connection (1): meta.ajenti.org
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 382, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 84, in __init__
    ctx = SSLContext(ssl_version)
NameError: global name 'SSLContext' is not defined
<Greenlet at 0x7fdac73dd2d0: <bound method SocketIOServer.wrap_socket_and_handle of <SocketIOServer at 0x7fdac74b4d90 fileno=8 address=0.0.0.0:8182>>(<socket at 0x7fdac7a64990 fileno=13 sock=178.62.15, ('46.8.192.58', 59500))> failed with NameError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 382, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 84, in __init__
    ctx = SSLContext(ssl_version)
NameError: global name 'SSLContext' is not defined
<Greenlet at 0x7fdac73dd2d0: <bound method SocketIOServer.wrap_socket_and_handle of <SocketIOServer at 0x7fdac74b4d90 fileno=8 address=0.0.0.0:8182>>(<socket at 0x7fdac7a64990 fileno=13 sock=178.62.15, ('46.8.192.58', 59502))> failed with NameError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 382, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 84, in __init__
    ctx = SSLContext(ssl_version)
NameError: global name 'SSLContext' is not defined
<Greenlet at 0x7fdac73dd2d0: <bound method SocketIOServer.wrap_socket_and_handle of <SocketIOServer at 0x7fdac74b4d90 fileno=8 address=0.0.0.0:8182>>(<socket at 0x7fdac7a64990 fileno=13 sock=178.62.15, ('46.8.192.58', 59503))> failed with NameError

**Comment by Mel0ne** [comment]
Решение проблемы\solve of problem

https://github.com/Eugeny/ajenti/issues/702#issuecomment-98543089

**Comment by tejastank** [comment]
Getting same issue to configure linux server.
