### ISSUE TITLE
Can't delete MySQL Database from Website

### ISSUE THREAD

**Issue by janxb** [ajenti/ajenti#724]
I can't delete an added MySQL-Database from a Website. I am using Ajenti-V and MariaDB 10.
If I press the "delete"-Button, the Database get's deleted, but stays in the database list in ajenti. If i press the delete button again, an error message appears saying "cant delete database because it doesn't exist".

I can remove the database from the list by pressing the "unlink from website" button after i have deleted it.

list.remove(x): x not in list
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/main.py", line 158, in handle_message
    self.ui.dispatch_event(update['uid'], update['event'], update['params'])
  File "/usr/lib/pymodules/python2.7/ajenti/ui/**init**.py", line 72, in dispatch_event
    self.root.dispatch_event(uid, event, params)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 378, in dispatch_event
    self.event(event, params)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 404, in event
    self.events[event](*self.event_args[event], **%28params or {}%29)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/binder.py", line 433, in on_delete
    self.ui.delete_item(item, self.collection)
  File "/var/lib/ajenti/plugins/vh-mysql/mysql.py", line 68, in <lambda>
    self.find('databases').delete_item = lambda i, c: self.on_delete_db(i)
  File "/var/lib/ajenti/plugins/vh-mysql/mysql.py", line 169, in on_delete_db
    self.config['databases'].remove(db)
ValueError: list.remove(x): x not in list

**Comment by janxb** [comment]
One more Information: I am able to delete the Database without any error message in the MySQL plugin. But it stays visible in the websites mysql area. I have to do the same thing ("unlink from website") as above.

**Comment by janxb** [comment]
I will close this issue to clean up, don't know the solution but it didn't occur for a while.. ;)
