### ISSUE TITLE
Ajenti + Debian = SSL Problem

### ISSUE THREAD

**Issue by bbbenji** [ajenti/ajenti#745]
I am experiencing 2 issues which I think are related. The first is when I enable the SSL on Ajenti, after logging in all I get is a blank page with the navbar. Secondly I am unable to setup an email client to use STARTTLS nor SSL/TLS. Without encryption both work as they should. When it comes to accessing a website created with Ajenti on my server with SSL it works fine. Though I did generate it by hand since Ajenti does not include an auto-gen SSL feature for websites yet. (Edit: generating certificate manually for Ajenti and email did not help.)

I did not apply the fix, ([discussed here](https://github.com/ajenti/ajenti/issues/702)) because my `/usr/local/lib/python2.7/dist-packages/gevent-1.1a1-py2.7-linux-x86_64.egg/gevent/ssl.py` already contains `ssl_version=PROTOCOL_SSLv23`. 

ajenti.log:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1a1-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 368, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1a1-py2.7-linux-x86_64.egg/gevent/baseserver.py", line 133, in _close_when_done
    return handle(*args)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1a1-py2.7-linux-x86_64.egg/gevent/server.py", line 127, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1a1-py2.7-linux-x86_64.egg/gevent/_sslgte279.py", line 660, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1a1-py2.7-linux-x86_64.egg/gevent/_sslgte279.py", line 260, in __init__
    raise x
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:581)
<Greenlet at 0x7f6689046550: _close_when_done(<socket at 0x7f6688ee2310 fileno=[Errno 9] Bad fil, ('xx.xxx.xx.xx', 44065))> failed with SSLEOFE$
```

uname -a:

```
Linux serv000000 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
```

Any ideas? Anything else I can provide?

**Comment by lukasmrtvy** [comment]
There is should be a fix
https://github.com/gevent/gevent/commit/4d8f7d58a772cbeaec161e8931e8b65c841ba38d

**Comment by bbbenji** [comment]
Thanks muhahacz, that fixed my Ajenti SSL problem. Although the email STARTTLS problem still exists. I guess they were not related.

EDIT: Looks like it might be a problem with Thunderbird sending data too quickly.

```
SMTP protocol synchronization error (next input sent too soon: pipelining was not advertised): rejected "EHLO we-guess.mozilla.org" H=[xx.xxx.xx.xx] next input="QUIT\r\n"
```
