### ISSUE TITLE
Ajenti in CentOS 7 not running Python error

### ISSUE THREAD

**Issue by willstdueswissen** [ajenti/ajenti#747]
Hello,
i habe a problem with Ajenti.
Can ans one help me?
Sorry for my Bad english! 
The log:

2015-07-10 02:28:12,778 INFO     core.run(): Ajenti 1.2.22.13 running on platform: centos
2015-07-10 02:28:12,789 ERROR    core.handle_crash(): Fatal crash occured
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 126, in <module>
    core.run()
  File "/usr/lib/python2.7/site-packages/ajenti/core.py", line 88, in run
    ajenti.plugins.manager.load_all()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 266, in load_all
    self.load_recursive(item[0])
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 277, in load_recursive
    return self.load(name)
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 324, in load
    dependency.check()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 67, in check
    if not self.satisfied():
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 58, in satisfied
    self._was_satisfied = self.is_satisfied()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 131, in is_satisfied
    return subprocess.call(['which', self.binary_name]) == 0
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 115, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/site-packages/ajenti/compat.py", line 26, in Popen
    _args, *_kwargs)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 238, in **init**
    errread, errwrite)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 756, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2015-07-10 02:28:13,079 ERROR    core.handle_crash(): Crash report written to /root/ajenti-crash.txt
2015-07-10 02:28:13,079 ERROR    core.handle_crash(): Please submit it to https://github.com/Eugeny/ajenti/issues/new
2015-07-10 02:28:13,079 ERROR   : Please submit it to https://github.com/Eugeny/ajenti/issues/new

**Comment by Eugeny** [comment]
please see if this helps: `yum install zsh`

**Comment by willstdueswissen** [comment]
After install zsh i get more errors:
2015-07-10 03:25:13,617 INFO     registry.register_crypt_handler(): registered crypt handler 'sha512_crypt': <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
2015-07-10 03:25:13,659 INFO     core.run(): Ajenti 1.2.22.13 running on platform: centos
2015-07-10 03:25:13,669 INFO     sm_upstart.verify(): Disabling Upstart service manager: org.freedesktop.DBus.Error.ServiceUnknown: The name com.ubuntu.Upstart was not provided by any .service files
2015-07-10 03:25:13,675 WARNING  **init**.load():  **\* [services] Plugin crashed: crashed: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 328, in load
    info.init()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/services/**init**.py", line 22, in init
    import sm_systemd
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/services/sm_systemd.py", line 14, in <module>
    class SystemdServiceManager (ServiceManager):
  File "/usr/lib/python2.7/site-packages/ajenti/api/**init**.py", line 67, in plugin
    if not cls.verify():
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/services/sm_systemd.py", line 22, in verify
    return subprocess.call(['which', 'systemctl']) == 0
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 115, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/site-packages/ajenti/compat.py", line 26, in Popen
    _args, *_kwargs)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 238, in **init**
    errread, errwrite)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 755, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

2015-07-10 03:25:13,676 WARNING  **init**.load_recursive():  **\* Plugin dependency unsatisfied: netatalk -> services
2015-07-10 03:25:13,679 ERROR    core.handle_crash(): Fatal crash occured
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 126, in <module>
    core.run()
  File "/usr/lib/python2.7/site-packages/ajenti/core.py", line 88, in run
    ajenti.plugins.manager.load_all()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 266, in load_all
    self.load_recursive(item[0])
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 277, in load_recursive
    return self.load(name)
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 324, in load
    dependency.check()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 67, in check
    if not self.satisfied():
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 58, in satisfied
    self._was_satisfied = self.is_satisfied()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 131, in is_satisfied
    return subprocess.call(['which', self.binary_name]) == 0
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 115, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/site-packages/ajenti/compat.py", line 26, in Popen
    _args, *_kwargs)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 238, in **init**
    errread, errwrite)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 755, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2015-07-10 03:25:13,815 INFO     connectionpool._new_conn(): Starting new HTTP connection (1): ajenti.org
2015-07-10 03:25:13,886 ERROR    core.handle_crash(): Crash report written to /root/ajenti-crash.txt
2015-07-10 03:25:13,886 ERROR    core.handle_crash(): Please submit it to https://github.com/Eugeny/ajenti/issues/new
2015-07-10 03:25:13,886 ERROR   : Please submit it to https://github.com/Eugeny/ajenti/issues/new

**Comment by willstdueswissen** [comment]
## Ajenti bug report

| Info | Value |
| --- | --- |
| Ajenti | 1.2.22.13 |
| Platform | centos / centos / Linux 2.6.32-042stab104.1 x86_64 |
| Architecture | x86_64 x86_64 |
| Python | 2.7.5 |
| Installation | 29091544 |
| Debug | True |
| Loaded plugins | dashboard, logs, main, resolv |

| Library | Version |
| --- | --- |
| gevent | 1.0 |
| greenlet | 0.4.2 |
| reconfigure | 0.1.62 |
| requests | 1.1.0 |
| psutil | 1.2.1 |

```
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 133, in <module>
    core.run()
  File "/usr/lib/python2.7/site-packages/ajenti/core.py", line 88, in run
    ajenti.plugins.manager.load_all()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 266, in load_all
    self.load_recursive(item[0])
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 277, in load_recursive
    return self.load(name)
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 324, in load
    dependency.check()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 67, in check
    if not self.satisfied():
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 58, in satisfied
    self._was_satisfied = self.is_satisfied()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 131, in is_satisfied
    return subprocess.call(['which', self.binary_name]) == 0
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 115, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/site-packages/ajenti/compat.py", line 26, in Popen
    *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 238, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 755, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Log content:

```
2015-07-10 03:53:44,185 INFO     ajenti-panel.<module>(): Using config file /etc/ajenti/config.json
2015-07-10 03:53:44,219 INFO     ajenti-panel.<module>(): Ajenti starting in foreground
2015-07-10 03:53:44,282 INFO     registry.register_crypt_handler(): registered crypt handler 'sha512_crypt': <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
2015-07-10 03:53:44,368 DEBUG    compat.Popen(): Popen: git describe --tags 2> /dev/null
2015-07-10 03:53:44,377 DEBUG    compat.Popen(): Popen: ['lsb_release', '-sd']
2015-07-10 03:53:44,381 DEBUG    compat.Popen(): Popen: ['uname', '-mrs']
2015-07-10 03:53:44,384 INFO     core.run(): Ajenti 1.2.22.13 running on platform: centos
2015-07-10 03:53:44,385 DEBUG    __init__.load(): Loading plugin services
2015-07-10 03:53:44,386 DEBUG    __init__.load_recursive(): Preloading plugin dependency: main
2015-07-10 03:53:44,386 DEBUG    __init__.load(): Loading plugin main
2015-07-10 03:53:44,390 DEBUG    __init__.load(): Loading plugin services
2015-07-10 03:53:44,390 DEBUG    __init__.load_recursive(): Preloading plugin dependency: dashboard
2015-07-10 03:53:44,391 DEBUG    __init__.load(): Loading plugin dashboard
2015-07-10 03:53:44,392 DEBUG    __init__.load(): Loading plugin services
2015-07-10 03:53:44,413 INFO     sm_upstart.verify(): Disabling Upstart service manager: org.freedesktop.DBus.Error.ServiceUnknown: The name com.ubuntu.Upstart was not provided by any .service files
2015-07-10 03:53:44,417 DEBUG    compat.Popen(): Popen: ['which', 'systemctl']
2015-07-10 03:53:44,421 WARNING  __init__.load():  *** [services] Plugin crashed: crashed: [Errno 2] No such file or directory
2015-07-10 03:53:44,422 DEBUG    __init__.load(): Loading plugin logs
2015-07-10 03:53:44,423 DEBUG    __init__.load(): Loading plugin resolv
2015-07-10 03:53:44,424 DEBUG    __init__.load(): Loading plugin netatalk
2015-07-10 03:53:44,424 WARNING  __init__.load_recursive():  *** Plugin dependency unsatisfied: netatalk -> services
2015-07-10 03:53:44,425 DEBUG    __init__.load(): Loading plugin exports
2015-07-10 03:53:44,425 DEBUG    compat.Popen(): Popen: ['which', 'nfsstat']
2015-07-10 03:53:44,429 ERROR    core.handle_crash(): Fatal crash occured
```

**Comment by willstdueswissen** [comment]
So i see the popen command.
2015-07-10 03:53:44,417 DEBUG    compat.Popen(): Popen: ['which', 'systemctl']
2015-07-10 03:53:44,421 WARNING  **init**.load():  **\* [services] Plugin crashed: crashed: [Errno 2] No such file or directory

After i install which
Its run :+1: 
~~But no i have ssl protocl error~~ <- after reinstall fix ;)
