### ISSUE TITLE
Error on Ajenti start

### ISSUE THREAD

**Issue by Djyp** [ajenti/ajenti#757]
## Ajenti bug report

| Info | Value |
| --- | --- |
| Ajenti | 1.2.22.22 |
| Platform | debian / debian / Debian GNU/Linux 7.8 (wheezy) |
| Architecture | x86_64 unknown |
| Python | 2.7.3 |
| Installation | 74937419 |
| Debug | True |
| Catcher report | <!DOCTYPE html> |

<html xmlns="http://www.w3.org/1999/xhtml" ng:app="app">
    <head>
        <title>Ajenti Webserver Control Panel</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="google-site-verification" content="x4PklNIAhqnDXEZBGXgbdxTTGGbRvEdHATuGeEaA7xg" />
        <link rel="icon" type="image/png" href="/static/home/favicon.png" />

```
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:700,400' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto:100,400' rel='stylesheet' type='text/css'>

    <script src="//cdn.jsdelivr.net/jquery/2.1.1/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/angularjs/1.2.17/angular.min.js"></script>
    <script src="//cdn.jsdelivr.net/g/bootstrap@3.0.3,ekko-lightbox,jquery.slick,angularui"></script>
    <link href="//cdn.jsdelivr.net/g/bootstrap@3.0.3(css/bootstrap.min.css)" rel="stylesheet">

    <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.slick/1.3.2/slick.css">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/fontawesome/4.0.3/css/font-awesome.css">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/angularui/0.4.0/angular-ui.min.css">

    <link rel="stylesheet" href="/static/CACHE/css/b5c22129cde7.css" type="text/css" />
    <script type="text/javascript" src="/static/CACHE/js/f756ca6b5462.js"></script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-3278102-8', 'ajenti.org');
      ga('send', 'pageview');
    </script>
</head>

<body data-spy="scroll" data-target="#navigation">
    <div class="top-area">
        <nav class="navbar">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">ajenti</a>
                </div>
                <ul class="nav navbar-nav">
                    <li>
                        <a href="http://support.ajenti.org/" target="_blank">
                            <i class="fa fa-book"></i> Docs
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/Eugeny/ajenti/" target="_blank">
                            <i class="fa fa-github"></i> GitHub
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/Eugeny/ajenti/issues/new" target="_blank">
                            <i class="fa fa-bug"></i> Report a bug
                        </a>
                    </li>
                    <li>
                        <a href="http://docs1.ajenti.org/en/latest/" target="_blank">
                            <i class="fa fa-cog"></i> Developer docs
                        </a>
                    </li>
                    <li>
                        <a href="/licensing">
                            <i class="fa fa-usd"></i> Licensing
                        </a>
                    </li>
                </ul>
            </div>
        </nav>



    </div>

    <div id="page">

404, sorry

    </div>

    <div class="footer">
        <div class="container">
            <div class="link pull-right">
                <a href="https://mixpanel.com/f/partner"><img src="//cdn.mxpnl.com/site_media/images/partner/badge_light.png" alt="Mobile Analytics" /></a>
            </div>
            <div class="link pull-right">
                CDN by&nbsp;&nbsp;<a href="http://jsdelivr.com/">jsDelivr</a> &amp; <a href="http://maxcdn.com">MaxCDN</a>
            </div>
            <div class="link">
                © Ajenti Project
            </div>
            <div class="link">
                <a href="mailto:e@ajenti.org"><i class="fa fa-envelope"></i></a>
            </div>
        </div>
    </div>



    <script type='text/javascript'>
        // UserEcho --------------------
        var _ues = {
        host:'ajenti.userecho.com',
        forum:'8996',
        lang:'en',
        tab_corner_radius:8,
        tab_font_size:22,
        tab_image_hash:'RmVlZGJhY2s%3D',
        tab_alignment:'left',
        tab_text_color:'#FFFFFF',
        tab_bg_color:'#9E9E9E',
        tab_hover_color:'#595959'
        };

        (function() {
            var _ue = document.createElement('script'); _ue.type = 'text/javascript'; _ue.async = true;
            _ue.src = ('https:' == document.location.protocol ? 'https://s3.amazonaws.com/' : 'http://') + 'cdn.userecho.com/js/widget-1.4.gz.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(_ue, s);
          })();

    </script>

    <script type="text/javascript">
        // Analytics --------------------------
      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>

    <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=408484792592752";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
</body>
```

</html>

Loaded plugins | ajenti_org, bind9, codemirror, configurator, cron, dashboard, db_common, fm, fstab, hosts, iptables, logs, main, munin, mysql, network, nginx, notepad, packages, plugins, power, psql, resolv, resources, scripts, sensors, services, supervisor, taskmgr, tasks, terminal, uname, users, vh, vh-gunicorn, vh-mail, vh-mysql, vh-nginx, vh-nodejs, vh-php-fpm, vh-pureftpd, vh-unicorn, webserver_common

| Library | Version |
| --- | --- |
| gevent | 0.13.6 |
| greenlet | 0.4.0 |
| reconfigure | 0.1.72 |
| requests | 0.12.1 |
| psutil | 0.6.1 |

```
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 133, in <module>
    core.run()
  File "/usr/lib/pymodules/python2.7/ajenti/core.py", line 89, in run
    Inflater.get().precache()
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 39, in precache
    self.inflate(temp_ui, layout)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 74, in inflate
    self.cache[layout] = self.inflate_rec(ui, xml)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 111, in inflate_rec
    element = self.create_element(ui, tag, children=children, **props)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 46, in create_element
    inst = cls.new(ui, context=(ui or self).context, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/api/__init__.py", line 91, in new
    return context.instantiate(cls, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/__init__.py", line 202, in instantiate
    init(instance)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/controls_inputs.py", line 117, in init
    self.dialog = self.ui.create('openfiledialog')
  File "/usr/lib/pymodules/python2.7/ajenti/ui/__init__.py", line 24, in create
    return self.inflater.create_element(self, typeid, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 46, in create_element
    inst = cls.new(ui, context=(ui or self).context, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/api/__init__.py", line 91, in new
    return context.instantiate(cls, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/__init__.py", line 202, in instantiate
    init(instance)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/controls_dialogs.py", line 98, in init
    self.refresh()
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/controls_dialogs.py", line 74, in refresh
    _dirs += sorted(os.listdir(unicode(self.path)))
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 0: invalid start byte
```

Log content:

```
2015-07-20 16:54:43,862 INFO     ajenti-panel.<module>(): Using config file /etc/ajenti/config.json
2015-07-20 16:54:43,892 INFO     ajenti-panel.<module>(): Ajenti starting in foreground
2015-07-20 16:54:43,975 INFO     registry.register_crypt_handler(): registered crypt handler 'sha512_crypt': <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
2015-07-20 16:54:44,040 DEBUG    compat.Popen(): Popen: git describe --tags 2> /dev/null
2015-07-20 16:54:44,057 DEBUG    compat.Popen(): Popen: ['lsb_release', '-sd']
2015-07-20 16:54:44,086 INFO     core.run(): Ajenti 1.2.22.22 running on platform: debian
2015-07-20 16:54:44,087 DEBUG    __init__.load(): Loading plugin configurator
2015-07-20 16:54:44,089 DEBUG    __init__.load_recursive(): Preloading plugin dependency: main
2015-07-20 16:54:44,089 DEBUG    __init__.load(): Loading plugin main
2015-07-20 16:54:44,097 DEBUG    __init__.load(): Loading plugin configurator
2015-07-20 16:54:44,099 DEBUG    __init__.load(): Loading plugin users
2015-07-20 16:54:44,101 DEBUG    __init__.load(): Loading plugin hddtemp
2015-07-20 16:54:44,103 DEBUG    __init__.load_recursive(): Preloading plugin dependency: dashboard
2015-07-20 16:54:44,103 DEBUG    __init__.load(): Loading plugin dashboard
2015-07-20 16:54:44,107 DEBUG    __init__.load(): Loading plugin hddtemp
2015-07-20 16:54:44,108 DEBUG    compat.Popen(): Popen: ['which', 'hddtemp']
2015-07-20 16:54:44,114 DEBUG    __init__.load():  *** [hddtemp] skipping due to BinaryDependency (hddtemp)
2015-07-20 16:54:44,115 DEBUG    __init__.load(): Loading plugin ctdb
2015-07-20 16:54:44,117 DEBUG    __init__.load_recursive(): Preloading plugin dependency: services
2015-07-20 16:54:44,118 DEBUG    __init__.load(): Loading plugin services
2015-07-20 16:54:44,127 INFO     sm_upstart.verify(): Disabling Upstart service manager: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: Aucun fichier ou dossier de ce type
2015-07-20 16:54:44,136 DEBUG    compat.Popen(): Popen: ['which', 'systemctl']
2015-07-20 16:54:44,143 DEBUG    __init__.load(): Loading plugin ctdb
2015-07-20 16:54:44,144 DEBUG    compat.Popen(): Popen: ['which', 'ctdb']
2015-07-20 16:54:44,148 DEBUG    __init__.load():  *** [ctdb] skipping due to BinaryDependency (ctdb)
2015-07-20 16:54:44,149 DEBUG    __init__.load(): Loading plugin nginx
2015-07-20 16:54:44,150 DEBUG    __init__.load_recursive(): Preloading plugin dependency: webserver_common
2015-07-20 16:54:44,151 DEBUG    __init__.load(): Loading plugin webserver_common
2015-07-20 16:54:44,153 DEBUG    __init__.load(): Loading plugin nginx
2015-07-20 16:54:44,154 DEBUG    compat.Popen(): Popen: ['which', 'nginx']
2015-07-20 16:54:44,158 DEBUG    __init__.load(): Loading plugin openvpn
2015-07-20 16:54:44,160 DEBUG    compat.Popen(): Popen: ['which', 'openvpn']
2015-07-20 16:54:44,164 DEBUG    __init__.load():  *** [openvpn] skipping due to BinaryDependency (openvpn)
2015-07-20 16:54:44,165 DEBUG    __init__.load(): Loading plugin plugins
2015-07-20 16:54:44,167 DEBUG    __init__.load(): Loading plugin power
2015-07-20 16:54:44,169 DEBUG    compat.Popen(): Popen: ['which', 'systemctl']
2015-07-20 16:54:44,177 DEBUG    compat.Popen(): Popen: ['which', 'pm-hibernate']
2015-07-20 16:54:44,182 DEBUG    __init__.load(): Loading plugin uname
2015-07-20 16:54:44,184 DEBUG    __init__.load(): Loading plugin squid
2015-07-20 16:54:44,186 DEBUG    compat.Popen(): Popen: ['which', 'squid3']
2015-07-20 16:54:44,190 DEBUG    __init__.load():  *** [squid] skipping due to BinaryDependency (squid3)
2015-07-20 16:54:44,191 DEBUG    __init__.load(): Loading plugin hosts
2015-07-20 16:54:44,193 DEBUG    __init__.load(): Loading plugin taskmgr
2015-07-20 16:54:44,211 DEBUG    __init__.load(): Loading plugin memcache
2015-07-20 16:54:44,212 DEBUG    compat.Popen(): Popen: ['which', 'memcached']
2015-07-20 16:54:44,216 DEBUG    __init__.load():  *** [memcache] skipping due to BinaryDependency (memcached)
2015-07-20 16:54:44,217 DEBUG    __init__.load(): Loading plugin mongo
2015-07-20 16:54:44,219 DEBUG    __init__.load_recursive(): Preloading plugin dependency: db_common
2015-07-20 16:54:44,219 DEBUG    __init__.load(): Loading plugin db_common
2015-07-20 16:54:44,220 DEBUG    __init__.load(): Loading plugin mongo
2015-07-20 16:54:44,221 DEBUG    compat.Popen(): Popen: ['which', 'mongod']
2015-07-20 16:54:44,225 DEBUG    __init__.load():  *** [mongo] skipping due to BinaryDependency (mongod)
2015-07-20 16:54:44,226 DEBUG    __init__.load(): Loading plugin psql
2015-07-20 16:54:44,227 DEBUG    compat.Popen(): Popen: ['which', 'psql']
2015-07-20 16:54:44,232 DEBUG    __init__.load(): Loading plugin samba
2015-07-20 16:54:44,233 DEBUG    compat.Popen(): Popen: ['which', 'smbd']
2015-07-20 16:54:44,237 DEBUG    __init__.load():  *** [samba] skipping due to BinaryDependency (smbd)
2015-07-20 16:54:44,238 DEBUG    __init__.load(): Loading plugin nsd
2015-07-20 16:54:44,239 DEBUG    compat.Popen(): Popen: ['which', 'nsd']
2015-07-20 16:54:44,243 DEBUG    __init__.load():  *** [nsd] skipping due to BinaryDependency (nsd)
2015-07-20 16:54:44,244 DEBUG    __init__.load(): Loading plugin apache
2015-07-20 16:54:44,245 DEBUG    compat.Popen(): Popen: ['which', 'apache2']
2015-07-20 16:54:44,249 DEBUG    __init__.load():  *** [apache] skipping due to BinaryDependency (apache2)
2015-07-20 16:54:44,250 DEBUG    __init__.load(): Loading plugin notepad
2015-07-20 16:54:44,251 DEBUG    __init__.load_recursive(): Preloading plugin dependency: codemirror
2015-07-20 16:54:44,251 DEBUG    __init__.load(): Loading plugin codemirror
2015-07-20 16:54:44,252 DEBUG    __init__.load(): Loading plugin notepad
2015-07-20 16:54:44,254 DEBUG    __init__.load(): Loading plugin exports
2015-07-20 16:54:44,255 DEBUG    compat.Popen(): Popen: ['which', 'nfsstat']
2015-07-20 16:54:44,259 DEBUG    __init__.load():  *** [exports] skipping due to BinaryDependency (nfsstat)
2015-07-20 16:54:44,260 DEBUG    __init__.load(): Loading plugin iptables
2015-07-20 16:54:44,262 DEBUG    compat.Popen(): Popen: ['which', 'ip6tables']
2015-07-20 16:54:44,272 DEBUG    __init__.load(): Loading plugin mysql
2015-07-20 16:54:44,274 DEBUG    compat.Popen(): Popen: ['which', 'mysql']
2015-07-20 16:54:44,277 DEBUG    compat.Popen(): Popen: ['which', 'mysqld_safe']
2015-07-20 16:54:44,282 DEBUG    __init__.load(): Loading plugin logs
2015-07-20 16:54:44,286 DEBUG    __init__.load(): Loading plugin lm_sensors
2015-07-20 16:54:44,287 DEBUG    compat.Popen(): Popen: ['which', 'sensors']
2015-07-20 16:54:44,291 DEBUG    __init__.load():  *** [lm_sensors] skipping due to BinaryDependency (sensors)
2015-07-20 16:54:44,292 DEBUG    __init__.load(): Loading plugin ntpd
2015-07-20 16:54:44,293 DEBUG    compat.Popen(): Popen: ['which', 'ntpd']
2015-07-20 16:54:44,297 DEBUG    __init__.load():  *** [ntpd] skipping due to BinaryDependency (ntpd)
2015-07-20 16:54:44,298 DEBUG    __init__.load(): Loading plugin netatalk
2015-07-20 16:54:44,299 DEBUG    compat.Popen(): Popen: ['which', 'afpd']
2015-07-20 16:54:44,303 DEBUG    __init__.load():  *** [netatalk] skipping due to BinaryDependency (afpd)
2015-07-20 16:54:44,304 DEBUG    __init__.load(): Loading plugin scripts
2015-07-20 16:54:44,305 DEBUG    __init__.load_recursive(): Preloading plugin dependency: terminal
2015-07-20 16:54:44,305 DEBUG    __init__.load(): Loading plugin terminal
2015-07-20 16:54:44,315 DEBUG    __init__.load(): Loading plugin scripts
2015-07-20 16:54:44,316 DEBUG    __init__.load(): Loading plugin fail2ban
2015-07-20 16:54:44,317 DEBUG    compat.Popen(): Popen: ['which', 'fail2ban-client']
2015-07-20 16:54:44,321 DEBUG    __init__.load():  *** [fail2ban] skipping due to BinaryDependency (fail2ban-client)
2015-07-20 16:54:44,322 DEBUG    __init__.load(): Loading plugin smartctl
2015-07-20 16:54:44,323 DEBUG    compat.Popen(): Popen: ['which', 'smartctl']
2015-07-20 16:54:44,327 DEBUG    __init__.load():  *** [smartctl] skipping due to BinaryDependency (smartctl)
2015-07-20 16:54:44,328 DEBUG    __init__.load(): Loading plugin ajenti_org
2015-07-20 16:54:44,330 DEBUG    __init__.load(): Loading plugin resources
2015-07-20 16:54:44,331 DEBUG    __init__.load(): Loading plugin supervisor
2015-07-20 16:54:44,332 DEBUG    compat.Popen(): Popen: ['which', 'supervisord']
2015-07-20 16:54:44,337 DEBUG    __init__.load(): Loading plugin resolv
2015-07-20 16:54:44,339 DEBUG    __init__.load(): Loading plugin tasks
2015-07-20 16:54:44,340 DEBUG    __init__.load_recursive(): Preloading plugin dependency: cron
2015-07-20 16:54:44,340 DEBUG    __init__.load(): Loading plugin cron
2015-07-20 16:54:44,341 DEBUG    compat.Popen(): Popen: ['which', 'crontab']
2015-07-20 16:54:44,346 DEBUG    __init__.load(): Loading plugin tasks
2015-07-20 16:54:44,355 DEBUG    __init__.load(): Loading plugin ipmi
2015-07-20 16:54:44,356 DEBUG    compat.Popen(): Popen: ['which', 'ipmitool']
2015-07-20 16:54:44,360 DEBUG    __init__.load():  *** [ipmi] skipping due to BinaryDependency (ipmitool)
2015-07-20 16:54:44,361 DEBUG    __init__.load(): Loading plugin sensors
2015-07-20 16:54:44,363 DEBUG    __init__.load(): Loading plugin fstab
2015-07-20 16:54:44,366 DEBUG    __init__.load(): Loading plugin network
2015-07-20 16:54:44,369 DEBUG    __init__.load(): Loading plugin megaraid
2015-07-20 16:54:44,369 DEBUG    __init__.load():  *** [megaraid] skipping due to FileDependency (/opt/MegaRAID/MegaCli/MegaCli)
2015-07-20 16:54:44,370 DEBUG    __init__.load(): Loading plugin munin
2015-07-20 16:54:44,371 DEBUG    compat.Popen(): Popen: ['which', 'munin-cron']
2015-07-20 16:54:44,385 DEBUG    __init__.load(): Loading plugin csf
2015-07-20 16:54:44,386 DEBUG    compat.Popen(): Popen: ['which', 'csf']
2015-07-20 16:54:44,390 DEBUG    __init__.load():  *** [csf] skipping due to BinaryDependency (csf)
2015-07-20 16:54:44,391 DEBUG    __init__.load(): Loading plugin rethink
2015-07-20 16:54:44,392 DEBUG    compat.Popen(): Popen: ['which', 'rethinkdb']
2015-07-20 16:54:44,396 DEBUG    __init__.load():  *** [rethink] skipping due to BinaryDependency (rethinkdb)
2015-07-20 16:54:44,397 DEBUG    __init__.load(): Loading plugin fm
2015-07-20 16:54:44,399 DEBUG    __init__.load(): Loading plugin packages
2015-07-20 16:54:44,402 DEBUG    __init__.load(): Loading plugin bind9
2015-07-20 16:54:44,403 DEBUG    compat.Popen(): Popen: ['which', 'named']
2015-07-20 16:54:44,407 DEBUG    __init__.load(): Loading plugin git
2015-07-20 16:54:44,409 DEBUG    compat.Popen(): Popen: ['which', 'git']
2015-07-20 16:54:44,413 DEBUG    compat.Popen(): Popen: ['which', 'gitolite']
2015-07-20 16:54:44,417 DEBUG    __init__.load():  *** [git] skipping due to BinaryDependency (gitolite)
2015-07-20 16:54:44,418 DEBUG    __init__.load(): Loading plugin raid
2015-07-20 16:54:44,419 DEBUG    compat.Popen(): Popen: ['which', 'mdadm']
2015-07-20 16:54:44,423 DEBUG    __init__.load():  *** [raid] skipping due to BinaryDependency (mdadm)
2015-07-20 16:54:44,424 DEBUG    __init__.load(): Loading plugin dhcpd
2015-07-20 16:54:44,425 DEBUG    compat.Popen(): Popen: ['which', 'dhcpd']
2015-07-20 16:54:44,429 DEBUG    __init__.load():  *** [dhcpd] skipping due to BinaryDependency (dhcpd)
2015-07-20 16:54:44,431 DEBUG    __init__.load(): Loading plugin apcups
2015-07-20 16:54:44,432 DEBUG    compat.Popen(): Popen: ['which', 'apcaccess']
2015-07-20 16:54:44,436 DEBUG    __init__.load():  *** [apcups] skipping due to BinaryDependency (apcaccess)
2015-07-20 16:54:44,437 DEBUG    __init__.load(): Loading plugin hdparm
2015-07-20 16:54:44,438 DEBUG    compat.Popen(): Popen: ['which', 'hdparm']
2015-07-20 16:54:44,442 DEBUG    __init__.load():  *** [hdparm] skipping due to BinaryDependency (hdparm)
2015-07-20 16:54:44,443 DEBUG    __init__.load(): Loading plugin snmpd
2015-07-20 16:54:44,444 DEBUG    compat.Popen(): Popen: ['which', 'snmpd']
2015-07-20 16:54:44,448 DEBUG    __init__.load():  *** [snmpd] skipping due to BinaryDependency (snmpd)
2015-07-20 16:54:44,449 DEBUG    __init__.load(): Loading plugin vh-gunicorn
2015-07-20 16:54:44,450 DEBUG    __init__.load_recursive(): Preloading plugin dependency: vh
2015-07-20 16:54:44,451 DEBUG    __init__.load(): Loading plugin vh
2015-07-20 16:54:44,455 DEBUG    __init__.load(): Loading plugin vh-gunicorn
2015-07-20 16:54:44,456 DEBUG    __init__.load(): Loading plugin vh-nodejs
2015-07-20 16:54:44,457 DEBUG    __init__.load(): Loading plugin vh-php-fpm
2015-07-20 16:54:44,458 DEBUG    compat.Popen(): Popen: ['which', 'php5-fpm']
2015-07-20 16:54:44,463 DEBUG    __init__.load(): Loading plugin vh-mail
2015-07-20 16:54:44,465 DEBUG    __init__.load(): Loading plugin vh-unicorn
2015-07-20 16:54:44,466 DEBUG    compat.Popen(): Popen: ['which', 'unicorn_rails']
2015-07-20 16:54:44,471 DEBUG    __init__.load(): Loading plugin vh-pureftpd
2015-07-20 16:54:44,472 DEBUG    compat.Popen(): Popen: ['which', 'pure-pw']
2015-07-20 16:54:44,476 DEBUG    compat.Popen(): Popen: ['which', 'pure-ftpd']
2015-07-20 16:54:44,481 DEBUG    __init__.load(): Loading plugin vh-mysql
2015-07-20 16:54:44,482 DEBUG    compat.Popen(): Popen: ['which', 'mysql']
2015-07-20 16:54:44,487 DEBUG    compat.Popen(): Popen: ['which', 'mysqld_safe']
2015-07-20 16:54:44,491 DEBUG    __init__.load(): Loading plugin vh-nginx
2015-07-20 16:54:44,496 DEBUG    __init__.instantiate(): Root context instantiated [Inflater] <ajenti.ui.inflater.Inflater object at 0x192a710>
2015-07-20 16:54:44,498 DEBUG    __init__.instantiate(): Root context instantiated [UI] <ajenti.ui.UI object at 0x1e04cd0>
2015-07-20 16:54:44,499 DEBUG    inflater.precache(): Precaching layout main:file-dialog
2015-07-20 16:54:44,500 DEBUG    inflater.precache(): Precaching layout main:passwd-main
2015-07-20 16:54:44,502 DEBUG    inflater.precache(): Precaching layout main:input-dialog
2015-07-20 16:54:44,503 DEBUG    inflater.precache(): Precaching layout main:file-dialog-save
2015-07-20 16:54:44,506 DEBUG    inflater.precache(): Precaching layout configurator:main
2015-07-20 16:54:44,509 ERROR    core.handle_crash(): Fatal crash occured
```

**Comment by Djyp** [comment]
I don't know what to do with that... I can't use Ajenti anymore.

It all started after I tried to install Taiga (python project). I think there's a library conflict somewhere...
I tried to uninstall and reinstall Ajenti : brought nothing :/

Any idea where should I look to go further with that ?

**Comment by Djyp** [comment]
So... I searched for this : 'utf8' codec can't decode byte 0xc0
Which led me to that page : http://stackoverflow.com/questions/22216076/unicodedecodeerror-utf8-codec-cant-decode-byte-0xa5-in-position-0-invalid-s

Which made me try, hopelessly to change line 16 of /usr/lib/python2.7/encodings/utf_8.py and add .strip(), of course it didn't work. So I took i off, saved the file and now Ajenti is working... WTH happened ? :s 

Well anyway... problem solved !
