### ISSUE TITLE
Ajenti SSL issues on Debian

### ISSUE THREAD

**Issue by gsnick** [ajenti/ajenti#767]
Hello,

I installed Ajenti on Debian. Configured it to work over HTTPS.
When I access it I see it does not open and shows bellow errors:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/_sslgte279.py", line 636, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/_sslgte279.py", line 248, in __init__
    raise x
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
<Greenlet at 0x7fbbaddcee10: <bound method SocketIOServer.wrap_socket_and_handle of <SocketIOServer at 0x7fbbad6b1cd0 fileno=6 address=0.0.0.0:8000>>(<socket at 0x7fbbacc11a90 fileno=12 sock=204.45.31, ('195.22.241.230', 1284))> failed with SSLError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/_sslgte279.py", line 636, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/_sslgte279.py", line 248, in __init__
    raise x
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:581)
<Greenlet at 0x7fbbaddcee10: <bound method SocketIOServer.wrap_socket_and_handle of <SocketIOServer at 0x7fbbad6b1cd0 fileno=6 address=0.0.0.0:8000>>(<socket at 0x7fbbacc11ad0 fileno=12 sock=204.45.31, ('195.22.241.230', 2089))> failed with SSLEOFError

Can someone help fix or advice how to fix above errors?
Thank you in advance!

**Comment by alessiodionisi** [comment]
Same error on Ubuntu 15

**Comment by Xefir** [comment]
Can you update gevent by doing easy_install -U gevent ?

The latest version on debian seems to be the 1.1b3 witch fixes this problem.
This is a case on jessie, i've not tested on wheezy, please come back if the problem is still present after the update on wheezy.

**Comment by alessiodionisi** [comment]
Yes, gevent 1.1b3 solve the problem!

**Comment by steschi** [comment]
I don't know why but gevent 1.1b3 as well as 1.1b5 do not solve the problem for me on Debian 8.2

**Comment by lots0logs** [comment]
1.1b3 works for me on Ubuntu 15.10. For any others affected by this:

```
pip install https://github.com/gevent/gevent/releases/download/v1.1b3/gevent-1.1b3.tar.gz
systemctl restart ajenti
```

Cheers!

**Comment by Eugeny** [comment]
The fixed `gevent-socketio` package (compatible with the new `gevent` versions) is now available in the Ajenti repo. You should be able to just update it, or install manually from http://repo.ajenti.org/debian/pool/ubuntu/g/gevent-socketio/python-gevent-socketio_0.3.7.99-1_all.deb
