### ISSUE TITLE
Error after ajenti upgrade "    UnicodeDecodeError: 'utf8' codec can't decode byte 0xc9 in position 1: invalid continuation byte"

### ISSUE THREAD

**Issue by RonnyLV** [ajenti/ajenti#788]
Error after upgrading Ajenti " UnicodeDecodeError: 'utf8' codec can't decode byte 0xc9 in position 1: invalid continuation byte"
## Ajenti bug report

| Info | Value |
| --- | --- |
| Ajenti | 1.2.22.24 |
| Platform | debian / ubuntu / Ubuntu 14.04.3 LTS |
| Architecture | x86_64 x86_64 |
| Python | 2.7.6 |
| Installation | 51320341 |
| Debug | True |
| Catcher report | <!DOCTYPE html> |

<html xmlns="http://www.w3.org/1999/xhtml" ng:app="app">
    <head>
        <title>Ajenti Server Admin Panel</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="google-site-verification" content="x4PklNIAhqnDXEZBGXgbdxTTGGbRvEdHATuGeEaA7xg" />
        <link rel="icon" type="image/png" href="/static/home/favicon.png" />

```
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:700,400' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto:100,400' rel='stylesheet' type='text/css'>

    <script src="//cdn.jsdelivr.net/jquery/2.1.1/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/angularjs/1.2.17/angular.min.js"></script>
    <script src="//cdn.jsdelivr.net/g/bootstrap@3.0.3,ekko-lightbox,jquery.slick,angularui"></script>
    <link href="//cdn.jsdelivr.net/g/bootstrap@3.0.3(css/bootstrap.min.css)" rel="stylesheet">

    <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.slick/1.3.2/slick.css">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/fontawesome/4.0.3/css/font-awesome.css">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/angularui/0.4.0/angular-ui.min.css">

    <link rel="stylesheet" href="/static/CACHE/css/b5c22129cde7.css" type="text/css" />
    <script type="text/javascript" src="/static/CACHE/js/f756ca6b5462.js"></script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-3278102-8', 'ajenti.org');
      ga('send', 'pageview');
    </script>
</head>

<body data-spy="scroll" data-target="#navigation">
    <div class="top-area">
        <nav class="navbar">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">ajenti</a>
                </div>
                <ul class="nav navbar-nav">
                    <li>
                        <a href="http://support.ajenti.org/" target="_blank">
                            <i class="fa fa-book"></i> Docs
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/Eugeny/ajenti/" target="_blank">
                            <i class="fa fa-github"></i> GitHub
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/Eugeny/ajenti/issues/new" target="_blank">
                            <i class="fa fa-bug"></i> Report a bug
                        </a>
                    </li>
                    <li>
                        <a href="http://docs1.ajenti.org/en/latest/" target="_blank">
                            <i class="fa fa-cog"></i> Developer docs
                        </a>
                    </li>
                    <li>
                        <a href="/licensing">
                            <i class="fa fa-usd"></i> Licensing
                        </a>
                    </li>
                </ul>
            </div>
        </nav>



    </div>

    <div id="page">

404, sorry

    </div>

    <div class="footer">
        <div class="container">
            <div class="link pull-right">
                <a href="https://mixpanel.com/f/partner"><img src="//cdn.mxpnl.com/site_media/images/partner/badge_light.png" alt="Mobile Analytics" /></a>
            </div>
            <div class="link pull-right">
                CDN by&nbsp;&nbsp;<a href="http://jsdelivr.com/">jsDelivr</a> &amp; <a href="http://maxcdn.com">MaxCDN</a>
            </div>
            <div class="link">
                © Ajenti Project
            </div>
            <div class="link">
                <a href="mailto:e@ajenti.org"><i class="fa fa-envelope"></i></a>
            </div>
        </div>
    </div>



    <script type='text/javascript'>
        // UserEcho --------------------
        var _ues = {
        host:'ajenti.userecho.com',
        forum:'8996',
        lang:'en',
        tab_corner_radius:8,
        tab_font_size:22,
        tab_image_hash:'RmVlZGJhY2s%3D',
        tab_alignment:'left',
        tab_text_color:'#FFFFFF',
        tab_bg_color:'#9E9E9E',
        tab_hover_color:'#595959'
        };

        (function() {
            var _ue = document.createElement('script'); _ue.type = 'text/javascript'; _ue.async = true;
            _ue.src = ('https:' == document.location.protocol ? 'https://s3.amazonaws.com/' : 'http://') + 'cdn.userecho.com/js/widget-1.4.gz.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(_ue, s);
          })();

    </script>

    <script type="text/javascript">
        // Analytics --------------------------
      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>

    <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=408484792592752";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
</body>
```

</html>

Loaded plugins | ajenti_org, codemirror, configurator, cron, dashboard, db_common, fm, fstab, hdparm, hosts, iptables, logs, main, mysql, network, nginx, notepad, packages, plugins, power, resolv, resources, scripts, sensors, services, supervisor, taskmgr, tasks, terminal, uname, users, vh, vh-mysql, vh-nginx, vh-php-fpm, webserver_common

| Library | Version |
| --- | --- |
| gevent | 1.0 |
| greenlet | 0.4.2 |
| reconfigure | 0.1.72 |
| requests | 2.2.1 |
| psutil | 1.2.1 |

```
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 133, in <module>
    core.run()
  File "/usr/lib/pymodules/python2.7/ajenti/core.py", line 89, in run
    Inflater.get().precache()
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 39, in precache
    self.inflate(temp_ui, layout)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 74, in inflate
    self.cache[layout] = self.inflate_rec(ui, xml)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in inflate_rec
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 110, in <genexpr>
    children = filter(None, list(self.inflate_rec(ui, child) for child in node))
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 111, in inflate_rec
    element = self.create_element(ui, tag, children=children, **props)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 46, in create_element
    inst = cls.new(ui, context=(ui or self).context, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/api/__init__.py", line 91, in new
    return context.instantiate(cls, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/__init__.py", line 202, in instantiate
    init(instance)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/controls_inputs.py", line 117, in init
    self.dialog = self.ui.create('openfiledialog')
  File "/usr/lib/pymodules/python2.7/ajenti/ui/__init__.py", line 24, in create
    return self.inflater.create_element(self, typeid, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/inflater.py", line 46, in create_element
    inst = cls.new(ui, context=(ui or self).context, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/api/__init__.py", line 91, in new
    return context.instantiate(cls, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/__init__.py", line 202, in instantiate
    init(instance)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/controls_dialogs.py", line 98, in init
    self.refresh()
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/controls_dialogs.py", line 74, in refresh
    _dirs += sorted(os.listdir(unicode(self.path)))
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc9 in position 1: invalid continuation byte
```

Log content:

```
2015-09-14 06:40:24,024 INFO     ajenti-panel.<module>(): Using config file /etc/ajenti/config.json
2015-09-14 06:40:24,044 INFO     ajenti-panel.<module>(): Ajenti starting in foreground
2015-09-14 06:40:24,092 INFO     registry.register_crypt_handler(): registered crypt handler 'sha512_crypt': <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
2015-09-14 06:40:24,170 DEBUG    compat.Popen(): Popen: git describe --tags 2> /dev/null
2015-09-14 06:40:24,191 DEBUG    compat.Popen(): Popen: ['lsb_release', '-sd']
2015-09-14 06:40:24,272 INFO     core.run(): Ajenti 1.2.22.24 running on platform: debian
2015-09-14 06:40:24,274 DEBUG    __init__.load(): Loading plugin squid
2015-09-14 06:40:24,275 DEBUG    __init__.load_recursive(): Preloading plugin dependency: main
2015-09-14 06:40:24,276 DEBUG    __init__.load(): Loading plugin main
2015-09-14 06:40:24,282 DEBUG    __init__.load(): Loading plugin squid
2015-09-14 06:40:24,284 DEBUG    __init__.load_recursive(): Preloading plugin dependency: services
2015-09-14 06:40:24,284 DEBUG    __init__.load(): Loading plugin services
2015-09-14 06:40:24,286 DEBUG    __init__.load_recursive(): Preloading plugin dependency: dashboard
2015-09-14 06:40:24,286 DEBUG    __init__.load(): Loading plugin dashboard
2015-09-14 06:40:24,289 DEBUG    __init__.load(): Loading plugin services
2015-09-14 06:40:24,476 DEBUG    compat.Popen(): Popen: ['which', 'systemctl']
2015-09-14 06:40:24,490 DEBUG    __init__.load(): Loading plugin squid
2015-09-14 06:40:24,492 DEBUG    compat.Popen(): Popen: ['which', 'squid3']
2015-09-14 06:40:24,497 DEBUG    __init__.load():  *** [squid] skipping due to BinaryDependency (squid3)
2015-09-14 06:40:24,498 DEBUG    __init__.load(): Loading plugin cron
2015-09-14 06:40:24,499 DEBUG    compat.Popen(): Popen: ['which', 'crontab']
2015-09-14 06:40:24,504 DEBUG    __init__.load(): Loading plugin sensors
2015-09-14 06:40:24,507 DEBUG    __init__.load(): Loading plugin munin
2015-09-14 06:40:24,508 DEBUG    compat.Popen(): Popen: ['which', 'munin-cron']
2015-09-14 06:40:24,513 DEBUG    __init__.load():  *** [munin] skipping due to BinaryDependency (munin-cron)
2015-09-14 06:40:24,515 DEBUG    __init__.load(): Loading plugin power
2015-09-14 06:40:24,517 DEBUG    compat.Popen(): Popen: ['which', 'systemctl']
2015-09-14 06:40:24,527 DEBUG    compat.Popen(): Popen: ['which', 'pm-hibernate']
2015-09-14 06:40:24,534 DEBUG    __init__.load(): Loading plugin ctdb
2015-09-14 06:40:24,535 DEBUG    compat.Popen(): Popen: ['which', 'ctdb']
2015-09-14 06:40:24,541 DEBUG    __init__.load():  *** [ctdb] skipping due to BinaryDependency (ctdb)
2015-09-14 06:40:24,542 DEBUG    __init__.load(): Loading plugin megaraid
2015-09-14 06:40:24,543 DEBUG    __init__.load():  *** [megaraid] skipping due to FileDependency (/opt/MegaRAID/MegaCli/MegaCli)
2015-09-14 06:40:24,544 DEBUG    __init__.load(): Loading plugin nginx
2015-09-14 06:40:24,545 DEBUG    __init__.load_recursive(): Preloading plugin dependency: webserver_common
2015-09-14 06:40:24,546 DEBUG    __init__.load(): Loading plugin webserver_common
2015-09-14 06:40:24,548 DEBUG    __init__.load(): Loading plugin nginx
2015-09-14 06:40:24,549 DEBUG    compat.Popen(): Popen: ['which', 'nginx']
2015-09-14 06:40:24,555 DEBUG    __init__.load(): Loading plugin scripts
2015-09-14 06:40:24,557 DEBUG    __init__.load_recursive(): Preloading plugin dependency: terminal
2015-09-14 06:40:24,557 DEBUG    __init__.load(): Loading plugin terminal
2015-09-14 06:40:24,569 DEBUG    __init__.load(): Loading plugin scripts
2015-09-14 06:40:24,571 DEBUG    __init__.load(): Loading plugin fail2ban
2015-09-14 06:40:24,572 DEBUG    compat.Popen(): Popen: ['which', 'fail2ban-client']
2015-09-14 06:40:24,578 DEBUG    __init__.load():  *** [fail2ban] skipping due to BinaryDependency (fail2ban-client)
2015-09-14 06:40:24,579 DEBUG    __init__.load(): Loading plugin git
2015-09-14 06:40:24,580 DEBUG    compat.Popen(): Popen: ['which', 'git']
2015-09-14 06:40:24,586 DEBUG    compat.Popen(): Popen: ['which', 'gitolite']
2015-09-14 06:40:24,591 DEBUG    __init__.load():  *** [git] skipping due to BinaryDependency (gitolite)
2015-09-14 06:40:24,592 DEBUG    __init__.load(): Loading plugin samba
2015-09-14 06:40:24,593 DEBUG    compat.Popen(): Popen: ['which', 'smbd']
2015-09-14 06:40:24,599 DEBUG    __init__.load():  *** [samba] skipping due to BinaryDependency (smbd)
2015-09-14 06:40:24,600 DEBUG    __init__.load(): Loading plugin resolv
2015-09-14 06:40:24,602 DEBUG    __init__.load(): Loading plugin codemirror
2015-09-14 06:40:24,603 DEBUG    __init__.load(): Loading plugin mongo
2015-09-14 06:40:24,604 DEBUG    __init__.load_recursive(): Preloading plugin dependency: db_common
2015-09-14 06:40:24,605 DEBUG    __init__.load(): Loading plugin db_common
2015-09-14 06:40:24,606 DEBUG    __init__.load(): Loading plugin mongo
2015-09-14 06:40:24,607 DEBUG    compat.Popen(): Popen: ['which', 'mongod']
2015-09-14 06:40:24,613 DEBUG    __init__.load():  *** [mongo] skipping due to BinaryDependency (mongod)
2015-09-14 06:40:24,614 DEBUG    __init__.load(): Loading plugin lm_sensors
2015-09-14 06:40:24,616 DEBUG    compat.Popen(): Popen: ['which', 'sensors']
2015-09-14 06:40:24,621 DEBUG    __init__.load():  *** [lm_sensors] skipping due to BinaryDependency (sensors)
2015-09-14 06:40:24,623 DEBUG    __init__.load(): Loading plugin ntpd
2015-09-14 06:40:24,624 DEBUG    compat.Popen(): Popen: ['which', 'ntpd']
2015-09-14 06:40:24,630 DEBUG    __init__.load():  *** [ntpd] skipping due to BinaryDependency (ntpd)
2015-09-14 06:40:24,631 DEBUG    __init__.load(): Loading plugin raid
2015-09-14 06:40:24,632 DEBUG    compat.Popen(): Popen: ['which', 'mdadm']
2015-09-14 06:40:24,638 DEBUG    __init__.load():  *** [raid] skipping due to BinaryDependency (mdadm)
2015-09-14 06:40:24,639 DEBUG    __init__.load(): Loading plugin exports
2015-09-14 06:40:24,640 DEBUG    compat.Popen(): Popen: ['which', 'nfsstat']
2015-09-14 06:40:24,646 DEBUG    __init__.load():  *** [exports] skipping due to BinaryDependency (nfsstat)
2015-09-14 06:40:24,647 DEBUG    __init__.load(): Loading plugin tasks
2015-09-14 06:40:24,651 DEBUG    __init__.load(): Loading plugin logs
2015-09-14 06:40:24,652 DEBUG    __init__.load(): Loading plugin uname
2015-09-14 06:40:24,654 DEBUG    __init__.load(): Loading plugin openvpn
2015-09-14 06:40:24,655 DEBUG    compat.Popen(): Popen: ['which', 'openvpn']
2015-09-14 06:40:24,661 DEBUG    __init__.load():  *** [openvpn] skipping due to BinaryDependency (openvpn)
2015-09-14 06:40:24,662 DEBUG    __init__.load(): Loading plugin bind9
2015-09-14 06:40:24,663 DEBUG    compat.Popen(): Popen: ['which', 'named']
2015-09-14 06:40:24,669 DEBUG    __init__.load():  *** [bind9] skipping due to BinaryDependency (named)
2015-09-14 06:40:24,670 DEBUG    __init__.load(): Loading plugin ajenti_org
2015-09-14 06:40:24,672 DEBUG    __init__.load(): Loading plugin supervisor
2015-09-14 06:40:24,673 DEBUG    compat.Popen(): Popen: ['which', 'supervisord']
2015-09-14 06:40:24,680 DEBUG    __init__.load(): Loading plugin network
2015-09-14 06:40:24,683 DEBUG    __init__.load(): Loading plugin nsd
2015-09-14 06:40:24,685 DEBUG    compat.Popen(): Popen: ['which', 'nsd']
2015-09-14 06:40:24,690 DEBUG    __init__.load():  *** [nsd] skipping due to BinaryDependency (nsd)
2015-09-14 06:40:24,691 DEBUG    __init__.load(): Loading plugin apache
2015-09-14 06:40:24,692 DEBUG    compat.Popen(): Popen: ['which', 'apache2']
2015-09-14 06:40:24,698 DEBUG    __init__.load():  *** [apache] skipping due to BinaryDependency (apache2)
2015-09-14 06:40:24,699 DEBUG    __init__.load(): Loading plugin csf
2015-09-14 06:40:24,701 DEBUG    compat.Popen(): Popen: ['which', 'csf']
2015-09-14 06:40:24,706 DEBUG    __init__.load():  *** [csf] skipping due to BinaryDependency (csf)
2015-09-14 06:40:24,707 DEBUG    __init__.load(): Loading plugin hosts
2015-09-14 06:40:24,708 DEBUG    __init__.load(): Loading plugin dhcpd
2015-09-14 06:40:24,710 DEBUG    compat.Popen(): Popen: ['which', 'dhcpd']
2015-09-14 06:40:24,715 DEBUG    __init__.load():  *** [dhcpd] skipping due to BinaryDependency (dhcpd)
2015-09-14 06:40:24,716 DEBUG    __init__.load(): Loading plugin snmpd
2015-09-14 06:40:24,717 DEBUG    compat.Popen(): Popen: ['which', 'snmpd']
2015-09-14 06:40:24,722 DEBUG    __init__.load():  *** [snmpd] skipping due to BinaryDependency (snmpd)
2015-09-14 06:40:24,723 DEBUG    __init__.load(): Loading plugin memcache
2015-09-14 06:40:24,724 DEBUG    compat.Popen(): Popen: ['which', 'memcached']
2015-09-14 06:40:24,729 DEBUG    __init__.load():  *** [memcache] skipping due to BinaryDependency (memcached)
2015-09-14 06:40:24,731 DEBUG    __init__.load(): Loading plugin apcups
2015-09-14 06:40:24,732 DEBUG    compat.Popen(): Popen: ['which', 'apcaccess']
2015-09-14 06:40:24,737 DEBUG    __init__.load():  *** [apcups] skipping due to BinaryDependency (apcaccess)
2015-09-14 06:40:24,739 DEBUG    __init__.load(): Loading plugin ipmi
2015-09-14 06:40:24,740 DEBUG    compat.Popen(): Popen: ['which', 'ipmitool']
2015-09-14 06:40:24,745 DEBUG    __init__.load():  *** [ipmi] skipping due to BinaryDependency (ipmitool)
2015-09-14 06:40:24,746 DEBUG    __init__.load(): Loading plugin fm
2015-09-14 06:40:24,750 DEBUG    __init__.load(): Loading plugin smartctl
2015-09-14 06:40:24,751 DEBUG    compat.Popen(): Popen: ['which', 'smartctl']
2015-09-14 06:40:24,756 DEBUG    __init__.load():  *** [smartctl] skipping due to BinaryDependency (smartctl)
2015-09-14 06:40:24,757 DEBUG    __init__.load(): Loading plugin resources
2015-09-14 06:40:24,759 DEBUG    __init__.load(): Loading plugin packages
2015-09-14 06:40:24,762 DEBUG    __init__.load(): Loading plugin users
2015-09-14 06:40:24,763 DEBUG    __init__.load(): Loading plugin hdparm
2015-09-14 06:40:24,764 DEBUG    compat.Popen(): Popen: ['which', 'hdparm']
2015-09-14 06:40:24,770 DEBUG    __init__.load(): Loading plugin notepad
2015-09-14 06:40:24,772 DEBUG    __init__.load(): Loading plugin rethink
2015-09-14 06:40:24,773 DEBUG    compat.Popen(): Popen: ['which', 'rethinkdb']
2015-09-14 06:40:24,779 DEBUG    __init__.load():  *** [rethink] skipping due to BinaryDependency (rethinkdb)
2015-09-14 06:40:24,780 DEBUG    __init__.load(): Loading plugin taskmgr
2015-09-14 06:40:24,782 DEBUG    __init__.load(): Loading plugin psql
2015-09-14 06:40:24,783 DEBUG    compat.Popen(): Popen: ['which', 'psql']
2015-09-14 06:40:24,788 DEBUG    __init__.load():  *** [psql] skipping due to BinaryDependency (psql)
2015-09-14 06:40:24,789 DEBUG    __init__.load(): Loading plugin mysql
2015-09-14 06:40:24,790 DEBUG    compat.Popen(): Popen: ['which', 'mysql']
2015-09-14 06:40:24,795 DEBUG    compat.Popen(): Popen: ['which', 'mysqld_safe']
2015-09-14 06:40:24,801 DEBUG    __init__.load(): Loading plugin hddtemp
2015-09-14 06:40:24,802 DEBUG    compat.Popen(): Popen: ['which', 'hddtemp']
2015-09-14 06:40:24,807 DEBUG    __init__.load():  *** [hddtemp] skipping due to BinaryDependency (hddtemp)
2015-09-14 06:40:24,808 DEBUG    __init__.load(): Loading plugin configurator
2015-09-14 06:40:24,812 DEBUG    __init__.load(): Loading plugin netatalk
2015-09-14 06:40:24,813 DEBUG    compat.Popen(): Popen: ['which', 'afpd']
2015-09-14 06:40:24,819 DEBUG    __init__.load():  *** [netatalk] skipping due to BinaryDependency (afpd)
2015-09-14 06:40:24,820 DEBUG    __init__.load(): Loading plugin fstab
2015-09-14 06:40:24,823 DEBUG    __init__.load(): Loading plugin iptables
2015-09-14 06:40:24,825 DEBUG    compat.Popen(): Popen: ['which', 'ip6tables']
2015-09-14 06:40:24,848 DEBUG    __init__.load(): Loading plugin plugins
2015-09-14 06:40:24,849 DEBUG    __init__.load(): Loading plugin vh-php-fpm
2015-09-14 06:40:24,851 DEBUG    __init__.load_recursive(): Preloading plugin dependency: vh
2015-09-14 06:40:24,851 DEBUG    __init__.load(): Loading plugin vh
2015-09-14 06:40:24,855 DEBUG    __init__.load(): Loading plugin vh-php-fpm
2015-09-14 06:40:24,857 DEBUG    compat.Popen(): Popen: ['which', 'php5-fpm']
2015-09-14 06:40:24,863 DEBUG    __init__.load(): Loading plugin vh-nginx
2015-09-14 06:40:24,867 DEBUG    __init__.load(): Loading plugin vh-mysql
2015-09-14 06:40:24,868 DEBUG    compat.Popen(): Popen: ['which', 'mysql']
2015-09-14 06:40:24,874 DEBUG    compat.Popen(): Popen: ['which', 'mysqld_safe']
2015-09-14 06:40:24,881 DEBUG    __init__.instantiate(): Root context instantiated [Inflater] <ajenti.ui.inflater.Inflater object at 0x7f217b7e5cd0>
2015-09-14 06:40:24,884 DEBUG    __init__.instantiate(): Root context instantiated [UI] <ajenti.ui.UI object at 0x7f2179d87cd0>
2015-09-14 06:40:24,885 DEBUG    inflater.precache(): Precaching layout main:file-dialog
2015-09-14 06:40:24,886 DEBUG    inflater.precache(): Precaching layout main:passwd-main
2015-09-14 06:40:24,888 DEBUG    inflater.precache(): Precaching layout main:file-dialog-save
2015-09-14 06:40:24,890 DEBUG    inflater.precache(): Precaching layout main:input-dialog
2015-09-14 06:40:24,891 DEBUG    inflater.precache(): Precaching layout dashboard:dash
2015-09-14 06:40:24,894 DEBUG    inflater.precache(): Precaching layout dashboard:text
2015-09-14 06:40:24,896 DEBUG    inflater.precache(): Precaching layout dashboard:welcome
2015-09-14 06:40:24,897 DEBUG    inflater.precache(): Precaching layout services:main
2015-09-14 06:40:24,900 DEBUG    inflater.precache(): Precaching layout services:bar
2015-09-14 06:40:24,901 DEBUG    inflater.precache(): Precaching layout services:widget
2015-09-14 06:40:24,903 DEBUG    inflater.precache(): Precaching layout cron:main
2015-09-14 06:40:24,910 DEBUG    inflater.precache(): Precaching layout sensors:progressbar-widget
2015-09-14 06:40:24,911 DEBUG    inflater.precache(): Precaching layout sensors:cpu-widget
2015-09-14 06:40:24,913 DEBUG    inflater.precache(): Precaching layout sensors:value-widget
2015-09-14 06:40:24,915 DEBUG    inflater.precache(): Precaching layout sensors:cpu-line
2015-09-14 06:40:24,916 DEBUG    inflater.precache(): Precaching layout power:widget
2015-09-14 06:40:24,918 DEBUG    inflater.precache(): Precaching layout webserver_common:main
2015-09-14 06:40:24,924 DEBUG    inflater.precache(): Precaching layout terminal:main
2015-09-14 06:40:24,926 DEBUG    inflater.precache(): Precaching layout terminal:config
2015-09-14 06:40:24,927 DEBUG    inflater.precache(): Precaching layout scripts:widget
2015-09-14 06:40:24,929 ERROR    core.handle_crash(): Fatal crash occured
```

**Comment by dannysuryadi** [comment]
I got the same error when accessing apache from Ajenti.

## Ajenti bug report

| Info | Value |
| --- | --- |
| Ajenti | 1.2.23.0 |
| Platform | debian / ubuntu / Ubuntu 14.04.1 LTS |
| Architecture | x86_64 x86_64 |
| Python | 2.7.6 |
| Installation | 10982843 |
| Debug | False |
| Catcher report |  |

```
404, sorry
```

Loaded plugins | ajenti_org, apache, codemirror, configurator, cron, dashboard, db_common, fail2ban, fm, fstab, hdparm, hosts, iptables, logs, main, mysql, network, notepad, packages, plugins, power, resolv, resources, scripts, sensors, services, supervisor, taskmgr, tasks, terminal, uname, users, webserver_common

| Library | Version |
| --- | --- |
| gevent | 1.0 |
| greenlet | 0.4.2 |
| reconfigure | 0.1.72 |
| requests | 2.2.1 |
| psutil | 1.2.1 |

```
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/main.py", line 163, in handle_message
    self.send_ui()
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/main.py", line 192, in send_ui
    data = json.dumps(self.ui.render())
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xab in position 18: invalid start byte
```

Log content:

```
2015-10-05 06:15:05,710 DEBUG    compat.Popen(): Popen: ['/etc/init.d/apache2', 'status']
2015-10-05 06:15:05,725 DEBUG    compat.Popen(): Popen: ['/etc/init.d/apache2', 'status']
2015-10-05 06:15:05,740 DEBUG    compat.Popen(): Popen: ['/etc/init.d/apache2', 'status']
2015-10-05 06:15:05,754 DEBUG    compat.Popen(): Popen: ['/etc/init.d/apache2', 'status']
```

**Comment by dannysuryadi** [comment]
Turns out my sites-available directory has some leftover .conf.swo and .conf.swp file with gibberish text inside when opened. Ajenti's Apache module runs perfectly after this two files were deleted.
