### ISSUE TITLE
1.2.22.13 centos 7 ajenti crash

### ISSUE THREAD

**Issue by vitteloil** [ajenti/ajenti#803]
| Info | Value |
| --- | --- |
| Ajenti | 1.2.22.13 |
| Platform | centos / centos / Linux 2.6.32-042stab111.12 x86_64 |
| Architecture | x86_64 x86_64 |
| Python | 2.7.5 |
| Installation | 36312258 |
| Debug | False |

Loaded plugins | dashboard, main, plugins, resources, scripts, terminal

| Library | Version |
| --- | --- |
| gevent | 1.0 |
| greenlet | 0.4.2 |
| reconfigure | 0.1.62 |
| requests | 2.6.0 |
| psutil | 1.2.1 |

```
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 126, in <module>
    core.run()
  File "/usr/lib/python2.7/site-packages/ajenti/core.py", line 88, in run
    ajenti.plugins.manager.load_all()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 266, in load_all
    self.load_recursive(item[0])
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 277, in load_recursive
    return self.load(name)
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 324, in load
    dependency.check()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 67, in check
    if not self.satisfied():
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 58, in satisfied
    self._was_satisfied = self.is_satisfied()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 131, in is_satisfied
    return subprocess.call(['which', self.binary_name]) == 0
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 115, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/site-packages/ajenti/compat.py", line 26, in Popen
    *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 238, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 755, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Log content:

```
2015-10-21 10:32:27,102 INFO     ajenti-panel.<module>(): Using config file /etc/ajenti/config.json
2015-10-21 10:32:27,245 DEBUG    registry.register_crypt_handler(): registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
2015-10-21 10:32:27,295 DEBUG    compat.Popen(): Popen: git describe --tags 2> /dev/null
2015-10-21 10:32:27,307 DEBUG    compat.Popen(): Popen: ['lsb_release', '-sd']
2015-10-21 10:32:27,313 DEBUG    compat.Popen(): Popen: ['uname', '-mrs']
2015-10-21 10:32:27,318 INFO     core.run(): Ajenti 1.2.22.13 running on platform: centos
2015-10-21 10:32:27,319 DEBUG    __init__.load(): Loading plugin resources
2015-10-21 10:32:27,320 DEBUG    __init__.load(): Loading plugin main
2015-10-21 10:32:27,332 DEBUG    __init__.load(): Loading plugin scripts
2015-10-21 10:32:27,333 DEBUG    __init__.load_recursive(): Preloading plugin dependency: dashboard
2015-10-21 10:32:27,333 DEBUG    __init__.load(): Loading plugin dashboard
2015-10-21 10:32:27,337 DEBUG    __init__.load(): Loading plugin scripts
2015-10-21 10:32:27,337 DEBUG    __init__.load_recursive(): Preloading plugin dependency: terminal
2015-10-21 10:32:27,337 DEBUG    __init__.load(): Loading plugin terminal
2015-10-21 10:32:27,353 DEBUG    __init__.load(): Loading plugin scripts
2015-10-21 10:32:27,354 DEBUG    __init__.load(): Loading plugin plugins
2015-10-21 10:32:27,355 DEBUG    __init__.load(): Loading plugin apache
2015-10-21 10:32:27,355 DEBUG    __init__.load_recursive(): Preloading plugin dependency: webserver_common
2015-10-21 10:32:27,355 DEBUG    __init__.load(): Loading plugin webserver_common
2015-10-21 10:32:27,355 DEBUG    __init__.load_recursive(): Preloading plugin dependency: services
2015-10-21 10:32:27,355 DEBUG    __init__.load(): Loading plugin services
2015-10-21 10:32:27,363 INFO     sm_upstart.verify(): Disabling Upstart service manager: org.freedesktop.DBus.Error.ServiceUnknown: The name c\
```

om.ubuntu.Upstart was not provided by any .service files
    2015-10-21 10:32:27,364 DEBUG    compat.Popen(): Popen: ['which', 'systemctl']
    2015-10-21 10:32:27,371 WARNING  **init**.load():  **\* [services] Plugin crashed: crashed: [Errno 2] No such file or directory
    2015-10-21 10:32:27,371 DEBUG    **init**.load(): Loading plugin supervisor
    2015-10-21 10:32:27,372 WARNING  **init**.load_recursive():  **\* Plugin dependency unsatisfied: supervisor -> services
    2015-10-21 10:32:27,372 DEBUG    **init**.load(): Loading plugin ntpd
    2015-10-21 10:32:27,372 WARNING  **init**.load_recursive():  **\* Plugin dependency unsatisfied: ntpd -> services
    2015-10-21 10:32:27,373 DEBUG    **init**.load(): Loading plugin nginx
    2015-10-21 10:32:27,373 WARNING  **init**.load_recursive():  **\* Plugin dependency unsatisfied: nginx -> webserver_common
    2015-10-21 10:32:27,373 DEBUG    **init**.load(): Loading plugin ipmi
    2015-10-21 10:32:27,374 DEBUG    compat.Popen(): Popen: ['which', 'ipmitool']
    2015-10-21 10:32:27,380 ERROR    core.handle_crash(): Fatal crash occured

**Comment by vitteloil** [comment]
I fixed it by installing 'which', which is not always here on a fresh centos install. you could consider it a depencency

**Comment by Eugeny** [comment]
Ajenti requires the `which` utility (typically installed with `coreutils`)
