### ISSUE TITLE
centos 6 ajenti not start

### ISSUE THREAD

**Issue by alfonsovinti** [ajenti/ajenti#806]
## ajenti-panel -v output

```
22.10.2015 15:08 ajenti-panel:105   INFO  Using config file /etc/ajenti/config.json
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 109, in <module>
    ajenti.config.load()
  File "/usr/lib/python2.6/site-packages/reconfigure/configs/base.py", line 46, in load
    self.nodetree = self.parser.parse(self.content)
  File "/usr/lib/python2.6/site-packages/reconfigure/parsers/jsonparser.py", line 13, in parse
    self.load_node_rec(node, json.loads(content))
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by Eugeny** [comment]
This means that your config file (/etc/ajenti/config.json) is damaged.
