### ISSUE TITLE
验证失败

### ISSUE THREAD

**Issue by Osub** [ajenti/ajenti#814]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, _args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/ajenti_plugin_core/views/api.py", line 68, in handle_api_auth
    if auth.check_password(username, password):
  File "/usr/local/lib/python2.7/site-packages/aj/auth.py", line 134, in check_password
    return self.get_provider().authenticate(username, password)
  File "/usr/local/lib/python2.7/site-packages/aj/auth.py", line 104, in authenticate
    if child and child.isalive():
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 653, in isalive
    alive = ptyproc.isalive()
  File "/usr/local/lib/python2.7/contextlib.py", line 35, in **exit**
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 24, in _wrap_ptyprocess_err
    raise ExceptionPexpect(*e.args)
ExceptionPexpect: isalive() encountered condition where "terminated" is 0, but there was no child process. Did someone else call waitpid() on our process?

**Comment by anjofael** [comment]
Same issue here:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, _args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/ajenti_plugin_core/views/api.py", line 71, in handle_api_auth
    auth_info = auth.check_password(username, password)
  File "/usr/local/lib/python2.7/site-packages/aj/auth.py", line 138, in check_password
30.08.2016 14:58  [rstrct 31011]  ERROR    Unhandled endpoint error at /api/core/auth
    return self.get_provider().authenticate(username, password)
  File "/usr/local/lib/python2.7/site-packages/aj/auth.py", line 108, in authenticate
    if child and child.isalive():
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 662, in isalive
    alive = ptyproc.isalive()
  File "/usr/local/lib/python2.7/contextlib.py", line 35, in **exit**
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 23, in _wrap_ptyprocess_err
    raise ExceptionPexpect(*e.args)
ExceptionPexpect: isalive() encountered condition where "terminated" is 0, but there was no child process. Did someone else call waitpid() on our process?
