### ISSUE TITLE
UnicodeError on Raspbian using Raspberry Pi B+

### ISSUE THREAD

**Issue by codebucketdev** [ajenti/ajenti#815]
Hello Guys,

I have a problem with my Ajenti installation. It is my third installation on a Raspberry Pi B+ and normally everything worked fine, but today my new installation has got an error while I tried to log in.

Device: Raspberry Pi B+
OS: Raspbian Wheezy

**Logfile**

```
2015-11-01 23:09:09,895 INFO     registry.register_crypt_handler(): registered crypt handler 'sha512_crypt': <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
2015-11-01 23:09:11,834 WARNING  core.run(): Couldn't set default locale
2015-11-01 23:09:11,850 INFO     core.run(): Ajenti 1.2.23.0 running on platform: debian
2015-11-01 23:09:12,124 INFO     sm_upstart.verify(): Disabling Upstart service manager: org.freedesktop.DBus.Error.ServiceUnknown: The name com.ubuntu.Upstart was not provided by any .service files
2015-11-01 23:09:21,628 INFO     core.run(): Starting server on (u'0.0.0.0', 8384)
2015-11-01 23:09:21,767 INFO     core.run(): SSL enabled: /etc/ajenti/ajenti.pem
2015-11-01 23:15:29,849 INFO     users.check_password(): user root logged in through AjentiSyncProvider from 192.168.1.23
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 523, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 153, in _close_when_done
    return handle(*args)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 130, in wrap_socket_and_handle
    return self.handle(ssl_socket, address)
  File "/usr/lib/python2.7/dist-packages/socketio/server.py", line 124, in handle
    handler.handle()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 410, in handle
    result = self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 625, in handle_one_request
    self.handle_one_response()
  File "/usr/lib/pymodules/python2.7/ajenti/http.py", line 25, in handle_one_response
    return SocketIOHandler.handle_one_response(self)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 122, in handle_one_response
    return self._do_handshake(handshake_tokens.groupdict())
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 64, in _do_handshake
    self.write_smart(data)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 88, in write_smart
    self.write_plain_result(data)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 78, in write_plain_result
    ("Content-Type", "text/plain"),
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 740, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
<Greenlet at 0x2825f80: _close_when_done(<socket at 0x2e6a590 fileno=[Errno 9] Bad file des, ('192.168.1.23', 63384))> failed with UnicodeError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 523, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 153, in _close_when_done
    return handle(*args)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 130, in wrap_socket_and_handle
    return self.handle(ssl_socket, address)
  File "/usr/lib/python2.7/dist-packages/socketio/server.py", line 124, in handle
    handler.handle()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 410, in handle
    result = self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 625, in handle_one_request
    self.handle_one_response()
  File "/usr/lib/pymodules/python2.7/ajenti/http.py", line 25, in handle_one_response
    return SocketIOHandler.handle_one_response(self)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 122, in handle_one_response
    return self._do_handshake(handshake_tokens.groupdict())
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 64, in _do_handshake
    self.write_smart(data)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 88, in write_smart
    self.write_plain_result(data)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 78, in write_plain_result
    ("Content-Type", "text/plain"),
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 740, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
<Greenlet at 0x302a530: _close_when_done(<socket at 0x2e5c7b0 fileno=[Errno 9] Bad file des, ('192.168.1.23', 63400))> failed with UnicodeError
```

**Comment by Xefir** [comment]
Have you tried to install the 1.1b4 's version of gevent ?

The current one (both stable and pre-release) don't work great with Ajenti.

To install it, please install pip and do this command :

`sudo easy_install -U gevent==1.1b4`

**Comment by Eugeny** [comment]
Recent Gevent versions have broken compatibility with existing libs, i.e. gevent-websocket. I've sent them a pull request, but you'll have to install `gevent==1.1.b3` for now.

**Comment by codebucketdev** [comment]
Thanks,
I've installed now `gevent==1.1.b3` and it works again! Maybe you should update the script and the article for Raspbian on the Knowledge Base, because there are 2 wrong lines.

http://support.ajenti.org/topic/436874-installing-on-raspbian/

Instead of

```
pip install -U gevent 
pip install greenlet==dev 
```

Should be this here:

```
pip install -U gevent==1.1b4
pip install greenlet
```

**Comment by cyclo-techtwister** [comment]
@codebucketdev Was having the issue of once ajentic's cPanel was loaded the admin page would not show anything and logout button and other was inactive. This worked for me.....

Thank You...
