### ISSUE TITLE
Ajenti not running - crashes

### ISSUE THREAD

**Issue by samapraku** [ajenti/ajenti#817]
I installed ajenti on my vps with centos 6 but it cannot start. below is the crash report

<code>
## Ajenti bug report

| Info | Value |
| --- | --- |
| Ajenti | 1.2.22.23 |
| Platform | centos / centos / Linux 2.6.32-042stab108.5 x86_64 |
| Architecture | x86_64 x86_64 |
| Python | 2.6.6 |
| Installation | 45749699 |
| Debug | True |
| Catcher report | Failed to upload traceback |
| Loaded plugins | dashboard, main |

| Library | Version |
| --- | --- |
| gevent | 1.0.1 |
| greenlet | 0.4.2 |
| reconfigure | 0.1.67 |
| requests | 2.6.0 |
| psutil | 0.6.1 |

```
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 133, in <module>
    core.run()
  File "/usr/lib/python2.6/site-packages/ajenti/core.py", line 88, in run
    ajenti.plugins.manager.load_all()
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 266, in load_all
    self.load_recursive(item[0])
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 277, in load_recursive
    return self.load(name)
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 324, in load
    dependency.check()
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 67, in check
    if not self.satisfied():
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 58, in satisfied
    self._was_satisfied = self.is_satisfied()
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 131, in is_satisfied
    return subprocess.call(['which', self.binary_name]) == 0
  File "/usr/lib64/python2.6/site-packages/gevent/subprocess.py", line 115, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.6/site-packages/ajenti/compat.py", line 26, in Popen
    *args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/gevent/subprocess.py", line 238, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/site-packages/gevent/subprocess.py", line 756, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Log content:

```
2015-11-04 08:54:30,652 INFO     ajenti-panel.<module>(): Using config file /etc/ajenti/config.json
2015-11-04 08:54:30,681 INFO     ajenti-panel.<module>(): Ajenti starting in foreground
2015-11-04 08:54:30,760 INFO     registry.register_crypt_handler(): registered crypt handler 'sha512_crypt': <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
2015-11-04 08:54:30,844 DEBUG    compat.Popen(): Popen: git describe --tags 2> /dev/null
2015-11-04 08:54:30,860 DEBUG    compat.Popen(): Popen: ['lsb_release', '-sd']
2015-11-04 08:54:30,865 DEBUG    compat.Popen(): Popen: ['uname', '-mrs']
2015-11-04 08:54:30,870 INFO     core.run(): Ajenti 1.2.22.23 running on platform: centos
2015-11-04 08:54:30,871 DEBUG    __init__.load(): Loading plugin dashboard
2015-11-04 08:54:30,872 DEBUG    __init__.load_recursive(): Preloading plugin dependency: main
2015-11-04 08:54:30,873 DEBUG    __init__.load(): Loading plugin main
2015-11-04 08:54:30,880 DEBUG    __init__.load(): Loading plugin dashboard
2015-11-04 08:54:30,882 DEBUG    __init__.load(): Loading plugin apache
2015-11-04 08:54:30,883 DEBUG    __init__.load_recursive(): Preloading plugin dependency: webserver_common
2015-11-04 08:54:30,884 DEBUG    __init__.load(): Loading plugin webserver_common
2015-11-04 08:54:30,885 DEBUG    __init__.load_recursive(): Preloading plugin dependency: services
2015-11-04 08:54:30,886 DEBUG    __init__.load(): Loading plugin services
2015-11-04 08:54:30,892 INFO     sm_upstart.verify(): Disabling Upstart service manager: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2015-11-04 08:54:30,899 DEBUG    compat.Popen(): Popen: ['which', 'systemctl']
2015-11-04 08:54:30,906 WARNING  __init__.load():  *** [services] Plugin crashed: crashed: [Errno 2] No such file or directory
2015-11-04 08:54:30,908 DEBUG    __init__.load(): Loading plugin fail2ban
2015-11-04 08:54:30,909 DEBUG    compat.Popen(): Popen: ['which', 'fail2ban-client']
2015-11-04 08:54:30,913 ERROR    core.handle_crash(): Fatal crash occured
        </code>
```

**Comment by Xefir** [comment]
Please install gevent 1.1b3 or 1.1b4.

See the numerous issues with gevent issue to know how to install it, like https://github.com/ajenti/ajenti/issues/815

Come back if it didn't resolve the issue

**Comment by Eugeny** [comment]
Ajenti requires the `which` utility (typically installed with `coreutils`)
