### ISSUE TITLE
exception occurs when change configuration

### ISSUE THREAD

**Issue by shenqiyu** [ajenti/ajenti#820]
Centos 7.1
PHP 2.7.5
ajenti clone from git

when I change configuration, such as http server port, then I click Save. a exception occurs:

**Comment by shenqiyu** [comment]
Traceback (most recent call last):
  File "/home/paulshen/python-projs/ajenti-dev/ajenti/plugins/main/main.py", line 346, in init
    cat = cls.new(self.ui)
  File "/home/paulshen/python-projs/ajenti-dev/ajenti/api/**init**.py", line 91, in new
    return context.instantiate(cls, _args, *_kwargs)
  File "/home/paulshen/python-projs/ajenti-dev/ajenti/plugins/**init**.py", line 202, in instantiate
    init(instance)
  File "/home/paulshen/python-projs/ajenti-dev/ajenti/plugins/configurator/configurator.py", line 53, in init
    self.binder = Binder(ajenti.config.tree, self.find('ajenti-config'))
  File "/home/paulshen/python-projs/ajenti-dev/ajenti/ui/binder.py", line 491, in **init**
    self.setup(object)
  File "/home/paulshen/python-projs/ajenti-dev/ajenti/ui/binder.py", line 506, in setup
    self.**autodiscover()
  File "/home/paulshen/python-projs/ajenti-dev/ajenti/ui/binder.py", line 577, in __autodiscover
    self.add(PropertyBinding(object, k, bindable, propname))
  File "/home/paulshen/python-projs/ajenti-dev/ajenti/ui/binder.py", line 135, in __init**
    raise Exception('Cannot bind %s.%s (%s, = %s) to %s' % (repr(obj), attribute, repr(type(v)), repr(v), ui))
Exception: Cannot bind <reconfigure.items.ajenti.AjentiData object at 0x21e1e90>.enable_feedback (<type 'int'>, = -1) to <checkbox # 1

**Comment by shenqiyu** [comment]
install ajenti via "yum install ajenti", also it will also happen.

**Comment by shenqiyu** [comment]
Cannot bind <reconfigure.items.ajenti.SSLData object at 0x2fa3810>.enable (<type 'int'>, = -1) to <checkbox # 6586>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/main/main.py", line 158, in handle_message
    self.ui.dispatch_event(update['uid'], update['event'], update['params'])
  File "/usr/lib/python2.7/site-packages/ajenti/ui/**init**.py", line 72, in dispatch_event
    self.root.dispatch_event(uid, event, params)
  File "/usr/lib/python2.7/site-packages/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/python2.7/site-packages/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/python2.7/site-packages/ajenti/ui/element.py", line 388, in dispatch_event
    getattr(self, k)(*_(params or {}))
  File "/usr/lib/python2.7/site-packages/ajenti/users.py", line 18, in wrapper
    return fx(_args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/configurator/configurator.py", line 195, in save
    self.refresh()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/configurator/configurator.py", line 180, in refresh
    self.binder.setup().populate()
  File "/usr/lib/python2.7/site-packages/ajenti/ui/binder.py", line 506, in setup
    self.**autodiscover()
  File "/usr/lib/python2.7/site-packages/ajenti/ui/binder.py", line 571, in __autodiscover
    self.__autodiscover(Binding.extract(object, k), bindable)
  File "/usr/lib/python2.7/site-packages/ajenti/ui/binder.py", line 577, in __autodiscover
    self.add(PropertyBinding(object, k, bindable, propname))
  File "/usr/lib/python2.7/site-packages/ajenti/ui/binder.py", line 135, in __init**
    raise Exception('Cannot bind %s.%s (%s, = %s) to %s' % (repr(obj), attribute, repr(type(v)), repr(v), ui))
Exception: Cannot bind <reconfigure.items.ajenti.SSLData object at 0x2fa3810>.enable (<type 'int'>, = -1) to <checkbox # 6586>
