### ISSUE TITLE
exception occurs when change configuration - find some hints

### ISSUE THREAD

**Issue by shenqiyu** [ajenti/ajenti#821]
when I change configuration, e.g. http server port, then I click Save. a exception occurs:

Traceback (most recent call last):
  File "/home/paul/python-projs/ajenti-dev/ajenti/plugins/main/main.py", line 158, in handle_message
    self.ui.dispatch_event(update['uid'], update['event'], update['params'])
  File "/home/paul/python-projs/ajenti-dev/ajenti/ui/**init**.py", line 72, in dispatch_event
    self.root.dispatch_event(uid, event, params)
  File "/home/paul/python-projs/ajenti-dev/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/home/paul/python-projs/ajenti-dev/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/home/paul/python-projs/ajenti-dev/ajenti/ui/element.py", line 388, in dispatch_event
    getattr(self, k)(*_(params or {}))
  File "/home/paul/python-projs/ajenti-dev/ajenti/users.py", line 18, in wrapper
    return fx(_args, **kwargs)
  File "/home/paul/python-projs/ajenti-dev/ajenti/plugins/configurator/configurator.py", line 195, in save
    self.refresh()
  File "/home/paul/python-projs/ajenti-dev/ajenti/plugins/configurator/configurator.py", line 180, in refresh
    self.binder.setup().populate()
  File "/home/paul/python-projs/ajenti-dev/ajenti/ui/binder.py", line 509, in setup
    self.**autodiscover()
  File "/home/paul/python-projs/ajenti-dev/ajenti/ui/binder.py", line 580, in __autodiscover
    self.add(PropertyBinding(object, k, bindable, propname))
  File "/home/paul/python-projs/ajenti-dev/ajenti/ui/binder.py", line 136, in __init**
    raise Exception('Cannot bind %s.%s (%s, = %s) to %s' % (repr(obj), attribute, repr(type(v)), repr(v), ui))
Exception: Cannot bind <reconfigure.items.ajenti.AjentiData object at 0x2c19e90>.enable_feedback (<type 'int'>, = -1) to <checkbox # 7553>

from config.json, I found:
"enable_feedback": -1,
the value should be true before I do configuration.

after I change the value -1 to true, restart ajenti, everything is OK.

If I uncheck the "Send feedback", then I click Save. a exception occurs again like before.
from config.json, I found:
"enable_feedback": 0,

If I change the value to false, restart ajenti, everything is OK again.

But I need help to find how to fix the value saved.

Thanks!

**Comment by shenqiyu** [comment]
Continue to look insight it:

after PropertyBinding.populate
  dump ui.properties
  [{'style': 'normal', 'bind': 'enable_feedback', 'value': True, 'visible': True, 'client': False, 'text': u'Enable', 'id': None, 'bindtransform': None}]

After uncheck 'Enable feedback' and click 'Save'

before PropertyBinding.update
  dump ui.properties
  [{'style': 'normal', 'bind': 'enable_feedback', 'value': -1, 'visible': True, 'client': False, 'text': u'Enable', 'id': None, 'bindtransform': None}]

The value of 'value' is changed to -1 which is not correct.

Are there some hints, or who will modify it to wrong value type? Thanks!

**Comment by shenqiyu** [comment]
finally, I found

**Comment by shenqiyu** [comment]
finally, I found someting

```
checkbox.prototype.detectUpdates = function() {
  var checked, r;
  r = {};
  checked = this.input.is(':checked');
  alert("checked value type: " + typeof(checked));
  if (checked !== this.properties.value) {
    alert("detect update: " + this.properties.value + "/" + checked);  
    r.value = checked;
  }
  this.properties.value = checked;
  return r;
};
```

IE return value type number, while firefox/chrome return value type of boolean.

I use IE v11.

**Comment by shenqiyu** [comment]
replace with jQuery v1.11.3, everything is OK. Thanks!
