### ISSUE TITLE
Ajenti Sercive won't start

### ISSUE THREAD

**Issue by ghost** [ajenti/ajenti#822]
Hi! I installed Ajenti via yum without errors.

But when I check service ajenti status it always says it's not running.

log:
10.11.2015 10:56 **init**.py:342               WARN   **\* [services] Plugin crashed: crashed: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 328, in load
    info.init()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/services/**init**.py", line 22, in init
    import sm_systemd
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/services/sm_systemd.py", line 14, in <module>
    class SystemdServiceManager (ServiceManager):
  File "/usr/lib/python2.7/site-packages/ajenti/api/**init**.py", line 67, in plugin
    if not cls.verify():
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/services/sm_systemd.py", line 22, in verify
    return subprocess.call(['which', 'systemctl']) == 0
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 115, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/site-packages/ajenti/compat.py", line 26, in Popen
    _args, *_kwargs)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 238, in **init**
    errread, errwrite)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 755, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

10.11.2015 10:56 **init**.py:297               DEBUG Loading plugin tasks
10.11.2015 10:56 **init**.py:286               DEBUG Preloading plugin dependency: cron
10.11.2015 10:56 **init**.py:297               DEBUG Loading plugin cron
10.11.2015 10:56 compat.py:20                  DEBUG Popen: ['which', 'crontab']
10.11.2015 10:56 core.py:191                   ERROR Fatal crash occured
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 133, in <module>
    core.run()
  File "/usr/lib/python2.7/site-packages/ajenti/core.py", line 88, in run
    ajenti.plugins.manager.load_all()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 266, in load_all
    self.load_recursive(item[0])
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 287, in load_recursive
    if not self.load_recursive(e.dependency.plugin_name):
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 277, in load_recursive
    return self.load(name)
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 324, in load
    dependency.check()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 67, in check
    if not self.satisfied():
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 58, in satisfied
    self._was_satisfied = self.is_satisfied()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 131, in is_satisfied
    return subprocess.call(['which', self.binary_name]) == 0
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 115, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/site-packages/ajenti/compat.py", line 26, in Popen
    _args, *_kwargs)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 238, in **init**
    errread, errwrite)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 755, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
10.11.2015 10:56 compat.py:20                  DEBUG Popen: ['uname', '-mp']
10.11.2015 10:56 core.py:202                   ERROR Crash report written to /root/ajenti-crash.txt
10.11.2015 10:56 core.py:203                   ERROR Please submit it to https://github.com/Eugeny/ajenti/issues/new

**Comment by Xefir** [comment]
Have you install the right version of gevent ? Please see https://github.com/ajenti/ajenti/issues/815
