### ISSUE TITLE
Ajenti v mail - Courier userdb missing error

### ISSUE THREAD

**Issue by dschense** [ajenti/ajenti#841]
Ive installed everything without problems. But after activating the mail option in ajenti and starting to activate TLS i get this error message:

[Errno 2] No such file or directory: '/etc/courier/userdb'
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/main.py", line 158, in handle_message
    self.ui.dispatch_event(update['uid'], update['event'], update['params'])
  File "/usr/lib/pymodules/python2.7/ajenti/ui/**init**.py", line 72, in dispatch_event
    self.root.dispatch_event(uid, event, params)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 388, in dispatch_event
    getattr(self, k)(**(params or {}))
  File "/var/lib/ajenti/plugins/vh-mail/main.py", line 169, in save
    self.manager.save()
  File "/var/lib/ajenti/plugins/vh-mail/api.py", line 354, in save
    self.backend.configure(self.config)
  File "/var/lib/ajenti/plugins/vh-mail/api.py", line 309, in configure
    os.chmod(self.courier_userdb, 0600)
OSError: [Errno 2] No such file or directory: '/etc/courier/userdb'

I know the problem is the userdb. Its missing, but i can not find a way to create this file.
Any hints ?

**Comment by dschense** [comment]
sorry, did not see the already opened issue:

https://github.com/ajenti/ajenti/issues/835
