### ISSUE TITLE
git user & repository management on Debian jessie

### ISSUE THREAD

**Issue by c-krause** [ajenti/ajenti#853]
Recently I installed gitolite on my Debian jessie server. In ajenti there is a plugin for git but seems not to work. Can I do anything do manage my git repositories with aneji? When I want to manage the users and repositories within ajenti I get the following error:

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/main.py", line 158, in handle_message
    self.ui.dispatch_event(update['uid'], update['event'], update['params'])
  File "/usr/lib/pymodules/python2.7/ajenti/ui/**init**.py", line 72, in dispatch_event
    self.root.dispatch_event(uid, event, params)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 378, in dispatch_event
    self.event(event, params)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 402, in event
    getattr(self, 'on_%s' % self_event)(*_(params or {}))
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/main.py", line 381, in on_switch
    child.broadcast('on_page_load')
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 356, in broadcast
    getattr(self, method)(_args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/git/main.py", line 65, in on_page_load
    self.refresh()
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/git/main.py", line 69, in refresh
    self.refresh_repositories()
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/git/main.py", line 98, in refresh_repositories
    repo.name = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Wenn I click on "continue" I get the frontend to manage git but it does not show my repositories or users. And I can not add new ones.

**Comment by AlbertoFdzM** [comment]
found the solution:
edit the next file `/usr/lib/pymodules/python2.7/ajenti/plugins/git/main.py`

and in the line 98 change this:
`repo.name = match and match.group(1)`
for this:
`repo.name = match is not None and match.group(1) or ''`

then restart ajenti: `service restart ajenti`

you should see then a repo without name (is the testing one) remove it to trigger the config files recompilation

**Comment by TRTL4LIFE** [comment]
@AlbertoFdzM solved it!

**Comment by AlbertoFdzM** [comment]
Maybe this issue should be closed?
