### ISSUE TITLE
Server crash after supervisor plugin installation

### ISSUE THREAD

**Issue by alorence** [ajenti/ajenti#854]
I just installed Ajenti on my Debian Jessie 8.2. Everything works fine, I started the web interface, login as root then install the first plugin I need: Supervisor. It installed then I restarted the web panel.
The server crash on the start:

```
09.01.2016 16:42  [master 22289]          core.py:227   WARN   Restarting by request
09.01.2016 16:42  [master 22289]          core.py:199   INFO   Process 22289 exiting normally
09.01.2016 16:42  [master 22289]       session.py:36    DEBUG  Destroying session 1
09.01.2016 16:42  [master 22289]          gate.py:52    DEBUG  Stopping child process 22305
09.01.2016 16:42  [master 22289]          gipc.py:464   DEBUG  SIGCHLD watcher callback for 22305 invoked. Exitcode stored: -15
09.01.2016 16:42  [master 22289]          core.py:234   DEBUG  Closed descriptor #19
09.01.2016 16:42  [master 22289]          core.py:234   DEBUG  Closed descriptor #18
09.01.2016 16:42  [master 22289]          core.py:234   DEBUG  Closed descriptor #16
09.01.2016 16:42  [master 22289]          core.py:234   DEBUG  Closed descriptor #15
09.01.2016 16:42  [master 22289]          core.py:234   DEBUG  Closed descriptor #14
09.01.2016 16:42  [master 22289]          core.py:234   DEBUG  Closed descriptor #13
09.01.2016 16:42  [master 22289]          core.py:234   DEBUG  Closed descriptor #12
09.01.2016 16:42  [master 22289]          core.py:234   DEBUG  Closed descriptor #11
09.01.2016 16:42  [master 22289]          core.py:234   DEBUG  Closed descriptor #10
09.01.2016 16:42  [master 22289]          core.py:234   DEBUG  Closed descriptor #9
09.01.2016 16:42  [master 22289]          core.py:234   DEBUG  Closed descriptor #8
09.01.2016 16:42  [master 22289]          core.py:234   DEBUG  Closed descriptor #7
09.01.2016 16:42  [master 22289]          core.py:234   DEBUG  Closed descriptor #6
09.01.2016 16:42  [master 22289]          core.py:234   DEBUG  Closed descriptor #4
09.01.2016 16:42  [master 22289]          core.py:234   DEBUG  Closed descriptor #3
09.01.2016 16:42  [master 22289]          core.py:239   WARN   Will restart the process now
09.01.2016 16:42  [...    22289]  DEBUG    Registering [aj.api.http.HttpMiddleware] (interface)
09.01.2016 16:42  [...    22289]  DEBUG    Registering [aj.api.http.HttpPlugin] (interface)
09.01.2016 16:42  [...    22289]  DEBUG    Registering [aj.api.http.SocketEndpoint] (interface)
09.01.2016 16:42  [...    22289]  DEBUG    Registering [aj.security.verifier.ClientCertificateVerificator] (service)
09.01.2016 16:42  [...    22289]  DEBUG    Registering [aj.auth.AuthenticationMiddleware] (service)
09.01.2016 16:42  [...    22289]  DEBUG    Registering [aj.auth.AuthenticationProvider] (interface)
09.01.2016 16:42  [...    22289]  DEBUG    Registering [aj.auth.OSAuthenticationProvider] (implementation of [aj.auth.AuthenticationProvider])
09.01.2016 16:42  [...    22289]  DEBUG    Registering [aj.auth.AuthenticationService] (service)
09.01.2016 16:42  [...    22289]  DEBUG    Registering [aj.auth.PermissionProvider] (interface)
09.01.2016 16:42  [...    22289]  DEBUG    Registering [aj.routing.CentralDispatcher] (service)
09.01.2016 16:42  [...    22289]  DEBUG    Registering [aj.gate.middleware.SocketIORouteHandler] (service)
09.01.2016 16:42  [...    22289]  DEBUG    Registering [aj.gate.middleware.GateMiddleware] (service)
09.01.2016 16:42  [...    22289]        compat.py:19    DEBUG    Popen: git describe --tags 2> /dev/null
09.01.2016 16:42  [...    22289]        compat.py:19    DEBUG    Popen: ['lsb_release', '-sd']
09.01.2016 16:42  [master 22289]          core.py:72    INFO   Loading config from /etc/ajenti/config.yml
09.01.2016 16:42  [master 22289]          core.py:77    WARN   Debug mode
09.01.2016 16:42  [master 22289]          core.py:90    INFO   Ajenti Core 2.1.6
09.01.2016 16:42  [master 22289]          core.py:91    INFO   Detected platform: debian / Debian GNU/Linux 8.2 (jessie)
09.01.2016 16:42  [master 22289]       plugins.py:63    DEBUG  Looking for plugins in /usr/local/bin
09.01.2016 16:42  [master 22289]       plugins.py:63    DEBUG  Looking for plugins in /usr/lib/python2.7
09.01.2016 16:42  [master 22289]       plugins.py:63    DEBUG  Looking for plugins in /usr/lib/python2.7/plat-x86_64-linux-gnu
09.01.2016 16:42  [master 22289]       plugins.py:63    DEBUG  Looking for plugins in /usr/lib/python2.7/lib-tk
09.01.2016 16:42  [master 22289]       plugins.py:63    DEBUG  Looking for plugins in /usr/lib/python2.7/lib-dynload
09.01.2016 16:42  [master 22289]       plugins.py:63    DEBUG  Looking for plugins in /usr/local/lib/python2.7/dist-packages
09.01.2016 16:42  [master 22289]       plugins.py:63    DEBUG  Looking for plugins in /usr/lib/python2.7/dist-packages
09.01.2016 16:42  [master 22289]       plugins.py:63    DEBUG  Looking for plugins in /usr/lib/pymodules/python2.7
09.01.2016 16:42  [master 22289]       plugins.py:272   INFO   Discovered 9 plugins
09.01.2016 16:42  [master 22289]        compat.py:19    DEBUG  Popen: ['which', 'supervisorctl']
09.01.2016 16:42  [master 22289]       plugins.py:320   DEBUG  Resolved load order for 9 plugins: ['core', 'augeas', 'passwd', 'plugins', 'dashboard', 'filesystem', 'settings', 'services', 'supervisor']
09.01.2016 16:42  [master 22289]       plugins.py:343   DEBUG  Importing plugin "core"
09.01.2016 16:42  [master 22289]          jadi.py:136   DEBUG  Registering [aj.plugins.core.api.sidebar.SidebarItemProvider] (interface)
09.01.2016 16:42  [master 22289]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.sidebar.Sidebar] (service)
09.01.2016 16:42  [master 22289]          jadi.py:164   DEBUG  Registering [aj.plugins.core.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.01.2016 16:42  [master 22289]          jadi.py:164   DEBUG  Registering [aj.plugins.core.main.Permissions] (implementation of [aj.auth.PermissionProvider])
09.01.2016 16:42  [master 22289]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.navbox.Navbox] (service)
09.01.2016 16:42  [master 22289]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.api.Handler] (implementation of [aj.api.http.HttpPlugin])
09.01.2016 16:42  [master 22289]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.config.Handler] (implementation of [aj.api.http.HttpPlugin])
09.01.2016 16:42  [master 22289]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.main.Handler] (implementation of [aj.api.http.HttpPlugin])
09.01.2016 16:42  [master 22289]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.resource_server.ResourcesHandler] (implementation of [aj.api.http.HttpPlugin])
09.01.2016 16:42  [master 22289]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.push.Push] (service)
09.01.2016 16:42  [master 22289]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.push.PushSocket] (implementation of [aj.api.http.SocketEndpoint])
09.01.2016 16:42  [master 22289]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.tasks.TasksService] (service)
09.01.2016 16:42  [master 22289]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.tasks.Handler] (implementation of [aj.api.http.HttpPlugin])
09.01.2016 16:42  [master 22289]       plugins.py:343   DEBUG  Importing plugin "augeas"
09.01.2016 16:42  [master 22289]       plugins.py:327   ERROR  [augeas]: plugin import failed: Unable to import libaugeas!
09.01.2016 16:42  [master 22289]         entry.py:47    ERROR  Fatal crash occured
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/entry.py", line 37, in start
    aj.core.run(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/aj/core.py", line 94, in run
    PluginManager.get(aj.context).load_all_from(aj.plugin_providers)
  File "/usr/local/lib/python2.7/dist-packages/aj/plugins.py", line 328, in load_all_from
    logging.error(traceback.format_exc())
  File "/usr/lib/python2.7/logging/__init__.py", line 1596, in error
    root.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1186, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1279, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1289, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1329, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python2.7/dist-packages/aj/log.py", line 79, in handle
    s += record.msg % record.args
TypeError: not enough arguments for format string
09.01.2016 16:42  [master 22289]        compat.py:19    DEBUG  Popen: ['uname', '-mp']
09.01.2016 16:42  [master 22289]         entry.py:60    ERROR  Crash report written to /root/ajenti-crash.txt
```

Crash report:

```
# cat /root/ajenti-crash.txt
Ajenti bug report
--------------------


Info | Value
----- | -----
Ajenti | 2.1.6
Platform | debian / debian / Debian GNU/Linux 8.2 (jessie)
Architecture | x86_64 unknown
Python | 2.7.9
Debug | True
Loaded plugins | core

Library | Version
------- | -------
gevent | 1.0.2
greenlet | 0.4.9
psutil | 3.3.0


    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/aj/entry.py", line 37, in start
        aj.core.run(**kwargs)
      File "/usr/local/lib/python2.7/dist-packages/aj/core.py", line 94, in run
        PluginManager.get(aj.context).load_all_from(aj.plugin_providers)
      File "/usr/local/lib/python2.7/dist-packages/aj/plugins.py", line 328, in load_all_from
        logging.error(traceback.format_exc())
      File "/usr/lib/python2.7/logging/__init__.py", line 1596, in error
        root.error(msg, *args, **kwargs)
      File "/usr/lib/python2.7/logging/__init__.py", line 1186, in error
        self._log(ERROR, msg, args, **kwargs)
      File "/usr/lib/python2.7/logging/__init__.py", line 1279, in _log
        self.handle(record)
      File "/usr/lib/python2.7/logging/__init__.py", line 1289, in handle
        self.callHandlers(record)
      File "/usr/lib/python2.7/logging/__init__.py", line 1329, in callHandlers
        hdlr.handle(record)
      File "/usr/local/lib/python2.7/dist-packages/aj/log.py", line 79, in handle
        s += record.msg % record.args
    TypeError: not enough arguments for format string

            #
```

**Comment by Xefir** [comment]
Seem's to be fixed by https://github.com/ajenti/ajenti/commit/efbf4d933f1fd4bd522250446668736aec90faec

Can you update, test and close if it's fixed ? :)

**Comment by Eugeny** [comment]
And please install the `python-augeas` package

**Comment by alorence** [comment]
Sorry guys, I don't have ajenti 2 anymore, I downgraded to v1.2.23.3 to have something working on my production server. i will consider reinstalling ajenti 2 if the bug is fixed, but I can't at the moment. I will try to update the ticket when it will be done.
