### ISSUE TITLE
core.handle_crash(): Fatal crash occured

### ISSUE THREAD

**Issue by Tusko** [ajenti/ajenti#858]
## Ajenti bug report

| Info | Value |
| --- | --- |
| Ajenti | 1.2.22.13 |
| Platform | centos / centos / Linux 3.10.0-123.8.1.el7.x86_64 x86_64 |
| Architecture | x86_64 x86_64 |
| Python | 2.7.5 |
| Installation | 51465793 |
| Debug | True |
| Catcher report | <!DOCTYPE html> |

<html xmlns="http://www.w3.org/1999/xhtml" ng:app="app">
    <head>
        <title>Ajenti Server Admin Panel</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="google-site-verification" content="x4PklNIAhqnDXEZBGXgbdxTTGGbRvEdHATuGeEaA7xg" />
        <link rel="icon" type="image/png" href="/static/home/favicon.png" />

```
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:700,400' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto:100,400' rel='stylesheet' type='text/css'>

    <script src="//cdn.jsdelivr.net/jquery/2.1.1/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/angularjs/1.2.17/angular.min.js"></script>
    <script src="//cdn.jsdelivr.net/g/bootstrap@3.0.3,ekko-lightbox,jquery.slick,angularui"></script>
    <link href="//cdn.jsdelivr.net/g/bootstrap@3.0.3(css/bootstrap.min.css)" rel="stylesheet">

    <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.slick/1.3.2/slick.css">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/fontawesome/4.0.3/css/font-awesome.css">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/angularui/0.4.0/angular-ui.min.css">

    <link rel="stylesheet" href="/static/CACHE/css/1bb1bf337770.css" type="text/css" />
    <script type="text/javascript" src="/static/CACHE/js/f756ca6b5462.js"></script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-3278102-8', 'ajenti.org');
      ga('send', 'pageview');
    </script>
</head>

<body data-spy="scroll" data-target="#navigation">
    <div class="top-area">
        <nav class="navbar">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">ajenti</a>
                </div>
                <ul class="nav navbar-nav">
                    <li>
                        <a href="http://support.ajenti.org/" target="_blank">
                            <i class="fa fa-book"></i> Docs
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/Eugeny/ajenti/" target="_blank">
                            <i class="fa fa-github"></i> GitHub
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/Eugeny/ajenti/issues/new" target="_blank">
                            <i class="fa fa-bug"></i> Report a bug
                        </a>
                    </li>
                    <li>
                        <a href="http://docs1.ajenti.org/en/latest/" target="_blank">
                            <i class="fa fa-cog"></i> Developer docs
                        </a>
                    </li>
                    <li>
                        <a href="/core/#section-licensing">
                            <i class="fa fa-usd"></i> Licensing
                        </a>
                    </li>
                </ul>
            </div>
        </nav>



    </div>

    <div id="page">

404, sorry

    </div>

    <div class="footer">
        <div class="container">
            <div class="link pull-right">
                <a href="https://mixpanel.com/f/partner"><img src="//cdn.mxpnl.com/site_media/images/partner/badge_light.png" alt="Mobile Analytics" /></a>
            </div>
            <div class="link pull-right">
                CDN by&nbsp;&nbsp;<a href="http://jsdelivr.com/">jsDelivr</a> &amp; <a href="http://maxcdn.com">MaxCDN</a>
            </div>
            <div class="link">
                © Ajenti Project
            </div>
            <div class="link">
                <a href="mailto:e@ajenti.org"><i class="fa fa-envelope"></i></a>
            </div>
        </div>
    </div>



    <script type='text/javascript'>
        // UserEcho --------------------
        var _ues = {
        host:'ajenti.userecho.com',
        forum:'8996',
        lang:'en',
        tab_corner_radius:8,
        tab_font_size:22,
        tab_image_hash:'RmVlZGJhY2s%3D',
        tab_alignment:'left',
        tab_text_color:'#FFFFFF',
        tab_bg_color:'#9E9E9E',
        tab_hover_color:'#595959'
        };

        (function() {
            var _ue = document.createElement('script'); _ue.type = 'text/javascript'; _ue.async = true;
            _ue.src = ('https:' == document.location.protocol ? 'https://s3.amazonaws.com/' : 'http://') + 'cdn.userecho.com/js/widget-1.4.gz.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(_ue, s);
          })();

    </script>

    <script type="text/javascript">
        // Analytics --------------------------
      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>

    <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=408484792592752";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
</body>
```

</html>

Loaded plugins | dashboard, main

| Library | Version |
| --- | --- |
| gevent | 1.0 |
| greenlet | 0.4.2 |
| reconfigure | 0.1.62 |
| requests | 2.6.0 |
| psutil | 1.2.1 |

```
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 133, in <module>
    core.run()
  File "/usr/lib/python2.7/site-packages/ajenti/core.py", line 88, in run
    ajenti.plugins.manager.load_all()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 266, in load_all
    self.load_recursive(item[0])
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 277, in load_recursive
    return self.load(name)
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 324, in load
    dependency.check()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 67, in check
    if not self.satisfied():
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 58, in satisfied
    self._was_satisfied = self.is_satisfied()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 131, in is_satisfied
    return subprocess.call(['which', self.binary_name]) == 0
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 115, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/site-packages/ajenti/compat.py", line 26, in Popen
    *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 238, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 755, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Log content:

```
2016-01-19 19:56:19,129 INFO     ajenti-panel.<module>(): Using config file /etc/ajenti/config.json
2016-01-19 19:56:19,158 INFO     ajenti-panel.<module>(): Ajenti starting in foreground
2016-01-19 19:56:19,305 DEBUG    registry.register_crypt_handler(): registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
2016-01-19 19:56:19,414 DEBUG    compat.Popen(): Popen: git describe --tags 2> /dev/null
2016-01-19 19:56:19,457 DEBUG    compat.Popen(): Popen: ['lsb_release', '-sd']
2016-01-19 19:56:19,473 DEBUG    compat.Popen(): Popen: ['uname', '-mrs']
2016-01-19 19:56:19,483 WARNING  core.run(): Couldn't set default locale
2016-01-19 19:56:19,484 INFO     core.run(): Ajenti 1.2.22.13 running on platform: centos
2016-01-19 19:56:19,487 DEBUG    __init__.load(): Loading plugin lm_sensors
2016-01-19 19:56:19,490 DEBUG    __init__.load_recursive(): Preloading plugin dependency: main
2016-01-19 19:56:19,490 DEBUG    __init__.load(): Loading plugin main
2016-01-19 19:56:19,502 DEBUG    __init__.load(): Loading plugin lm_sensors
2016-01-19 19:56:19,503 DEBUG    __init__.load_recursive(): Preloading plugin dependency: dashboard
2016-01-19 19:56:19,504 DEBUG    __init__.load(): Loading plugin dashboard
2016-01-19 19:56:19,510 DEBUG    __init__.load(): Loading plugin lm_sensors
2016-01-19 19:56:19,512 DEBUG    compat.Popen(): Popen: ['which', 'sensors']
2016-01-19 19:56:19,521 ERROR    core.handle_crash(): Fatal crash occured
```

**Comment by Tusko** [comment]
hey. anybody help?

**Comment by Xefir** [comment]
Seems like the usual gevent error. What's your gevent version ? Did you follow these advises ? https://github.com/ajenti/ajenti/issues/702 (TLDR : installing the 1.1b3 or 1.1b4 of gevent, the latest gevent witch is 1.1rc isn't compatible with current ajenti).

**Comment by Tusko** [comment]
@Xefir thanks for the answer.
I'm using Centos 7
How I can find it?

**Comment by Tusko** [comment]
@Xefir  Package python-gevent-1.0-2.el7.x86_64 already installed and latest version

**Comment by Xefir** [comment]
Yeah ... but no.

Install python_setuptools if it's not already installed.

And type this command : 

`sudo easy_install -U gevent==1.1b4`

**Comment by Tusko** [comment]
@Xefir  Writing /tmp/easy_install-JzxbWP/gevent-1.1b4/setup.cfg
Running gevent-1.1b4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-JzxbWP/gevent-1.1b4/egg-dist-tmp-MKB4kd
Running '(cd  "/tmp/easy_install-JzxbWP/gevent-1.1b4/libev"  && /bin/sh ./configure   && mv config.h "$OLDPWD") > configure-output.txt' in /tmp/easy_install-JzxbWP/gevent-1.1b4/build/temp.linux-x86_64-2.7/libev
gevent/gevent.corecext.c:9:22: fatal error: pyconfig.h: No such file or directory
 #include "pyconfig.h"
                      ^
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by Tusko** [comment]
@Xefir 
22.01.2016 20:02 core.py:191                   ERROR Fatal crash occured
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 133, in <module>
    core.run()
  File "/usr/lib/python2.7/site-packages/ajenti/core.py", line 88, in run
    ajenti.plugins.manager.load_all()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 266, in l                                                                                       oad_all
    self.load_recursive(item[0])
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 277, in l                                                                                       oad_recursive
    return self.load(name)
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 324, in l                                                                                       oad
    dependency.check()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 67, in ch                                                                                       eck
    if not self.satisfied():
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/**init**.py", line 58, in sa                                                                                       tisfied
    self._was_satisfied = self.is_satisfied()
  File "/usr/lib/python2.7/site-packages/ajenti/plugins/__init__.py", line 131, in i                                                                                       s_satisfied
    return subprocess.call(['which', self.binary_name]) == 0
  File "/usr/lib/python2.7/site-packages/gevent-1.1b4-py2.7-linux-x86_64.egg/gevent/                                                                                       subprocess.py", line 154, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/site-packages/ajenti/compat.py", line 26, in Popen
    _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/gevent-1.1b4-py2.7-linux-x86_64.egg/gevent/                                                                                       subprocess.py", line 446, in **init**
    reraise(*exc_info)
  File "/usr/lib/python2.7/site-packages/gevent-1.1b4-py2.7-linux-x86_64.egg/gevent/                                                                                       subprocess.py", line 415, in **init**
    restore_signals, start_new_session)
  File "/usr/lib/python2.7/site-packages/gevent-1.1b4-py2.7-linux-x86_64.egg/gevent/                                                                                       subprocess.py", line 1100, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
22.01.2016 20:02 compat.py:20                  DEBUG Popen: ['uname', '-mp']
22.01.2016 20:02 core.py:202                   ERROR Crash report written to /root/a                                                                                       jenti-crash.txt
22.01.2016 20:02 core.py:203                   ERROR Please submit it to https://git                                                                                       hub.com/Eugeny/ajenti/issues/new

**Comment by Tusko** [comment]
I have installed gevent-1.1b4 but still doesn't work

**Comment by Xefir** [comment]
Have you restart Ajenti after install gevent ?

**Comment by Tusko** [comment]
[ajenti-crash.txt](https://github.com/ajenti/ajenti/files/101831/ajenti-crash.txt)

**Comment by Xefir** [comment]
Oh, I missed a line. Seems related to https://github.com/ajenti/ajenti/issues/803

Can you install the missing `which` package ?

**Comment by Tusko** [comment]
@Xefir  `Package which-2.20-7.el7.x86_64 already installed and latest version`

**Comment by Tusko** [comment]
@Eugeny 
Здраствуйте. Возможно Вы сможете мне помочь?

**Comment by Tusko** [comment]
removed Ajenti :)
