### ISSUE TITLE
Unable to create dir - AttributeError

### ISSUE THREAD

**Issue by ChillarAnand** [ajenti/ajenti#859]
```
Server error

 Server error occured. This is likely a bug.

Request
POST /api/filesystem/create-directory//home/foo/bar

Type
AttributeError
Message
'exceptions.OSError' object has no attribute 'replace'
Traceback
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ajenti_plugin_filesystem/views.py", line 170, in handle_api_fs_create_directory
    raise EndpointError(e)
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 22, in __init__
    self.message = message or six.u(inner)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 647, in u
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
AttributeError: 'exceptions.OSError' object has no attribute 'replace'

```

**Comment by Xefir** [comment]
Fixed by Eugeny/reconfigure#17. Can you update python-reconfigure, test and close if it's good ? :)
