### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PY2'

### ISSUE THREAD

**Issue by ghost** [ajenti/ajenti#892]
```
# service ajenti restart
Stopping Ajenti:
 * not running
Starting Ajenti:
27.02.2016 09:23 INFO  Using config file /etc/ajenti/config.json
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 109, in <module>
    ajenti.config.load()
  File "/usr/lib/pymodules/python2.7/reconfigure/configs/base.py", line 42, in load
    (six.PY2 and isinstance(self.content, str)):
AttributeError: 'module' object has no attribute 'PY2'
 * failed
```

**Comment by ghost** [comment]
Python 2.7.3

**Comment by mateuszbrylski** [comment]
#891
