### ISSUE TITLE
Ajenti 2.1.11 install issue on Debian 8.4

### ISSUE THREAD

**Issue by mureev** [ajenti/ajenti#911]
Hi there,

I have an issue with instilling latest Ajenti panel on my Debian 8.4 server.

`sudo pip install ajenti-panel`

couses an error

> sudo pip install ajenti-panel
> Collecting ajenti-panel
> Using cached ajenti-panel-2.1.11.tar.gz
> Collecting aj==2.1.11 (from ajenti-panel)
> ...
> Using cached aj-2.1.11.tar.gz
> Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.7 in /usr/local/lib/python2.7/dist-packages (from gevent==1.1b3->aj==2.1.11->ajenti-panel)
> 
> Exception:
> Traceback (most recent call last):
> File "/usr/local/lib/python2.7/dist-packages/pip-8.1.1-py2.7.egg/pip/basecommand.py", line 209, in main
>     status = self.run(options, args)
> File "/usr/local/lib/python2.7/dist-packages/pip-8.1.1-py2.7.egg/pip/commands/install.py", line 310, in run
>     wb.build(autobuilding=True)
>   File "/usr/local/lib/python2.7/dist-packages/pip-8.1.1-py2.7.egg/pip/wheel.py", line 748, in build
>     self.requirement_set.prepare_files(self.finder)
>   File "/usr/local/lib/python2.7/dist-packages/pip-8.1.1-py2.7.egg/pip/req/req_set.py", line 360, in prepare_files
>     ignore_dependencies=self.ignore_dependencies))
>   File "/usr/local/lib/python2.7/dist-packages/pip-8.1.1-py2.7.egg/pip/req/req_set.py", line 647, in _prepare_file
>     set(req_to_install.extras) - set(dist.extras)
>   File "/usr/local/lib/python2.7/dist-packages/pip-8.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2810, in extras
>     return [dep for dep in self._dep_map if dep]
>   File "/usr/local/lib/python2.7/dist-packages/pip-8.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2853, in _dep_map
>     self.__dep_map = self._compute_dependencies()
>   File "/usr/local/lib/python2.7/dist-packages/pip-8.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2875, in _compute_dependencies
>     for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
>   File "/usr/local/lib/python2.7/dist-packages/pip-8.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2844, in _parsed_pkg_info
>     metadata = self.get_metadata(self.PKG_INFO)
>   File "/usr/local/lib/python2.7/dist-packages/pip-8.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1616, in get_metadata
>     return self._get(self._fn(self.egg_info, name))
>   File "/usr/local/lib/python2.7/dist-packages/pip-8.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1727, in _get
>     with open(path, 'rb') as stream:
> IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/greenlet-0.4.7.dist-info/METADATA'`

**Comment by mureev** [comment]
Looks like this issue is related to greenlet package. I am getting similar error by trying to install just greenlet

`pip install greenlet`

**Comment by mureev** [comment]
Just log an issue for greenlet
https://github.com/python-greenlet/greenlet/issues/102
