### ISSUE TITLE
Ajenti crashes while trying to start service or run ajenti-panel -v

### ISSUE THREAD

**Issue by deceptikon** [ajenti/ajenti#928]
[root@nikfm ~]# cat /root/ajenti-crash.txt                   
## Ajenti bug report

| Info | Value |
| --- | --- |
| Ajenti | 1.2.23.8 |
| Platform | centos / centos / Linux 2.6.32-openvz-042stab113.17-amd64 x86_64 |
| Architecture | x86_64 x86_64 |
| Python | 2.6.6 |
| Installation | 9489352 |
| Debug | True |
| Catcher report | Failed to upload traceback |
| Loaded plugins | dashboard, main, terminal |

| Library | Version |
| --- | --- |
| gevent | 1.0.1 |
| greenlet | 0.4.2 |
| reconfigure | 0.1.77 |
| requests | 2.6.0 |
| psutil | 0.6.1 |

```
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 133, in <module>
    core.run()
  File "/usr/lib/python2.6/site-packages/ajenti/core.py", line 88, in run
    ajenti.plugins.manager.load_all()
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 266, in load_all
    self.load_recursive(item[0])
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 277, in load_recursive
    return self.load(name)
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 324, in load
    dependency.check()
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 67, in check
    if not self.satisfied():
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 58, in satisfied
    self._was_satisfied = self.is_satisfied()
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 131, in is_satisfied
    return subprocess.call(['which', self.binary_name]) == 0
  File "/usr/lib64/python2.6/site-packages/gevent/subprocess.py", line 115, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.6/site-packages/ajenti/compat.py", line 26, in Popen
    *args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/gevent/subprocess.py", line 238, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/site-packages/gevent/subprocess.py", line 756, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Log content:

```
2016-05-28 13:34:25,242 INFO     ajenti-panel.<module>(): Using config file /etc/ajenti/config.json
2016-05-28 13:34:25,268 INFO     ajenti-panel.<module>(): Ajenti starting in foreground
2016-05-28 13:34:25,347 INFO     registry.register_crypt_handler(): registered crypt handler 'sha512_crypt': <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
2016-05-28 13:34:25,434 DEBUG    compat.Popen(): Popen: git describe --tags 2> /dev/null
2016-05-28 13:34:25,451 DEBUG    compat.Popen(): Popen: ['lsb_release', '-sd']
2016-05-28 13:34:25,457 DEBUG    compat.Popen(): Popen: ['uname', '-mrs']
2016-05-28 13:34:25,464 INFO     core.run(): Ajenti 1.2.23.8 running on platform: centos
2016-05-28 13:34:25,465 DEBUG    __init__.load(): Loading plugin terminal
2016-05-28 13:34:25,466 DEBUG    __init__.load_recursive(): Preloading plugin dependency: main
2016-05-28 13:34:25,467 DEBUG    __init__.load(): Loading plugin main
2016-05-28 13:34:25,473 DEBUG    __init__.load(): Loading plugin terminal
2016-05-28 13:34:25,483 DEBUG    __init__.load(): Loading plugin squid
2016-05-28 13:34:25,484 DEBUG    __init__.load_recursive(): Preloading plugin dependency: services
2016-05-28 13:34:25,485 DEBUG    __init__.load(): Loading plugin services
2016-05-28 13:34:25,486 DEBUG    __init__.load_recursive(): Preloading plugin dependency: dashboard
2016-05-28 13:34:25,487 DEBUG    __init__.load(): Loading plugin dashboard
2016-05-28 13:34:25,502 DEBUG    __init__.load(): Loading plugin services
2016-05-28 13:34:25,524 DEBUG    compat.Popen(): Popen: ['which', 'systemctl']
2016-05-28 13:34:25,540 WARNING  __init__.load():  *** [services] Plugin crashed: crashed: [Errno 2] No such file or directory
2016-05-28 13:34:25,541 DEBUG    __init__.load(): Loading plugin apcups
2016-05-28 13:34:25,542 DEBUG    compat.Popen(): Popen: ['which', 'apcaccess']
2016-05-28 13:34:25,548 ERROR    core.handle_crash(): Fatal crash occured
```

**Comment by Xefir** [comment]
Did you install the `which` package ?
