### ISSUE TITLE
UnicodeError with gevent 1.1.1

### ISSUE THREAD

**Issue by artooro** [ajenti/ajenti#931]
Installed Ajenti on a fresh debian 8 VM and initially port 8000 wouldn't bind because of an SSLContext error, after reading through previous issues I decided to upgrade gevent using pip. That seemed to resolve that issue, but now I get this problem, no content loads in the Ajenti UI.
All packages are up to date and backports are enabled.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 127, in wrap_socket_and_handle
    return self.handle(ssl_socket, address)
  File "/usr/lib/python2.7/dist-packages/socketio/server.py", line 124, in handle
    handler.handle()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 443, in handle
    result = self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 658, in handle_one_request
    self.handle_one_response()
  File "/usr/lib/pymodules/python2.7/ajenti/http.py", line 25, in handle_one_response
    return SocketIOHandler.handle_one_response(self)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 122, in handle_one_response
    return self._do_handshake(handshake_tokens.groupdict())
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 64, in _do_handshake
    self.write_smart(data)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 88, in write_smart
    self.write_plain_result(data)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 78, in write_plain_result
    ("Content-Type", "text/plain"),
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 778, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
<Greenlet at 0x7ff54e3459b0: _handle_and_close_when_done(<bound method SocketIOServer.wrap_socket_and_handl, <bound method SocketIOServer.do_close of <SocketIO, (<socket at 0x7ff54db63ad0 fileno=[Errno 9] Bad fi)> failed with UnicodeError
```

**Comment by Xefir** [comment]
Because the latest gevent is not compatible with Ajenti either.

You have to install a particular version of gevent there is 1.1b4 and only this version.
You have to uninstall your current update and run this command : 

`sudo pip install gevent==1.1b4`

Numerous issues was already opened or closed in this repository regarding this problem if you want more informations about the issue.

**Comment by artooro** [comment]
Ok the other issues were closed so seemed to be resolved. Is Ajenti going to be updated for this issue at some point?

I've installed 1.1b4 which does work.

**Comment by Eugeny** [comment]
The fixed `gevent-socketio` package (compatible with the new `gevent` versions) is now available in the Ajenti repo. You should be able to just update it, or install manually from http://repo.ajenti.org/debian/pool/ubuntu/g/gevent-socketio/python-gevent-socketio_0.3.7.99-1_all.deb
