### ISSUE TITLE
Ajenti crashes after "sudo npm update"

### ISSUE THREAD

**Issue by nicholaskats** [ajenti/ajenti#935]
Hello! Yesterday I needed to update npm so I can deploy a new application but unfortunately I am getting this error. Any help? Thanks!
## Ajenti bug report

| Info | Value |
| --- | --- |
| Ajenti | 1.2.23.8 |
| Platform | centos / centos / Linux 2.6.32-642.1.1.el6.x86_64 x86_64 |
| Architecture | x86_64 x86_64 |
| Python | 2.6.6 |
| Installation | 13219205 |
| Debug | False |
| Catcher report | Failed to upload traceback |
| Loaded plugins | dashboard, main |

| Library | Version |
| --- | --- |
| gevent | 1.0.1 |
| greenlet | 0.4.2 |
| reconfigure | 0.1.77 |
| requests | 2.6.0 |
| psutil | 0.6.1 |

```
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 126, in <module>
    core.run()
  File "/usr/lib/python2.6/site-packages/ajenti/core.py", line 88, in run
    ajenti.plugins.manager.load_all()
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 266, in load_all
    self.load_recursive(item[0])
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 277, in load_recursive
    return self.load(name)
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 324, in load
    dependency.check()
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 67, in check
    if not self.satisfied():
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 58, in satisfied
    self._was_satisfied = self.is_satisfied()
  File "/usr/lib/python2.6/site-packages/ajenti/plugins/__init__.py", line 131, in is_satisfied
    return subprocess.call(['which', self.binary_name]) == 0
  File "/usr/lib64/python2.6/site-packages/gevent/subprocess.py", line 115, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.6/site-packages/ajenti/compat.py", line 26, in Popen
    *args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/gevent/subprocess.py", line 238, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/site-packages/gevent/subprocess.py", line 756, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Log content:

```
2016-06-13 03:02:27,974 INFO     ajenti-panel.<module>(): Using config file /etc/ajenti/config.json
2016-06-13 03:02:28,028 INFO     registry.register_crypt_handler(): registered crypt handler 'sha512_crypt': <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
2016-06-13 03:02:28,075 DEBUG    compat.Popen(): Popen: git describe --tags 2> /dev/null
2016-06-13 03:02:28,080 DEBUG    compat.Popen(): Popen: ['lsb_release', '-sd']
2016-06-13 03:02:28,082 DEBUG    compat.Popen(): Popen: ['uname', '-mrs']
2016-06-13 03:02:28,083 INFO     core.run(): Ajenti 1.2.23.8 running on platform: centos
2016-06-13 03:02:28,083 DEBUG    __init__.load(): Loading plugin squid
2016-06-13 03:02:28,084 DEBUG    __init__.load_recursive(): Preloading plugin dependency: main
2016-06-13 03:02:28,084 DEBUG    __init__.load(): Loading plugin main
2016-06-13 03:02:28,088 DEBUG    __init__.load(): Loading plugin squid
2016-06-13 03:02:28,088 DEBUG    __init__.load_recursive(): Preloading plugin dependency: services
2016-06-13 03:02:28,088 DEBUG    __init__.load(): Loading plugin services
2016-06-13 03:02:28,088 DEBUG    __init__.load_recursive(): Preloading plugin dependency: dashboard
2016-06-13 03:02:28,088 DEBUG    __init__.load(): Loading plugin dashboard
2016-06-13 03:02:28,089 DEBUG    __init__.load(): Loading plugin services
2016-06-13 03:02:28,103 DEBUG    compat.Popen(): Popen: ['which', 'systemctl']
2016-06-13 03:02:28,106 WARNING  __init__.load():  *** [services] Plugin crashed: crashed: [Errno 2] No such file or directory
2016-06-13 03:02:28,106 DEBUG    __init__.load(): Loading plugin lm_sensors
2016-06-13 03:02:28,106 DEBUG    compat.Popen(): Popen: ['which', 'sensors']
2016-06-13 03:02:28,108 ERROR    core.handle_crash(): Fatal crash occured
```

**Comment by nicholaskats** [comment]
What I am seeing right now is:

Package which-2.19-6.el6.x86_64 already installed and latest version
Nothing to do
[root@server home]# which
bash: /usr/bin/which: No such file or directory

**Comment by nicholaskats** [comment]
Reinstalled which and everything works great, I am really scared from what it happened by just updating npm.. Thanks all
