### ISSUE TITLE
A bootstrap error has occured

### ISSUE THREAD

**Issue by Hoffimh** [ajenti/ajenti#964]
I don´t know, what I have to do.... Please help me..

Thank you.

VM37 normal:170 Angular bootstrap has failed(anonymous function) @ VM37 normal:170
VM37 normal:171 Consider sending the following error to https://github.com/ajenti/ajenti/issues/new
VM37 normal:172 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module ajenti.network due to:
Error: [$injector:nomod] Module 'ajenti.network' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.4-build.4707+sha.71cf28c/$injector/nomod?p0=ajenti.network
    at https://communitysofa.com:8000/resources/all.js:73:12
    at https://communitysofa.com:8000/resources/all.js:2041:17
    at ensure (https://communitysofa.com:8000/resources/all.js:1965:38)
    at module (https://communitysofa.com:8000/resources/all.js:2039:14)
    at https://communitysofa.com:8000/resources/all.js:4523:22
    at forEach (https://communitysofa.com:8000/resources/all.js:328:20)
    at loadModules (https://communitysofa.com:8000/resources/all.js:4507:5)
    at https://communitysofa.com:8000/resources/all.js:4524:40
    at forEach (https://communitysofa.com:8000/resources/all.js:328:20)
    at loadModules (https://communitysofa.com:8000/resources/all.js:4507:5)
http://errors.angularjs.org/1.5.4-build.4707+sha.71cf28c/$injector/modulerr…%20(https%3A%2F%2Fcommunitysofa.com%3A8000%2Fresources%2Fall.js%3A4507%3A5)
    at https://communitysofa.com:8000/resources/all.js:73:12
    at https://communitysofa.com:8000/resources/all.js:4546:15
    at forEach (https://communitysofa.com:8000/resources/all.js:328:20)
    at loadModules (https://communitysofa.com:8000/resources/all.js:4507:5)
    at https://communitysofa.com:8000/resources/all.js:4524:40
    at forEach (https://communitysofa.com:8000/resources/all.js:328:20)
    at loadModules (https://communitysofa.com:8000/resources/all.js:4507:5)
    at createInjector (https://communitysofa.com:8000/resources/all.js:4429:19)
    at doBootstrap (https://communitysofa.com:8000/resources/all.js:1717:20)
    at Object.bootstrap (https://communitysofa.com:8000/resources/all.js:1738:12)
http://errors.angularjs.org/1.5.4-build.4707+sha.71cf28c/$injector/modulerr…20(https%3A%2F%2Fcommunitysofa.com%3A8000%2Fresources%2Fall.js%3A1738%3A12)

**Comment by briansok** [comment]
got the same problem...

**Comment by Eugeny** [comment]
Make sure that Ajenti packages are at the latest version: `sudo pip list --outdated | grep aj`

**Comment by briansok** [comment]
try: `sudo pip uninstall ajenti.plugin.network` This wil delete the broken package and you can reinstall it later if you need it. This worked for me

**Comment by Eugeny** [comment]
This was indeed fixed in the latest plugin version.
